import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:http';
import {chromium} from 'playwright';
import {ControlSettings} from '../dist/observability/control-settings.js';
import {prepareLocalConnection} from '../dist/onboarding/connection.js';
import {loadHostConfig} from '../dist/interface/config.js';
import {modelSettingsPath,readModelSettings,NEW_SUBSCRIPTION_DEFAULTS} from '../dist/onboarding/model-settings.js';
import {claudeModelCatalog} from '../dist/onboarding/model-catalog.js';
import {WorkDeliverySettings} from '../dist/work/delivery-settings.js';
const koPage=async(browser,options)=>{const page=await browser.newPage(options);await page.addInitScript(()=>{try{localStorage.setItem('office-lang','ko')}catch{}});return page;};

test('runtime native local settings UI desktop/mobile completes wizard, probes provider and masks keys (fixture provider)',async()=>{
  const browser=await chromium.launch({headless:true});await mkdir('tests/evidence/phase58',{recursive:true});
  try{for(const width of [1440,390]){
    const root=await mkdtemp(join(tmpdir(),'driver-settings-ui-')),paths=await prepareLocalConnection(root),config=loadHostConfig(paths.runtimeConfig);
    let loggedIn=false,loginCalls=0,installed=false,installCalls=0;
    const auth={async connections(){return [{id:'codex',status:loggedIn?'ready':'signed_out',structured_bridge:true,supported_login_flows:['device'],connection:{client_id:'codex',state:'idle'}}];},view(){return {state:'idle'};},close(){},async start(id,flow){assert.equal(id,'codex');assert.equal(flow,'device');loginCalls++;loggedIn=true;return {client_id:id,state:'waiting',device_url:'https://auth.example.test/device',user_code:'FIXTURE-CODE'};}};
    let providerCalls=0;const providerFetch=async(_url,options)=>{if(options?.method==='POST')providerCalls++;return new Response(JSON.stringify(options?.method==='POST'?{status:'completed',model:'gpt-5.6-luna',output:[{type:'message',phase:'final_answer',content:[{type:'output_text',text:'{"status":"ok","nonce":"agent-driver-provider-probe"}'}]}],usage:{input_tokens:1,output_tokens:1,total_tokens:2}}:{data:[{id:'gpt-5.6-luna'}]}),{status:200,headers:{'content-type':'application/json'}});};
    let mcpRegistered=false;const mcp={async view(){const registration=mcpRegistered?'registered':'not_registered';return {agent_driver:{installed:true,mcp_command:'agent-driver mcp'},clients:[{id:'codex',installed:true,registration,automatic:true,reason:registration,restart_required:mcpRegistered}],registered_count:mcpRegistered?1:0,windows_bridge:{command:'wsl.exe',args:['--distribution','Ubuntu-24.04','--user','fixture','--exec','/usr/bin/node','/home/fixture/agent-driver/dist/cli.js','mcp'],registration:'manual_unverified'},credentials_exposed:false};},async register(id){assert.equal(id,'codex');mcpRegistered=true;return this.view();}};
    const activity=undefined,bootstrap={view(){return {clients:[{id:'codex',label:'Codex',docs_url:'https://learn.chatgpt.com/docs/codex/cli',installer_url:'https://chatgpt.com/codex/install.sh',install_command:'curl -fsSL https://chatgpt.com/codex/install.sh | sh',auth_guide_url:'https://learn.chatgpt.com/docs/auth',installed:true,managed_install:true,reason:'installed',credentials_exposed:false},{id:'claude',label:'Claude Code',docs_url:'https://code.claude.com/docs/en/quickstart',installer_url:'https://claude.ai/install.sh',install_command:'curl -fsSL https://claude.ai/install.sh | bash',auth_guide_url:'https://code.claude.com/docs/en/quickstart',installed,managed_install:true,reason:installed?'installed':'not_installed',credentials_exposed:false}],credentials_exposed:false};},async install(id,onStage){assert.equal(id,'claude');installCalls++;await onStage('downloading');await onStage('downloaded',{byte_count:100});await onStage('running');await onStage('installer_exited',{exit_code:0,elapsed_ms:10});installed=true;return this.view();}};
    const settings=new ControlSettings(config,auth,{},providerFetch,mcp,activity,bootstrap),deliverySettings=WorkDeliverySettings.fromConfig(config);
    let maintenance={enabled:true,revision:0,interval_hours:24,next_due_at:null,state:'idle',clients:[{id:'codex',label:'Codex',installed:true,managed_update:true,eligibility_reason:'eligible',reason:'updated',last_success_at:'2026-09-30T00:00:00.000Z'}]},maintenanceSaves=0,maintenanceUpdates=0,host;
    const maintenanceView=()=>({...maintenance,preference_saved:maintenanceSaves>0});
    // This native UI fixture supplies its connected-client catalog as well as
    // auth and provider replies. An installed developer account is not fixture
    // evidence that the new-install default or tested Claude alias is available.
    const fixtureCatalogs={codex:{source:'fixture_codex_app_server',status:'available',models:[{id:NEW_SUBSCRIPTION_DEFAULTS.codex,label:'Fixture Codex default'}],fetched_at:'2026-09-30T00:00:00.000Z'},claude:claudeModelCatalog(),opencode:{source:'fixture_opencode_cli',status:'unavailable',models:[],fetched_at:null}};
    const server=createServer(async(req,res)=>{
      if(req.url==='/test/'){res.end('<h1>Control Center</h1>');return;}
      if(req.url==='/test/settings/models'&&req.method==='GET'){res.setHeader('content-type','application/json');res.end(JSON.stringify(fixtureCatalogs));return;}
      if(req.url==='/test/settings/maintenance/status'&&req.method==='GET'){res.setHeader('content-type','application/json');res.end(JSON.stringify(maintenanceView()));return;}
      if(req.url==='/test/settings/maintenance/settings'&&req.method==='POST'){assert.equal(req.headers['x-agent-driver'],'human-settings');let body='';for await(const chunk of req)body+=String(chunk);const input=JSON.parse(body);assert.equal(input.revision,maintenance.revision);maintenance={...maintenance,revision:maintenance.revision+1,enabled:input.enabled,state:input.enabled?'idle':'disabled'};maintenanceSaves++;res.setHeader('content-type','application/json');res.end(JSON.stringify(maintenanceView()));return;}
      if(req.url==='/test/settings/maintenance/update-now'&&req.method==='POST'){assert.equal(req.headers['x-agent-driver'],'human-settings');maintenanceUpdates++;maintenance={...maintenance,state:maintenance.enabled?'idle':'disabled'};res.setHeader('content-type','application/json');res.end(JSON.stringify({state:maintenanceUpdates===2?'deferred_busy':maintenance.state,attempted_ids:[],updated_ids:[],skipped:maintenanceUpdates===2?[{id:'codex',reason:'busy'}]:[],next_due_at:null}));return;}
      if(req.url==='/test/delivery/status'&&req.method==='GET'){res.setHeader('content-type','application/json');res.end(JSON.stringify(deliverySettings.publicState()));return;}
      if(req.url==='/test/delivery/settings'&&req.method==='POST'){assert.equal(req.headers.origin,'http://'+host);assert.equal(req.headers['x-agent-driver'],'human-office');let body='';for await(const chunk of req)body+=String(chunk);res.setHeader('content-type','application/json');res.end(JSON.stringify(deliverySettings.save(JSON.parse(body))));return;}
      if(!await settings.handle(req,res,req.url.slice('/test/'.length),host)){res.writeHead(404);res.end();}
    });await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));host='127.0.0.1:'+server.address().port;
    const page=await koPage(browser,{viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
    try{
await page.goto('http://'+host+'/test/settings');await page.getByRole('heading',{name:"AI 앱 연결",exact:true}).waitFor();await page.getByRole('button',{name:'Claude Code 설치',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Claude Code 설치',exact:true}).count(),1);assert.equal(await page.getByRole('link',{name:'공식 설치 안내',exact:true}).count(),0);await page.getByText('Windows AI 앱 연결 · 선택',{exact:true}).waitFor();assert.equal(await page.locator('#mcp-next').isEnabled(),true);await page.locator('#windows-bridge summary').click();assert.match(await page.locator('#windows-bridge-config').textContent(),/wsl\.exe/u);assert.match(await page.getByRole('status').textContent(),/Windows AI 앱 연결을 선택하세요/u);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.locator('#copy-windows-bridge').click();assert.ok((await page.evaluate(()=>navigator.clipboard.readText())).includes('wsl.exe'));await page.screenshot({path:'tests/evidence/phase58/client-bootstrap-'+width+'.png',fullPage:true});await page.getByRole('button',{name:'Claude Code 설치',exact:true}).click();await page.getByText("Claude Code · 연결 필요",{exact:true}).waitFor();assert.equal(installCalls,1);assert.equal(await page.getByRole('button',{name:'Claude Code 설치',exact:true}).count(),0);
      await page.getByRole('button',{name:'Codex 로그인',exact:true}).click();await page.getByText('FIXTURE-CODE',{exact:true}).waitFor();assert.equal(loginCalls,1);assert.equal(await page.getByRole('link',{name:'인증 열기'}).getAttribute('href'),'https://auth.example.test/device');
      await page.locator('#refresh-mcp').click();await page.getByRole('button',{name:'Codex MCP 연결',exact:true}).click();await page.getByText("Codex · 연결 등록됨",{exact:true}).waitFor();await page.getByRole('button',{name:'다음',exact:true}).click();await page.getByRole('heading',{name:"브라우저와 로그인 환경",exact:true}).waitFor();await page.getByRole('button',{name:"실행 환경 연결",exact:true}).click();await page.getByRole('heading',{name:"업무 기본값",exact:true}).waitFor();
      const ai=page.locator('#step-2');assert.equal(await ai.getByLabel("AI 앱 자동 업데이트").isChecked(),true);assert.match(await page.locator('#cli-maintenance-status').textContent(),/자동 확인은 AI 설정 저장 후 적용.*24시간 간격.*최근 성공/u);assert.equal(maintenanceSaves,0);await page.waitForFunction(()=>!document.getElementById('cli-update-now').disabled);await ai.getByRole('button',{name:'지금 업데이트'}).click();await page.getByRole('status').filter({hasText:'CLI 업데이트 확인을 마쳤어요.'}).waitFor();assert.equal(maintenanceUpdates,1);assert.equal(maintenanceSaves,0);await ai.getByLabel('Claude Code 모델',{exact:true}).selectOption('sonnet');assert.equal(await ai.getByLabel("AI 사용 방식",{exact:true}).count(),0,'API mode is no longer offered for Work defaults');assert.equal(await ai.getByLabel('API 키',{exact:true}).count(),0);assert.equal(readModelSettings(modelSettingsPath(config)),null);assert.equal(maintenanceSaves,0);
      await ai.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('status').filter({hasText:'저장했어요'}).waitFor();assert.equal(maintenanceSaves,1);assert.equal(maintenance.enabled,true);assert.doesNotMatch(await page.locator('#cli-maintenance-status').textContent(),/저장 후 적용/u);assert.equal(readModelSettings(modelSettingsPath(config)).selection.mode,'subscription');assert.equal(readModelSettings(modelSettingsPath(config)).selection.client_models.claude,'sonnet');assert.match(await ai.getByLabel('Claude Code 모델',{exact:true}).locator('option:checked').textContent(),/앱 기본 모델 · 버전은 달라질 수 있어요/u);assert.equal(providerCalls,0,'no provider is probed without API mode');
      await ai.getByLabel("AI 앱 자동 업데이트").uncheck();await page.locator('#cli-maintenance-status').filter({hasText:'꺼짐'}).waitFor();assert.equal(maintenanceSaves,2);assert.equal(await ai.getByRole('button',{name:'지금 업데이트'}).isEnabled(),true);await ai.getByRole('button',{name:'지금 업데이트'}).click();await page.getByRole('status').filter({hasText:"업무 실행 중이라 업데이트를 미뤘어요."}).waitFor();assert.equal(maintenanceUpdates,2);assert.equal(await ai.getByRole('button',{name:'지금 업데이트'}).isEnabled(),true);await ai.getByRole('button',{name:'지금 업데이트'}).click();await page.locator('#cli-maintenance-status').filter({hasText:'꺼짐'}).waitFor();assert.equal(maintenanceUpdates,3);await ai.getByLabel("AI 앱 자동 업데이트").check();await page.locator('#cli-maintenance-status').filter({hasText:'대기 중'}).waitFor();assert.equal(maintenanceSaves,3);
      await page.locator('.terminal summary').click();assert.equal(await page.locator('#setup-log').isVisible(),true);const tail=await page.locator('#setup-log').textContent();assert.match(tail,/Claude Code 설치 확인 완료/u);assert.match(tail,/공식 AI 로그인 절차를 시작/u);assert.match(tail,/\[MCP · 완료\].*Codex MCP 등록 완료 · [0-9.]+초/su);assert.match(tail,/\[RUNTIME · 완료\].*로컬 실행 연결을 승인했어요/su);assert.doesNotMatch(tail,/fixture-secret/iu);
      await page.screenshot({path:'tests/evidence/phase58/settings-defaults-'+width+'.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
      await page.reload();await page.getByRole('heading',{name:"업무 기본값",exact:true}).waitFor();assert.equal(await ai.getByLabel('Claude Code 모델',{exact:true}).isVisible(),true);assert.equal(await ai.getByLabel('Claude Code 모델',{exact:true}).inputValue(),'sonnet');await ai.getByRole('button',{name:'다음',exact:true}).click();await page.getByRole('heading',{name:'Jev 연결',exact:true}).waitFor();assert.equal(await page.getByText('4 / 5',{exact:true}).count(),1);assert.equal(await page.getByRole('button',{name:'사이트',exact:true}).count(),0);const jev=page.locator('#step-3');await jev.getByLabel('사용 방식',{exact:true}).selectOption('off');await jev.getByRole('button',{name:'다음',exact:true}).click();await page.getByRole('heading',{name:"결과 보내기",exact:true}).waitFor();assert.equal(await page.getByText('5 / 5',{exact:true}).count(),1);assert.equal(await page.locator('#delivery-defaults input[value="app"]').isChecked(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#finish-delivery').click();await page.getByRole('heading',{name:'Control Center'}).waitFor();
      const saved=readModelSettings(modelSettingsPath(config));assert.equal(saved.onboarding_step,4);assert.equal(saved.selection.mode,'subscription');assert.equal(saved.selection.jev,'off');assert.deepEqual(deliverySettings.publicState().default_target_ids,['app']);assert.equal(deliverySettings.publicState().revision,1);assert.equal(providerCalls,0);assert.equal(loginCalls,1);assert.equal(installCalls,1);assert.deepEqual(errors,[]);
    }finally{await page.close();await settings.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await rm(root,{recursive:true,force:true});}
  }}finally{await browser.close();}
});
