import test from 'node:test';
import assert from 'node:assert/strict';

test('runtime fixture Hide takes a Work off the feed, the board and the counts into the Hidden view, and Show again brings it back',async t=>{
  const {mkdtemp,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{chromium}=await import('playwright');
  const {prepareLocalConnection}=await import('../dist/onboarding/connection.js'),{loadHostConfig}=await import('../dist/interface/config.js'),{startControlCenter}=await import('../dist/observability/control-center.js');
  const {PackStore}=await import('../dist/packs/store.js'),{hiddenWorkIds}=await import('../dist/work/hidden.js'),{WorkResults}=await import('../dist/work/results.js');
  const root=await mkdtemp(join(tmpdir(),'work-hide-')),config=loadHostConfig((await prepareLocalConnection(root)).runtimeConfig);
  const store=new PackStore(config.dbPath);store.registerProject(config.project);new WorkResults(store);
  const work=(key,title)=>{const id=store.beginWork(config.project.id,key,title,'quick').work.id;store.hermesState.prepare("UPDATE office_intake SET status='ready' WHERE work_id=?").run(id);store.hermesState.prepare('UPDATE office_work SET title=? WHERE id=?').run(title,id);return id;};
  const personal=work('hide-personal','개인 업무'),shown=work('hide-shown','보여 줄 업무');
  for(const [i,id] of [personal,shown].entries())store.hermesState.prepare('INSERT INTO office_result VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(`00000000-0000-4000-8000-00000000000${i}`,config.project.id,id,'run-'+i,'client',0,'succeeded','verified','client-output',JSON.stringify({binding_revision:0,summary:'결과 '+i,text:'결과 '+i,delivery_text:'결과 '+i,completion_verified:true,artifacts:[],sources:[]}),'x'+i,new Date(Date.now()-i*60_000).toISOString());
  store.close();
  const server=await startControlCenter(config),browser=await chromium.launch({headless:true});
  t.after(async()=>{await browser.close();await server.close();await rm(root,{recursive:true,force:true});});
  const context=await browser.newContext({viewport:{width:1280,height:900}});await context.addInitScript(()=>localStorage.setItem('office-lang','en'));
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const authors=async()=>{await page.locator('.post').first().waitFor();return (await page.locator('.post .who strong').allInnerTexts()).sort()};
  await page.goto(server.url);assert.deepEqual(await authors(),['개인 업무','보여 줄 업무']);
  await page.locator('.post',{hasText:'개인 업무'}).locator('[data-feed-open]').first().click();await page.locator('[data-work-hide="hide"]').click();await page.locator('[data-work-hide="show"]').waitFor();
  const read=new PackStore(config.dbPath);assert.deepEqual([...hiddenWorkIds(read,config.project.id)],[personal]);read.close();
  await page.locator('#back').click();
  await page.waitForFunction(()=>document.querySelectorAll('.post').length===1);assert.deepEqual(await authors(),['보여 줄 업무'],'a hidden Work leaves the feed');
  assert.deepEqual([await page.locator('[data-count="all"]').innerText(),await page.locator('[data-count="hidden"]').innerText()],['1','1']);
  await page.locator('[data-view="all"]').click();await page.locator('.tile').first().waitFor();
  assert.deepEqual(await page.locator('.tile').evaluateAll(n=>n.map(t=>t.dataset.work)),[shown]);
  await page.locator('[data-view="hidden"]').click();await page.waitForFunction(()=>document.querySelectorAll('.tile').length===1);
  assert.deepEqual(await page.locator('.tile').evaluateAll(n=>n.map(t=>t.dataset.work)),[personal],'the Hidden view holds only hidden Works');
  await page.locator('.tile[data-work="'+personal+'"]').click();await page.locator('[data-work-hide="show"]').click();await page.locator('[data-work-hide="hide"]').waitFor();
  await page.locator('[data-view="feed"]').click();await page.waitForFunction(()=>document.querySelectorAll('.post').length===2);
  assert.equal(await page.locator('[data-count="hidden"]').innerText(),'');
  const forged=await page.evaluate(async id=>(await fetch('work/hide',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({work_id:id,hidden:true})})).status,personal);
  assert.equal(forged,403,'only the Office page can hide');
  assert.deepEqual(errors,[]);
});
