import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {prepareLocalConnection} from '../dist/onboarding/connection.js';
import {loadHostConfig} from '../dist/interface/config.js';
import {PackStore} from '../dist/packs/store.js';
import {RemoteOffice} from '../dist/work/remote.js';
import {remoteTargetSchema,validateRemoteCall,remoteCommand} from '../dist/integrations/remote-openclaw.js';
import {startControlCenter} from '../dist/observability/control-center.js';
import {tools} from '../dist/interface/catalog.js';
import {chromium} from 'playwright';

export const target={name:'테스트 원격 서버',host:'example.invalid',user:'agent',container:'openclaw',entry:'/app/openclaw.mjs'};
export function fake(){const calls=[];let down=false,loseAck=false,status='timeout';return {calls,setDown(v){down=v},loseNextAck(){loseAck=true},finish(){status='ok'},async call(t,m,p){calls.push({m,p});if(down)throw Error('fixture offline');if(m==='sessions.list')return {sessions:[{key:'agent:main:office',label:'원격 테스트 업무'}]};if(m==='cron.list')return {jobs:[{id:'job-1',name:'기존 서버 예약',enabled:true,schedule:{expr:'0 20 * * *'}}]};if(m==='cron.runs')return {entries:[{status:'ok',ts:1,summary:'예약 기록'}]};if(m==='chat.history')return {sessionId:'session-owned',messages:[{role:'assistant',content:[{type:'thinking',thinking:'hidden'},{type:'text',text:'fixture reply token=secret123'}]},{role:'tool',content:'secret tool'}]};if(m==='chat.send'){if(loseAck){loseAck=false;throw Error('lost ack')}return {runId:p.idempotencyKey,status:'started'}}if(m==='chat.abort')return {aborted:true,runIds:[p.runId]};if(m==='agent.wait')return {status,runId:p.runId};throw Error('unhandled '+m)}}
}
async function setup(t,transport=fake()){const root=await mkdtemp(join(tmpdir(),'remote-office-'));const paths=await prepareLocalConnection(root),config=loadHostConfig(paths.runtimeConfig),store=new PackStore(config.dbPath);store.registerProject(config.project);const runtime=new RemoteOffice(store,config,transport);t.after(async()=>{await runtime.drain();store.close();await rm(root,{recursive:true,force:true})});return {root,config,store,runtime,transport}}

test('runtime unit remote transport validates destination and limits gateway operations',()=>{
 assert.throws(()=>remoteTargetSchema.parse({...target,host:'-oProxyCommand=bad'}));assert.throws(()=>remoteTargetSchema.parse({...target,container:'open;touch /tmp/x'}));assert.throws(()=>remoteTargetSchema.parse({...target,entry:'/app/../secret.mjs'}));assert.throws(()=>validateRemoteCall('config.set',{}));assert.throws(()=>validateRemoteCall('chat.send',{sessionKey:'x',message:'test',idempotencyKey:randomUUID(),deliver:true}));assert.throws(()=>validateRemoteCall('chat.abort',{sessionKey:'x'}));assert.match(remoteCommand(target),/^docker exec -i 'openclaw' node -e /);assert.doesNotMatch(remoteCommand(target),/StrictHostKeyChecking=no/);
});
test('runtime fixture remote discovery and repeated linking preserve server schedule and create no execution',async t=>{
 const {runtime,transport,store,config}=await setup(t);const a=runtime.register(target);assert.equal(runtime.register(target).id,a.id);const list=await runtime.discover({target_id:a.id});assert.equal(list.candidates.length,2);const request={target_id:a.id,kind:'session',source_id:'agent:main:office',acknowledged:true};const [one,two]=await Promise.all([runtime.link(request),runtime.link(request)]);assert.equal(one.work_id,two.work_id);assert.equal(store.hermesState.prepare('SELECT count(*) n FROM office_work WHERE project_id=?').get(config.project.id).n,1);assert.ok(transport.calls.every(c=>['sessions.list','cron.list'].includes(c.m)));assert.equal(runtime.status(one.work_id).remote.can_send,false);await runtime.refresh(one.work_id);assert.equal(runtime.status(one.work_id).remote.can_send,true);assert.doesNotMatch(JSON.stringify(runtime.status(one.work_id)),/secret123|hidden|secret tool/);
});
test('runtime fixture remote consent, proposal, idempotency and restart never replay an instruction',async t=>{
 const {runtime,transport,store,config}=await setup(t),target_id=runtime.register(target).id,{work_id}=await runtime.link({target_id,kind:'session',source_id:'agent:main:office',acknowledged:true});await runtime.refresh(work_id);const request_id=randomUUID(),instruction='read this fixture only';runtime.propose({work_id,request_id,instruction});assert.equal(transport.calls.filter(c=>c.m==='chat.send').length,0);let revision=runtime.status(work_id).revision;await assert.rejects(runtime.action({work_id,revision,action:'send',request_id,instruction}),/CONSENT/);const req={work_id,revision,action:'send',request_id,instruction,cost_acknowledged:true};await runtime.action(req);await runtime.action(req);assert.equal(transport.calls.filter(c=>c.m==='chat.send').length,1);assert.equal(transport.calls.find(c=>c.m==='chat.send').p.deliver,false);await assert.rejects(runtime.action({...req,instruction:'different'}),/CONFLICT/);const reopened=new RemoteOffice(store,config,transport);await reopened.refresh(work_id);assert.equal(transport.calls.filter(c=>c.m==='chat.send').length,1);assert.equal(reopened.status(work_id).run_status,'reconciliation_required');transport.finish();await reopened.refresh(work_id);assert.equal(reopened.status(work_id).run_status,'needs_human');assert.equal(reopened.status(work_id).completion_verified,false);await reopened.action({work_id,revision:reopened.status(work_id).revision,action:'review'});assert.equal(reopened.status(work_id).remote.can_send,true);
});
test('runtime fixture lost acknowledgment and offline refresh preserve evidence without replay or false completion',async t=>{
 const {runtime,transport}=await setup(t),target_id=runtime.register(target).id,{work_id}=await runtime.link({target_id,kind:'session',source_id:'agent:main:office',acknowledged:true});await runtime.refresh(work_id);const req={work_id,revision:runtime.status(work_id).revision,action:'send',request_id:randomUUID(),instruction:'read fixture',cost_acknowledged:true};transport.loseNextAck();await runtime.action(req);await runtime.action(req);assert.equal(transport.calls.filter(c=>c.m==='chat.send').length,1);assert.equal(runtime.status(work_id).run_status,'reconciliation_required');const prior=runtime.status(work_id).remote.snapshot;transport.setDown(true);await runtime.refresh(work_id);assert.deepEqual(runtime.status(work_id).remote.snapshot,prior);assert.equal(runtime.status(work_id).remote.can_send,false);transport.setDown(false);await runtime.refresh(work_id);await assert.rejects(runtime.action({work_id,revision:runtime.status(work_id).revision,action:'review'}),/REMOTE_UNCERTAIN/);
});
test('runtime fixture remote stop is scoped to owned run and jobs stay read only',async t=>{
 const {runtime,transport}=await setup(t),target_id=runtime.register(target).id,{work_id}=await runtime.link({target_id,kind:'session',source_id:'agent:main:office',acknowledged:true});await runtime.refresh(work_id);await assert.rejects(runtime.action({work_id,revision:runtime.status(work_id).revision,action:'stop'}),/NO_OWNED/);const request_id=randomUUID();await runtime.action({work_id,revision:runtime.status(work_id).revision,action:'send',request_id,instruction:'fixture turn',cost_acknowledged:true});await runtime.action({work_id,revision:runtime.status(work_id).revision,action:'stop'});assert.equal(transport.calls.find(c=>c.m==='chat.abort').p.runId,request_id);const job=await runtime.link({target_id,kind:'job',source_id:'job-1',acknowledged:true});await runtime.refresh(job.work_id);assert.equal(runtime.status(job.work_id).remote.can_send,false);await assert.rejects(runtime.action({work_id:job.work_id,revision:runtime.status(job.work_id).revision,action:'send'}),/JOB_READ_ONLY/);assert.ok(!transport.calls.some(c=>['cron.run','cron.update','cron.remove'].includes(c.m)));
});
test('runtime fixture remote HTTP rejects cross-origin and MCP cannot register targets or execute unapproved turns',async t=>{
 const {config,transport}=await setup(t);const server=await startControlCenter(config,{remote:transport});t.after(()=>server.close());const url=server.url+'work/remote/register';const bad=await fetch(url,{method:'POST',headers:{origin:'http://evil.invalid','content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(target)});assert.equal(bad.status,403);const ok=await fetch(url,{method:'POST',headers:{origin:new URL(server.url).origin,'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(target)});assert.equal(ok.status,200);assert.ok(tools.runtime_work_remote_propose);assert.equal(tools.runtime_work_remote_send,undefined);assert.equal(tools.runtime_work_remote_register,undefined);
});

test('runtime fixture remote UI connects, links, reviews and controls owned work on desktop and mobile',async t=>{
 const {config,transport}=await setup(t);const server=await startControlCenter(config,{remote:transport});const browser=await chromium.launch({headless:true}),page=await browser.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
 t.after(async()=>{await browser.close();await server.close();assert.deepEqual(errors,[])});
 await page.addInitScript(()=>localStorage.setItem('office-lang','ko'));await page.goto(server.url+'?import=1');await page.locator('[data-import-route="remote"]').click();await page.locator('#import-remote details summary').click();
 await page.locator('#remote-name').fill(target.name);await page.locator('#remote-host').fill(target.host);await page.locator('#remote-user').fill(target.user);await page.locator('#remote-container').fill(target.container);await page.locator('#remote-register').click();await page.waitForFunction(()=>document.getElementById('remote-target').options.length===1);
 await page.locator('#remote-discover').click();await page.locator('[data-remote-link="0"]').click();await page.locator('#remote-refresh').click();await page.waitForFunction(()=>document.getElementById('remote-send')&&!document.getElementById('remote-send').disabled);
 await page.locator('#remote-instruction').fill('fixture instruction');await page.locator('#remote-send').click();assert.equal(transport.calls.filter(c=>c.m==='chat.send').length,0);await page.locator('#remote-cost').check();await page.locator('#remote-send').click();await page.locator('#remote-stop').waitFor();assert.equal(transport.calls.filter(c=>c.m==='chat.send').length,1);
 await page.locator('#remote-stop').click();await page.locator('#remote-review').waitFor();await page.locator('#remote-refresh').click();await page.waitForFunction(()=>!remoteBusy);await page.locator('#remote-review').click();await page.waitForFunction(()=>!document.getElementById('remote-send').disabled);
 for(const width of [1280,390]){await page.setViewportSize({width,height:850});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('#remote-send').isVisible(),true)}
 await page.locator('#remote-instruction').fill('only this work draft');await page.locator('#remote-cost').check();await page.locator('#back').click();await page.locator('[data-view="all"]').click();await page.locator('[data-work]').first().click();await page.locator('#remote-instruction').waitFor();assert.equal(await page.locator('#remote-instruction').inputValue(),'');assert.equal(await page.locator('#remote-cost').isChecked(),false);assert.equal(transport.calls.filter(c=>c.m==='chat.send').length,1);
});

test('runtime fixture remote refresh is fail closed and cannot overwrite a newer command',async t=>{
 const base=fake();let historyOverride,release,entered;const transport={call:async(t,m,p)=>{if(m==='chat.history'&&historyOverride)return historyOverride();return base.call(t,m,p)}};
 const {runtime}=await setup(t,transport),target_id=runtime.register(target).id,{work_id}=await runtime.link({target_id,kind:'session',source_id:'agent:main:office',acknowledged:true});
 await runtime.refresh(work_id);const original=runtime.status(work_id).remote.snapshot;
 historyOverride=()=>({invalid:true});await runtime.refresh(work_id);assert.equal(runtime.status(work_id).remote.can_send,false);assert.deepEqual(runtime.status(work_id).remote.snapshot,original);
 historyOverride=()=>({messages:[]});await runtime.refresh(work_id);assert.equal(runtime.status(work_id).remote.can_send,false);
 historyOverride=null;await runtime.refresh(work_id);
 const seen=new Promise(r=>entered=r);historyOverride=()=>new Promise(r=>{release=r;entered()});const pending=runtime.refresh(work_id);await seen;
 const request_id=randomUUID();await runtime.action({work_id,revision:runtime.status(work_id).revision,action:'send',request_id,instruction:'one command only',cost_acknowledged:true});release({sessionId:'old-session',messages:[]});await pending;
 assert.equal(runtime.status(work_id).run_status,'running');assert.equal(runtime.status(work_id).remote.snapshot.session_id,'session-owned');assert.equal(base.calls.filter(c=>c.m==='chat.send').length,1);
});

test('runtime fixture remote project isolation, lost acknowledgment reconciliation and unconfirmed stop',async t=>{
 const base=fake(),transport={call:(t,m,p)=>m==='chat.abort'?Promise.resolve({aborted:true,runIds:[randomUUID()]}):base.call(t,m,p)};
 const {runtime,store,config}=await setup(t,transport),target_id=runtime.register(target).id,{work_id}=await runtime.link({target_id,kind:'session',source_id:'agent:main:office',acknowledged:true});await runtime.refresh(work_id);
 const other=new RemoteOffice(store,{...config,project:{...config.project,id:'other-project'}},transport);assert.deepEqual(other.targets(),[]);assert.equal(other.status(work_id),null);await assert.rejects(other.discover({target_id}),/NOT_FOUND/);
 const request_id=randomUUID();base.loseNextAck();await runtime.action({work_id,revision:runtime.status(work_id).revision,action:'send',request_id,instruction:'one command only',cost_acknowledged:true});assert.equal(runtime.status(work_id).remote.turns[0].status,'uncertain');
 await assert.rejects(runtime.action({work_id,revision:runtime.status(work_id).revision,action:'stop'}),/STOP_UNCONFIRMED/);assert.equal(runtime.status(work_id).remote.turns[0].status,'uncertain');
 base.finish();await runtime.refresh(work_id);assert.equal(runtime.status(work_id).remote.turns[0].status,'finished');assert.equal(base.calls.filter(c=>c.m==='chat.send').length,1);
});
