import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {randomUUID} from 'node:crypto';
import vm from 'node:vm';
import {chromium} from 'playwright';
import {workHtml} from '../dist/observability/work-ui.js';

// Deterministic UI/HTTP fixtures only. No real model, public website, private
// process, original bot, delivery connector or schedule is invoked here.
const at='2026-09-29T02:00:00.000Z';
const admissionLabels={queued:'실행 대기',running:'진행 중',retry_wait:'자동 재시도 대기',paused:'일시정지됨',reconciliation_required:'실행 여부 확인 필요',waiting_auth:'로그인 필요',failed:'실행 실패',succeeded:'실행 완료'};

test('runtime unit duplicate intake feedback reports the actual existing state without implying blocked executions resumed',()=>{
  const script=workHtml('dedup-nonce').match(/<script nonce="dedup-nonce">([\s\S]*?)<\/script>/u)[1],start=script.indexOf('function executionAdmissionMessage'),end=script.indexOf('async function readWorkStartResponse');assert.ok(start>=0&&end>start);
  const context={window:{officeText:value=>value},labels:admissionLabels};vm.runInNewContext(script.slice(start,end),context);
  for(const state of ['paused','reconciliation_required','waiting_auth','failed','succeeded',null]){
    context.data={work_id:'fixture-work',definition_status:'ready',admission:{accepted:false,deduplicated:true,state}};
    const text=vm.runInNewContext('admissionMessage(data)',context);assert.match(text,/기존 실행 기록/u);assert.ok(text.includes(admissionLabels[state]||'미관측'));assert.doesNotMatch(text,/이어갑니다|처리하고 있습니다|실행을 접수/u);
  }
  for(const state of ['queued','running','retry_wait']){context.data={definition_status:'ready',admission:{accepted:false,deduplicated:true,state}};assert.equal(vm.runInNewContext('admissionMessage(data)',context),'실행기가 이 업무를 처리하고 있습니다.');}
});

test('runtime unit current-cycle resume keeps duplicate paused and uncertain runs stopped and carries explicit cost consent',async()=>{
  const script=workHtml('dedup-resume').match(/<script nonce="dedup-resume">([\s\S]*?)<\/script>/u)[1],feedback=script.slice(script.indexOf('function executionAdmissionMessage'),script.indexOf('function admissionMessage')),pause=script.slice(script.indexOf('async function pauseWork'),script.indexOf('async function retryDefine'));
  for(const state of ['paused','reconciliation_required','waiting_auth','failed','succeeded','queued','running','retry_wait']){
    const calls=[],messages=[],context={detail:{id:'fixture-work',work_control:{revision:7}},labels:admissionLabels,window:{officeText:value=>value},modalFeedback:'',dispatchReasons:{},executionError:null,Intl,async loadDetail(){},setMessage(value){messages.push(value);},async fetch(path,init){const body=JSON.parse(init.body);calls.push({path,body});return {ok:true,async json(){return {scope:'current_run_request',admission:{accepted:false,deduplicated:true,state}};}};}};
    vm.runInNewContext(feedback+pause,context);assert.equal(await vm.runInNewContext('pauseWork(false,true)',context),true);assert.equal(calls.length,1);assert.equal(calls[0].path,'work/pause');assert.equal(calls[0].body.work_id,'fixture-work');assert.equal(calls[0].body.revision,7);assert.equal(calls[0].body.paused,false);assert.equal(calls[0].body.execute,true);assert.equal(calls[0].body.cost_acknowledged,true);
    if(['queued','running','retry_wait'].includes(state))assert.equal(context.modalFeedback,'업무를 이어갑니다.');else{assert.match(context.modalFeedback,/기존 실행 기록/u);assert.ok(context.modalFeedback.includes(admissionLabels[state]));assert.doesNotMatch(context.modalFeedback,/이어갑니다|처리하고 있습니다|실행을 접수/u);}assert.equal(messages.at(-1),context.modalFeedback);
  }
});
const spec={title:'Source research',desired_outcome:'Read a public source and deliver a summary.',completion_checks:[{id:'summary',result:'Source-grounded summary',evidence:'Observed source and saved report'}],assumptions:[],route:{kind:'pack',pack_family:'research.search'},requested_effect:'read_only',recurrence:{kind:'once',rule:null},questions:[],plan:{revision:1,source:'request',steps:[{id:'collect',goal:'Read the delegated public source.',effect:'read_only',depends_on:[]},{id:'write',goal:'Write the source-grounded summary.',effect:'draft_only',depends_on:['collect']}],source_id:null,source_digest:null,provenance:'user_request'}};
function baseDetail(){return {id:randomUUID(),title:'Source research',goal:spec.desired_outcome,prompt:'Read a public source and write a summary.',work_status:'ready',display_status:'ready',mode:'quick',revision:0,paused:false,spec,questions:[],answers:{},route:spec.route,pack:'research.search',run_id:null,run_status:null,runs:[],client_handoffs:[],swarm:false,coding:false,agent_count:0,verified_steps:0,total_steps:2,progress_percent:null,progress_basis:'이 실행 경로는 단계별 독립 검증 진행률을 제공하지 않음',stages:spec.plan.steps.map(step=>({id:step.id,label:'계획 단계',objective:step.goal,status:'pending',verified:false,executor:null,can_edit:false,attempts:0,owner:null})),control:null,work_control:{can_pause:true,paused:false,revision:0,scope:'future_dispatch'},events:[],completion_verified:false,completion_note:'Run 성공은 Work의 모든 완료조건 충족을 자동으로 뜻하지 않습니다.',execution:{live:false,active_workers:0,basis:'no_active_lease'},execution_action:{executor:'client',can_execute:true,reason:null},supervisor:null,schedule:null,adoption:null,adoption_eligible:false,jev:null,file_activity:null,imported_connection:null,imported_coding:null,coding_attach:null,coding_dialog:null,activity:[],observed_sources:[],current_operation:null,runtime_reload_available:false,runtime_configuration:{state:'idle',reason:null},results:[]};}
function event(d,kind,metadata={},summary=kind){const row={id:'fixture-'+(d.activity.length+1),kind,metadata,summary,created_at:at,source:'fixture'};d.activity.push(row);d.current_operation={...row,observed_at:at};return row;}
async function fixture(t,{mode='ready',language='en',width=1280}={}){
  let closed=false,release;const gate=new Promise(resolve=>release=resolve),streams=new Set(),calls=[],d=baseDetail();
  const board=()=>({format:1,project_id:'ui-fixture',generated_at:at,works:[{id:d.id,title:d.title,full_title:d.title,pack:d.pack,status:d.display_status,work_status:d.work_status,updated_at:at,has_contract:true,run:d.run_id?{kind:'client',id:d.run_id,status:d.display_status}:null,execution:d.execution}],auth_attention_count:0});
  const emit=()=>{for(const stream of streams)stream.write('event: activity\ndata: '+JSON.stringify({...d,work_id:d.id})+'\n\n');};
  const ready=()=>{d.work_status='ready';d.display_status=d.paused?'paused':'ready';d.spec=spec;d.pack='research.search';d.execution.live=false;d.execution_action={executor:'client',can_execute:!d.paused,reason:d.paused?'WORK_PAUSED':null};d.stages=baseDetail().stages;event(d,'definition.finished',{status:'ready'});};
  const admit=()=>{d.run_id??=randomUUID();d.display_status='running';d.execution={live:true,active_workers:1,basis:'office_dispatch_lease'};d.execution_action=null;d.supervisor={run_id:d.run_id,work_id:d.id,revision:d.revision,state:'running',live:true,kind:'client',active_workers:0,current_stage:'collect',can_pause:true,can_resume:false,can_edit:true,reason:null};event(d,'supervisor.queued',{},'업무를 실행 대기열에 넣었습니다. 실행 연결과 저장된 진행 지점을 확인합니다.');event(d,'model.started',{stage_id:'collect'},'Actual fixture model request.');};
  if(mode==='running'){admit();d.stages=[{id:'collect',label:'자료 확인',objective:'Read the delegated source.',status:'running',verified:false,executor:'client',can_edit:false,attempts:1,owner:null}];}
  if(mode==='guided'){d.work_status=d.display_status='awaiting_details';d.questions=[{id:'format',prompt:'Choose the output format.',recommended_id:'summary',options:[{id:'summary',label:'Summary'},{id:'report',label:'Report'}]}];d.execution_action={can_execute:false,reason:'WORK_DEFINITION_REQUIRED'};}
  const server=createServer(async(req,res)=>{
    if(closed){res.writeHead(503);res.end();return;}const url=new URL(req.url,'http://fixture'),path=url.pathname.replace('/office/','');
    const json=(body,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(body));};
    if(req.method==='GET'){
      if(path===''||path==='index.html'){res.writeHead(200,{'content-type':'text/html'});res.end(workHtml('fixture-nonce'));return;}
      if(path==='work/board'){json(board());return;}if(path==='work/detail'){json(d);return;}
      if(path==='settings/status'){json({work_model_data:{editable:true,approved:true}});return;}
      if(path==='work/events'){res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache'});streams.add(res);res.write('event: board\ndata: '+JSON.stringify(board())+'\n\n');if(url.searchParams.has('work_id'))res.write('event: activity\ndata: '+JSON.stringify({...d,work_id:d.id})+'\n\n');res.on('close',()=>streams.delete(res));return;}
      res.writeHead(404);res.end();return;
    }
    let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw||'{}');calls.push({path,body,headers:req.headers});
    if(path==='work/start'){
      assert.equal(body.execute,true);assert.equal(body.cost_acknowledged,true);assert.equal('current_run_only' in body,false);assert.equal(req.headers.accept,'application/x-ndjson');d.work_status=d.display_status='defining';d.spec=null;d.pack=null;d.execution={live:true,active_workers:0,basis:'definition_lease'};d.execution_action={can_execute:false,reason:'WORK_DEFINITION_REQUIRED'};d.stages=[{id:'definition',label:'업무 분석',objective:'지침·완료조건·실행 계획 구성',status:'defining',verified:false,executor:'AI',can_edit:false,attempts:1,owner:null}];event(d,'definition.started',{stage_id:'definition',status:'running'});res.writeHead(200,{'content-type':'application/x-ndjson'});res.write(JSON.stringify({type:'registered',work:{work_id:d.id,status:'defining'}})+'\n');emit();await gate;if(closed){res.end();return;}ready();if(!d.paused)admit();emit();res.end(JSON.stringify({type:'result',result:{work_id:d.id,definition_status:'ready',status:d.display_status,admission:{requested:true,accepted:!d.paused,state:d.display_status,reason:d.paused?'WORK_PAUSED':null}}})+'\n');return;
    }
    if(path==='work/answer'){assert.equal(body.execute,true);assert.equal(body.cost_acknowledged,true);assert.equal('current_run_only' in body,false);d.answers=body.answers;d.questions=[];d.revision++;d.work_control.revision=d.revision;ready();admit();emit();json({work_id:d.id,definition_status:'ready',status:'running',admission:{requested:true,accepted:true,state:'running'}},202);return;}
    if(path==='work/execute'){
      if(mode==='config'){d.execution_action={can_execute:false,reason:'CONFIG_CHANGED'};d.runtime_reload_available=true;event(d,'dispatch.rejected',{status:'rejected',reason:'CONFIG_CHANGED'});emit();json({error:'CONFIG_CHANGED'},409);return;}
      assert.equal(body.cost_acknowledged,true);assert.equal(body.revision,d.revision);admit();emit();json({accepted:true,deduplicated:false,run_id:d.run_id},202);return;
    }
    if(path==='work/reconnect'){assert.equal(body.work_id,d.id);mode='ready';d.runtime_configuration={state:'idle',reason:null};d.execution_action={can_execute:true,executor:'client',reason:null};emit();json({state:'reconnecting'},202);return;}
    if(path==='work/pause'){assert.equal(body.revision,d.work_control.revision);d.paused=body.paused;d.revision++;d.work_control={...d.work_control,paused:d.paused,revision:d.revision};emit();json(d);return;}
    if(path==='work/control'){assert.equal(body.revision,d.revision);d.revision++;d.supervisor.state=body.action==='resume'?'running':'paused';d.supervisor.can_pause=body.action==='resume';d.supervisor.can_resume=body.action!=='resume';d.supervisor.live=body.action==='resume';d.display_status=d.supervisor.state;d.execution.live=d.supervisor.live;event(d,'supervisor.'+body.action,{status:d.supervisor.state},body.action==='edit'?'지침 변경 · '+body.instruction:'실행 중단을 요청했습니다.');emit();json(d.supervisor);return;}
    json({error:'UNSUPPORTED_FIXTURE_ACTION'},400);
  });
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port+'/office/',browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width,height:900}}),errors=[];await context.addInitScript(lang=>localStorage.setItem('office-lang',lang),language);const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
  t.after(async()=>{closed=true;release();await browser.close();for(const stream of streams)stream.end();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));});
  return {d,page,url,calls,errors,release,emit};
}

test('runtime fixture Start work moves to its actual registered detail before definition finishes and admits only the current cycle',{timeout:20000},async t=>{
  const x=await fixture(t);await x.page.goto(x.url);await x.page.locator('#new-work').click();await x.page.locator('#submit-work').waitFor();assert.equal(await x.page.locator('#submit-work').innerText(),'Start work');assert.match(await x.page.locator('.intake-notice').innerText(),/chosen AI allowance/u);
  await x.page.locator('#prompt').fill('Read a public source and write a summary.');await x.page.locator('#submit-work').click();await x.page.locator('.work-head h2').waitFor();assert.ok(x.page.url().includes(x.d.id));assert.equal(x.calls.length,1);assert.equal(x.calls[0].path,'work/start');assert.equal(x.calls[0].body.client,undefined,'an untouched AI choice leaves the owner defaults to the host');await x.page.locator('.work-primary .live-stage[data-busy=true]').waitFor();assert.equal(await x.page.locator('#work-timeline li').count(),1);assert.equal(await x.page.getByRole('progressbar').getAttribute('aria-valuenow'),null);
  await x.page.locator('[data-stage="definition"]').click();await x.page.locator('#stage-dialog[open]').waitFor();assert.equal(await x.page.locator('[data-stage-action="edit"]').isDisabled(),true);assert.equal(await x.page.locator('[data-stage-action="resume"]').isDisabled(),true);assert.match(await x.page.locator('#stage-dialog').innerText(),/analysis request will finish/u);await x.page.keyboard.press('Escape');assert.equal(await x.page.locator('#stage-dialog[open]').count(),0);assert.equal(await x.page.evaluate(()=>document.activeElement.dataset.stage),'definition');
  x.release();await x.page.waitForFunction(()=>document.querySelector('#work-tail-output')?.textContent.includes('supervisor.queued'));assert.equal(x.calls.filter(call=>call.path==='work/execute').length,0);assert.equal(await x.page.locator('#execution-consent').count(),0);assert.match(await x.page.locator('.work-analysis').innerText(),/Planned Pack/u);assert.match(await x.page.locator('.work-analysis').innerText(),/research.search/u);assert.deepEqual(x.errors,[]);
});

test('runtime fixture existing Work has a visible current-cycle action and persistent CONFIG_CHANGED recovery without automatic replay',{timeout:20000},async t=>{
  const x=await fixture(t,{mode:'config',width:390});await x.page.goto(x.url+'?work='+x.d.id);await x.page.locator('#execute-work').waitFor();assert.equal(await x.page.locator('#execute-work').isEnabled(),true);assert.equal(await x.page.locator('#execution-consent').count(),0);await x.page.locator('#execute-work').click();await x.page.locator('.execution-error').waitFor();assert.match(await x.page.locator('.execution-error').innerText(),/Execution tool settings changed/u);assert.equal(x.calls[0].body.current_run_only,true);assert.equal(x.calls[0].body.cost_acknowledged,true);
  event(x.d,'dispatch.rejected',{reason:'CONFIG_CHANGED'});x.emit();await x.page.waitForFunction(()=>document.getElementById('work-timeline')?.textContent.includes('Execution tool settings changed.'));assert.match(await x.page.locator('#work-tail-output').textContent(),/CONFIG_CHANGED/u,'the raw diagnostic is retained in the collapsed technical log');assert.doesNotMatch(await x.page.locator('#work-timeline').innerText(),/CONFIG_CHANGED/u);assert.equal(await x.page.locator('#work-tail-output').isVisible(),false);assert.equal(await x.page.locator('.execution-error').count(),1);assert.equal(await x.page.locator('#reconnect-work').innerText(),'Reapply settings');await x.page.locator('#reconnect-work').click();await x.page.locator('#execute-work').waitFor();assert.equal(await x.page.locator('.execution-error').count(),0);assert.equal(x.calls.filter(call=>call.path==='work/execute').length,1);assert.equal(x.calls.filter(call=>call.path==='work/reconnect').length,1);assert.equal(await x.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.deepEqual(x.errors,[]);
});

test('runtime fixture guided drafts survive real event refresh and the visible choice action carries explicit current-cycle consent',{timeout:20000},async t=>{
  const x=await fixture(t,{mode:'guided'});await x.page.goto(x.url+'?work='+x.d.id);await x.page.locator('[data-question] select').selectOption('custom');await x.page.locator('[data-question] input').fill('A one-page source-grounded report.');event(x.d,'definition.finished',{status:'awaiting_details'});x.emit();await x.page.waitForFunction(()=>document.getElementById('work-tail-output')?.textContent.includes('definition.finished'));assert.equal(await x.page.locator('[data-question] input').inputValue(),'A one-page source-grounded report.');assert.equal(await x.page.evaluate(()=>document.activeElement.tagName),'INPUT');await x.page.locator('#answer').click();await x.page.waitForFunction(()=>document.getElementById('work-tail-output')?.textContent.includes('supervisor.queued'));const request=x.calls.find(call=>call.path==='work/answer');assert.equal(request.body.answers.format,'A one-page source-grounded report.');assert.equal(request.body.cost_acknowledged,true);assert.equal('current_run_only' in request.body,false);assert.deepEqual(x.errors,[]);
});

test('runtime fixture failed or restored settings show their real recovery outcome without replay or silent controls',{timeout:20000},async t=>{
  for(const state of ['failed','restored']){const x=await fixture(t);x.d.runtime_configuration={state,reason:'CONTROL_CENTER_RELOAD_FAILED'};x.d.runtime_reload_available=true;await x.page.goto(x.url+'?work='+x.d.id);await x.page.locator('.execution-error').waitFor();assert.match(await x.page.locator('.execution-error').innerText(),state==='failed'?/Execution is blocked/u:/previous state was restored/u);if(state==='failed'){assert.equal(await x.page.locator('#execute-work').count(),0);assert.equal(await x.page.locator('#reconnect-work').count(),0);}else assert.equal(await x.page.locator('#reconnect-work').count(),1);assert.equal(x.calls.length,0);assert.doesNotMatch(await x.page.locator('.execution-error').innerText(),/[가-힣]/u);assert.deepEqual(x.errors,[]);}
});

test('runtime fixture timeline never promotes a model claim to successful execution and keeps host verification human-readable',{timeout:20000},async t=>{
  const x=await fixture(t,{mode:'running'});event(x.d,'received',{},'received');event(x.d,'defined',{},'defined');event(x.d,'model.result',{},'The source result is verified and succeeded.');event(x.d,'supervisor.result',{status:'awaiting_review'},'awaiting_review · The result succeeded and was verified.');event(x.d,'supervisor.verification.audit',{},JSON.stringify({status:'accepted',code:'WORK_COMPLETION_VERIFIED',input_sha256:'a'.repeat(64),checks:[]}));await x.page.goto(x.url+'?work='+x.d.id);await x.page.locator('#work-timeline').waitFor();const text=await x.page.locator('#work-timeline').innerText();assert.match(text,/Request saved/u);assert.match(text,/Plan saved/u);assert.match(text,/Work execution result/u);assert.match(text,/Completion criteria met/u);assert.doesNotMatch(text,/Work execution succeeded|input_sha256/u);assert.equal(await x.page.locator('#work-timeline .timeline-success').count(),0);const summary=x.page.locator('#work-timeline details').filter({has:x.page.getByText('AI action summary',{exact:true})}).last();await summary.locator('summary').click();assert.match(await summary.innerText(),/source result is verified and succeeded/u);assert.deepEqual(x.errors,[]);
});

for(const [language,width] of [['en',1280],['en',390],['ko',1280],['ko',390]])test(`runtime fixture ${language}/${width} stage modal preserves draft, traps focus and shows only observed source/worker evidence`,{timeout:20000},async t=>{
  const x=await fixture(t,{mode:'running',language,width});x.d.supervisor.kind='swarm';x.d.supervisor.active_workers=2;x.d.swarm=true;event(x.d,'source.observed',{stage_id:'collect',worker_id:'source-one',tool_name:'office_browser_read',engine:'playwright',status:'succeeded',source:{url:'https://example.org/observed',title:'Observed fixture source',observed_at:at}});x.d.observed_sources=[{url:'https://example.org/observed',title:'Observed fixture source',observed_at:at,tool:'office_browser_read',engine:'playwright'}];event(x.d,'tool.result',{stage_id:'collect',worker_id:'source-two',tool_name:'office_browser_read',status:'failed',reason:'SOURCE_NOT_AVAILABLE'});await x.page.goto(x.url+'?work='+x.d.id);await x.page.locator('#work-timeline').waitFor();assert.match(await x.page.locator('#work-worker-summary').innerText(),/2/u);assert.equal(await x.page.locator('#work-timeline .timeline-failure').count(),1);assert.equal(await x.page.locator('#work-timeline a[href="https://example.org/observed"]').count(),1);assert.equal(await x.page.locator('#work-timeline a[href*="not-observed"]').count(),0);assert.equal(await x.page.locator('#supervisor-instruction').count(),0);
  await x.page.locator('[data-stage="collect"]').focus();await x.page.keyboard.press('Enter');await x.page.locator('#stage-dialog[open]').waitFor();assert.equal(await x.page.locator('[data-stage-action="resume"]').isDisabled(),true);assert.equal(await x.page.locator('[data-stage-action="edit"]').isDisabled(),true);await x.page.locator('#stage-instruction').fill('Deliver a summary instead of cards.');event(x.d,'model.result',{stage_id:'collect',worker_id:'source-one'});x.emit();await x.page.waitForFunction(()=>document.getElementById('work-tail-output')?.textContent.includes('model.result'));assert.equal(await x.page.locator('#stage-instruction').inputValue(),'Deliver a summary instead of cards.');assert.equal(await x.page.evaluate(()=>document.activeElement.id),'stage-instruction');
  await x.page.keyboard.press('Tab');assert.equal(await x.page.evaluate(()=>Boolean(document.activeElement.closest('#stage-dialog'))),true);await x.page.keyboard.press('Escape');assert.equal(await x.page.locator('#stage-dialog[open]').count(),0);assert.equal(await x.page.evaluate(()=>document.activeElement.dataset.stage),'collect');await x.page.locator('[data-stage="collect"]').click();assert.equal(await x.page.locator('#stage-instruction').inputValue(),'Deliver a summary instead of cards.');await x.page.locator('[data-stage-action="edit"]').click();await x.page.waitForFunction(()=>document.querySelector('#stage-state')?.textContent.includes('Paused')||document.querySelector('#stage-state')?.textContent.includes('일시정지'));assert.equal(x.calls.at(-1).body.stage_id,'collect');assert.equal(x.calls.at(-1).body.revision,0);assert.equal(x.calls.at(-1).body.instruction,'Deliver a summary instead of cards.');await x.page.locator('[data-stage-action="resume"]').click();await x.page.waitForFunction(()=>document.querySelector('[data-stage-action="resume"]')?.disabled===true);assert.equal(x.calls.at(-1).body.revision,1);assert.equal(x.calls.at(-1).body.action,'resume');
  if(language==='en'){assert.doesNotMatch(await x.page.locator('#stage-dialog').innerText(),/[가-힣]/u);assert.doesNotMatch(await x.page.locator('.work-analysis').innerText(),/[가-힣]/u);assert.doesNotMatch(await x.page.locator('.work-tail').innerText(),/[가-힣]/u);}assert.equal(await x.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.deepEqual(x.errors,[]);
  await x.page.locator('#stage-close').click();await x.page.evaluate(()=>{Object.defineProperty(document,'hidden',{get:()=>true,configurable:true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await x.page.locator('#work-tail-state').innerText(),language==='en'?'Inactive tab · updates paused':'탭 비활성 · 갱신 대기');await x.page.evaluate(()=>{Object.defineProperty(document,'hidden',{get:()=>false,configurable:true});document.dispatchEvent(new Event('visibilitychange'));});await x.page.waitForFunction(()=>document.getElementById('work-tail-state').textContent==='Live'||document.getElementById('work-tail-state').textContent==='실시간 연결됨');
});

for(const [language,width] of [['en',1280],['en',390],['ko',1280],['ko',390]])test(`runtime fixture ${language}/${width} business stages keep source attempts distinct from observed sites and pending verification`,{timeout:20000},async t=>{
  const x=await fixture(t,{mode:'running',language,width}),attempt={id:'attempt',kind:'source.started',summary:'Source read attempted',created_at:at,metadata:{target_url:'https://example.org/not-observed',worker_id:'source-one',executor:'playwright'}},observed={id:'observed',kind:'source.observed',summary:'Source observed',created_at:at,metadata:{worker_id:'source-one',engine:'playwright',source:{url:'https://example.org/observed',title:'Observed primary source',observed_at:at}}};
  x.d.supervisor.state='awaiting_review';x.d.supervisor.live=false;x.d.display_status='awaiting_review';x.d.execution.live=false;x.d.progress_percent=50;x.d.executed_steps=1;x.d.verified_steps=0;
  x.d.stages=[{id:'collect',label:'Collect the public source',objective:'One primary source is observed and recorded.',observable_outcome:'One primary source is observed and recorded.',status:'execution_completed',execution_reported:true,verified:false,executor:'playwright',can_edit:false,attempts:1,owner:null,semantic:true,activities:[attempt,observed],block_reason:null},{id:'write',label:'Write the result',objective:'A cited summary is saved.',observable_outcome:'A cited summary is saved.',status:'pending',execution_reported:false,verified:false,executor:null,can_edit:false,attempts:0,owner:null,semantic:true,activities:[],block_reason:null}];
  await x.page.goto(x.url+'?work='+x.d.id);await x.page.locator('.stage-group').first().waitFor();
  assert.equal(await x.page.locator('.stage-group').count(),2);assert.equal(await x.page.getByRole('progressbar').getAttribute('aria-valuenow'),'50');assert.equal(await x.page.locator('[data-stage="office_browser_read"]').count(),0);
  assert.equal(await x.page.locator('.stage-activities a[href="https://example.org/observed"]').count(),1);assert.equal(await x.page.locator('.stage-activities a[href*="not-observed"]').count(),0);assert.match(await x.page.locator('.stage-activities').first().innerText(),language==='en'?/Attempted site/u:/조회 시도/u);
  const first=x.page.locator('[data-stage="collect"]');assert.match(await first.innerText(),language==='en'?/Executed · awaiting confirmation/u:/실행 완료 · 검증 대기/u);await first.click();await x.page.locator('#stage-dialog[open]').waitFor();assert.match(await x.page.locator('#stage-state').innerText(),language==='en'?/awaiting confirmation/u:/검증 대기/u);assert.equal(await x.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.deepEqual(x.errors,[]);
});

for(const [language,width] of [['en',1280],['ko',390]])test(`runtime fixture ${language}/${width} verification timeout explains preserved results`,{timeout:20000},async t=>{
  const x=await fixture(t,{mode:'running',language,width});
  event(x.d,'supervisor.verification.audit',{},JSON.stringify({status:'unavailable',code:'STRUCTURED_MODEL_TIMEOUT'}));
  await x.page.goto(x.url+'?work='+x.d.id);await x.page.locator('#work-timeline').waitFor();
  assert.match(await x.page.locator('#work-timeline').innerText(),language==='en'?/Completion verification timed out\. Existing results are preserved\./u:/완료 검증 AI의 응답 시간이 초과됐어요\. 기존 결과는 보존돼요\./u);
  assert.equal(await x.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.deepEqual(x.errors,[]);
});

for(const [language,width] of [['en',1280],['ko',390]])test(`runtime fixture ${language}/${width} redacted source placeholders are never clickable URLs`,{timeout:20000},async t=>{
  const x=await fixture(t,{mode:'running',language,width}),safe='https://example.org/safe-article',redacted='https://example.org/news/:redacted',encoded='https://example.org/news/%3Aredacted';
  x.d.observed_sources=[{url:safe,title:'Public article',observed_at:at,tool:'office_browser_read',engine:'playwright'},{url:redacted,title:'Observed source with a private-looking path',observed_at:at,tool:'office_browser_read',engine:'playwright'}];
  const activities=[event(x.d,'source.observed',{source:{url:redacted,title:'Observed source with a private-looking path',observed_at:at}},'Observed source'),event(x.d,'source.observed',{source:{url:encoded,title:'Encoded redaction marker',observed_at:at}},'Observed source')];
  x.d.stages=[{id:'collect',label:'Collect source',objective:'Observe a public source.',observable_outcome:'Observe a public source.',status:'result_observed',execution_reported:false,verified:false,executor:'playwright',can_edit:false,attempts:1,owner:null,semantic:true,activities,block_reason:null}];
  await x.page.goto(x.url+'?work='+x.d.id);await x.page.locator('.source-observations li').first().waitFor();
  assert.equal(await x.page.locator('.source-observations a[href="'+safe+'"]').count(),1);assert.equal(await x.page.locator('a[href*="redacted"],a[href*="REDACTED"]').count(),0);
  assert.equal(await x.page.locator('.source-observations li').last().locator('a').count(),0);assert.match(await x.page.locator('.source-observations li').last().innerText(),/Observed source with a private-looking path/u);assert.match(await x.page.locator('.source-observations li').last().innerText(),/https:\/\/example\.org/u);assert.doesNotMatch(await x.page.locator('.source-observations').innerText(),/:redacted|%3Aredacted/iu);
  assert.equal(await x.page.locator('.stage-activities a').count(),0);assert.equal(await x.page.locator('#work-timeline a').count(),0);assert.equal(await x.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.deepEqual(x.errors,[]);
});
