export const browserSetupHtml=`<div id="browser-setup"><div class="runtime-line"><h3 class="connection-title">브라우저</h3><button id="browser-setup-refresh" class="small-action" aria-label="브라우저 상태 다시 확인">지금 확인</button></div><details class="settings-help" id="browser-help" data-section-help><summary>설명 보기</summary><p class="muted">기본 브라우저는 백그라운드에서 돌아요. 내 브라우저(Aside)를 연결하면 로그인 상태를 그대로 쓰고, 사이트가 막을 때 자동으로 넘어가요.</p><div id="browser-guides"></div></details><div id="browser-default" class="browser-list"></div><details id="browser-alternatives"><summary>내 브라우저 연결 (Aside · BrowserOS Neo) · 선택</summary><div id="browser-optional" class="browser-list"></div></details><p id="browser-setup-notice" class="muted keep" role="status" hidden></p><div class="runtime-line site-login-line"><div><h3 class="connection-title">사이트 로그인</h3><p class="muted keep">로그인이 필요한 사이트를 미리 등록해 두면 업무가 중간에 멈추지 않아요.</p></div><a id="browser-site-logins" class="action-link" href="connections">사이트 로그인 관리</a></div></div>`;

export const browserSetupScript=`
let browserSetupState;
async function refreshBrowserSetup(){renderBrowserSetup(await request('settings/browsers'));}
function browserStage(row){return row.health==='ready'?(row.engine==='playwright'||row.registered?'connected':'permission'):row.health==='unchecked'?'unchecked':row.reason==='cli_missing'?'missing_cli':'disconnected';}
const browserStageLabels={connected:'연결됨',permission:'사용 허용 필요',unchecked:'확인 전',missing_cli:'CLI 설치 필요',disconnected:'연결 필요'};
function browserGuidance(row){const stage=browserStage(row);return stage==='permission'?'이 브라우저와 로그인 상태를 읽기 업무에 쓰는 데 동의하면 연결하세요.':stage==='connected'?(row.engine==='playwright'?'전용 브라우저가 준비되었습니다.':'이 브라우저를 조회 업무에 사용할 수 있습니다.'):stage==='missing_cli'?'Aside가 이미 설치되어 있다면 Settings → Developers에서 CLI를 설치하세요.':stage==='disconnected'?'앱을 실행하고 로컬 연결을 켠 뒤 연결 버튼을 누르세요.':'설치·실행 상태를 먼저 확인하세요.';}
const browserSetupErrors={BROWSER_SETUP_CHECK_REQUIRED:'연결 확인이 만료됐습니다. 다시 확인한 뒤 연결하세요.',BROWSER_SETUP_CONFLICT:'설정이 변경됐습니다. 다시 확인한 뒤 연결하세요.',BROWSER_SETUP_CONSENT_REQUIRED:'화면·프로필 사용을 허용해야 연결할 수 있습니다.',BROWSER_SETUP_TARGET_CONFLICT:'기존 브라우저 설정과 충돌합니다. 설정을 확인해 주세요.',BROWSER_SETUP_UNSAFE_CONFIG:'설정 파일을 안전하게 읽지 못했습니다. 기존 설정은 유지됩니다.',BROWSER_SETUP_INSTALL_FAILED:'브라우저 설치를 완료하지 못했습니다. 다시 시도해 주세요.'};
function browserFeedback(engine,message){const target=document.querySelector('[data-browser="'+engine+'"] .browser-feedback');if(target){target.textContent=message;target.hidden=!message;}notice('');}
function browserOperation(row,path,body,progress){return action(async()=>{browserFeedback(row.engine,progress);try{const result=await request(path,body);renderBrowserSetup(result);const updated=result.rows.find(item=>item.engine===row.engine),stage=browserStage(updated);browserFeedback(row.engine,stage==='connected'?'연결됐습니다.':stage==='permission'?'조회 업무에 화면·프로필 사용을 허용합니다.':stage==='missing_cli'?'CLI 설치 후 다시 확인하세요.':'연결하지 못했습니다. 설명 보기를 확인하세요.');}catch(error){if(['BROWSER_SETUP_CHECK_REQUIRED','BROWSER_SETUP_CONFLICT'].includes(error.message)){browserSetupState={...browserSetupState,rows:browserSetupState.rows.map(item=>item.engine===row.engine?{...item,health:'unchecked',reason:'unchecked'}:item)};}renderBrowserSetup(browserSetupState);browserFeedback(row.engine,browserSetupErrors[error.message]||'요청을 완료하지 못했습니다. 앱의 실행·연결 상태를 확인하고 다시 시도하세요.');}});}
function renderBrowserSetup(data){
  browserSetupState=data;$('browser-default').replaceChildren();$('browser-optional').replaceChildren();$('browser-guides').replaceChildren();
  for(const row of data.rows){
    const stage=browserStage(row),card=document.createElement('div');card.className='client';card.dataset.browser=row.engine;card.dataset.setupState=stage;
    const head=document.createElement('div');head.className='crow';const title=document.createElement('strong');title.textContent=row.engine==='playwright'?'기본 브라우저 (Playwright)':row.label;
    const badge=document.createElement('span');badge.className='badge '+(stage==='connected'?'ok':['permission','missing_cli','disconnected'].includes(stage)?'warn':'idle');badge.textContent=row.engine==='playwright'&&stage==='connected'?'준비됨':stage==='unchecked'&&row.registered?'연결 확인 필요':browserStageLabels[stage];head.append(title,badge);card.append(head);
    const actions=document.createElement('div');actions.className='cact';
    const check=document.createElement('button');check.textContent=stage==='connected'?(row.engine==='playwright'?'준비됨':'연결됨'):stage==='disconnected'?'연결':stage==='missing_cli'?'다시 확인':'연결 확인';check.setAttribute('aria-label',row.label+(stage==='connected'?' 연결됨':' 연결 확인'));check.onclick=()=>browserOperation(row,'settings/browsers/check',{engine:row.engine},row.label+' 연결 확인 중…');
    if(stage==='connected'){check.disabled=true;check.dataset.setupComplete='true';actions.append(check);}
    else if(stage==='permission'){const register=document.createElement('button');register.textContent='허용하고 연결';register.className='primary';register.setAttribute('aria-label',row.label+' 연결 등록');register.onclick=()=>browserOperation(row,'settings/browsers/register',{engine:row.engine,revision:browserSetupState.revision,consent:true},row.label+' 연결 중…');actions.append(register);}
    else if(row.engine==='playwright'&&stage==='disconnected'){const install=document.createElement('button');install.textContent='설치';install.setAttribute('aria-label','전용 브라우저 다운로드');install.onclick=()=>browserOperation(row,'settings/browsers/install',{engine:'playwright'},'Chromium 다운로드 중…');actions.append(install);}
    else{if(stage==='missing_cli'&&row.download){const link=document.createElement('a');link.href=row.download;link.target='_blank';link.rel='noreferrer';link.className='action-link';link.textContent='다운로드';link.setAttribute('aria-label',row.label+' 다운로드');actions.append(link);}actions.append(check);}
    head.append(actions);
    const feedback=document.createElement('p');feedback.className='browser-feedback muted keep';feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');feedback.hidden=stage!=='permission';feedback.textContent=stage==='permission'?'조회 업무에 화면·프로필 사용을 허용합니다.':'';card.append(feedback);
    const guide=document.createElement('section');guide.className='browser-guide';guide.dataset.guide=row.engine;const heading=document.createElement('h4');heading.textContent=row.label;guide.append(heading);for(const text of [browserGuidance(row),row.setup,row.auth]){const p=document.createElement('p');p.className='muted';p.textContent=text;guide.append(p);}if(row.connection||row.download){const link=document.createElement('a');link.href=row.connection||row.download;link.target='_blank';link.rel='noreferrer';link.textContent='설정 안내';guide.append(link);}if(row.download&&stage!=='missing_cli'){const link=document.createElement('a');link.href=row.download;link.target='_blank';link.rel='noreferrer';link.textContent='앱이 없으면 다운로드';guide.append(link);}$('browser-guides').append(guide);
    $(row.engine==='playwright'?'browser-default':'browser-optional').append(card);
  }
  $('browser-setup-notice').hidden=!data.restart_required;$('browser-setup-notice').textContent=data.restart_required?'설정이 바뀌었습니다. MCP를 다시 연결하세요.':'';
}
$('browser-setup-refresh').onclick=()=>action(refreshBrowserSetup);
`;
