/** Result delivery controls shared by onboarding and the Work page. Secrets are write only. */
export const deliveryCss=`
.delivery-targets{display:grid;gap:8px;margin:12px 0}.delivery-target{border:1px solid var(--line);border-radius:8px;padding:10px 12px;min-width:0}.delivery-target header{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}.delivery-target header strong{font-size:13px;margin-right:auto}.delivery-target .icon-btn{border:1px solid var(--line);background:transparent;border-radius:6px;width:26px;height:26px;padding:0;line-height:1;cursor:pointer;color:var(--dim)}.delivery-target .icon-btn:hover{color:var(--text);border-color:var(--text)}.delivery-hint{margin:8px 0 0;font-size:12px}.delivery-target .badge{font-size:11px}.delivery-target label{margin:8px 0 4px}.delivery-target input{width:100%}.delivery-target .row{margin-top:4px}.delivery-state{display:flex;flex-wrap:wrap;gap:6px 12px;align-items:center;margin:8px 0;font:12.5px var(--mono);color:var(--dim)}.delivery-state .badge.ok{color:var(--ok);border-color:var(--ok)}.delivery-edit{width:auto}.delivery-choice{display:flex;align-items:flex-start;gap:7px;margin:7px 0;color:var(--text);font:12.5px/1.45 var(--sans);overflow-wrap:anywhere}.delivery-choice input{width:auto;flex:none;margin:2px 0 0}.delivery-choice span{min-width:0}.delivery-add{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.delivery-add button{width:auto}.delivery-empty{font:12px/1.5 var(--sans);color:var(--dim);margin:6px 0}.delivery-choice-list{display:flex;gap:8px 16px;align-items:center;flex-wrap:wrap}.delivery-choice-list .delivery-choice{margin:0}.delivery-choice-list a,.delivery-policy a{color:var(--code);text-decoration:underline;text-underline-offset:3px}.delivery-policy{margin:0;color:var(--dim);font:12px/1.5 var(--sans)}.delivery-step{border-top:1px solid var(--line);padding-top:14px;margin-top:2px}.delivery-step .step{padding-bottom:4px}.delivery-dialog{width:min(480px,calc(100vw - 28px));max-height:calc(100dvh - 32px);overflow:auto;margin:auto;border:1px solid var(--line2);border-radius:var(--r);padding:18px;background:var(--panel);color:var(--text)}.delivery-dialog::backdrop{background:#0009}.delivery-dialog header{display:flex;align-items:center;justify-content:space-between;gap:8px}.delivery-dialog .actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.delivery-dialog [role=status]{min-height:20px;color:var(--human);font-size:12px}.delivery-state-list{margin:12px 0;padding-left:20px;font:12px/1.5 var(--sans);color:var(--dim)}
form.intake>label:first-child{position:static;left:auto;color:var(--text);font-weight:600}.intake-delivery{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:2px 14px;margin-top:8px}.intake-delivery>label{margin:0 0 3px;color:var(--text);font-weight:500}.intake-delivery textarea{grid-column:1;grid-row:2;min-height:66px}.intake-delivery>.delivery-choice-list{grid-column:2;grid-row:2;align-content:start;align-items:start}
.result-deliveries p:has(.delivery-reason){flex-wrap:wrap}.result-deliveries .delivery-reason{flex-basis:100%;font:11.5px/1.5 var(--sans);color:var(--human)}
@media(max-width:560px){.delivery-choice-list{display:grid;gap:8px}.delivery-target .row{grid-template-columns:1fr}.delivery-dialog .actions{flex-wrap:wrap}.intake-delivery{grid-template-columns:1fr}.intake-delivery textarea,.intake-delivery>.delivery-choice-list{grid-column:1;grid-row:auto}}
`;

export const deliverySettingsHtml=`<section class="panel" id="step-4" hidden><h2>결과 전달</h2><p class="muted">결과는 항상 피드에서 볼 수 있어요. 메신저로도 받으려면 추가하세요.</p><div id="delivery-targets" class="delivery-targets"></div><div class="delivery-add" role="group" aria-label="전달 대상 추가"><button type="button" data-add-delivery="telegram">Telegram 추가</button><button type="button" data-add-delivery="slack">Slack 추가</button><button type="button" data-add-delivery="discord">Discord 추가</button></div><h3 class="connection-title">새 업무의 기본 전달 대상</h3><div id="delivery-defaults" class="delivery-choice-list"></div><p class="delivery-policy"><span>연결 정보는 저장 후 실제 전송 때 확인됩니다.</span> <span>업무 상세에서 결과 받을 곳을 바꿀 수 있어요.</span> <a href="./">업무 보기</a></p><div class="actions"><button type="button" id="save-delivery">저장</button><button type="button" id="finish-delivery" class="primary">완료</button></div></section>`;

export const deliverySettingsScript=`
let deliverySettingsState=null,deliveryTargetDrafts=[];
const deliveryPlatformName={telegram:'Telegram',slack:'Slack',discord:'Discord'};
function deliveryEscape(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function deliverySettingsText(ko,en){return window.officeCopy?.(ko,en)??(document.documentElement.lang==='en'?en:ko);}
const deliveryHints={telegram:['@BotFather에서 봇을 만들어 토큰을 받고, 봇에게 메시지를 보낸 뒤 @userinfobot으로 채팅 ID를 확인하세요.','Create a bot with @BotFather for the token; message the bot, then get your chat ID from @userinfobot.','https://core.telegram.org/bots#how-do-i-create-a-bot'],slack:['Slack 앱 설정 → Incoming Webhooks에서 채널용 Webhook URL을 발급받아 붙여 넣으세요.','In your Slack app settings open Incoming Webhooks and create a webhook URL for the channel.','https://api.slack.com/messaging/webhooks'],discord:['Discord 채널 설정 → 연동 → 웹후크 → 새 웹후크 → URL 복사.','In the Discord channel: Settings → Integrations → Webhooks → New Webhook → Copy URL.','https://support.discord.com/hc/articles/228383668']};
// A saved destination reads as saved: its name, a detail to recognise it, and whether a result has gone out with it.
// The fields open only to change it (secrets stay write-only); a new destination opens with its fields.
function deliveryWhen(at){const d=new Date(at);return isNaN(d)?'':d.toLocaleString(document.documentElement.lang==='en'?'en-US':'ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});}
function deliveryTargetCard(target){const platform=deliveryPlatformName[target.platform]||target.platform,hint=deliveryHints[target.platform],remove='<button type="button" class="icon-btn" data-remove-delivery="'+deliveryEscape(target.id)+'" aria-label="'+deliverySettingsText(platform+' 삭제',platform+' remove')+'" title="'+deliverySettingsText('삭제','Remove')+'">✕</button>';
 if(target.configured&&!target.editing){const sent=target.connection==='delivered'&&target.last_delivered_at;
  return '<article class="delivery-target saved" data-delivery-target="'+deliveryEscape(target.id)+'"><header><strong>'+deliveryEscape(platform)+' · <span data-i18n-skip>'+deliveryEscape(target.label||platform)+'</span></strong>'+remove+'</header>'
   +'<p class="delivery-state"><span class="badge '+(sent?'ok':'idle')+'">'+(sent?deliverySettingsText('연결됨','Connected'):deliverySettingsText('등록됨 · 아직 보낸 적 없음','Saved · nothing sent yet'))+'</span>'+(sent?'<span>'+deliverySettingsText('마지막 전송 ','Last sent ')+deliveryEscape(deliveryWhen(target.last_delivered_at))+'</span>':'')+(target.detail?'<span data-i18n-skip>'+deliveryEscape(target.detail)+'</span>':'')+'</p>'
   +'<button type="button" class="delivery-edit" data-edit-delivery="'+deliveryEscape(target.id)+'">'+deliverySettingsText('수정','Edit')+'</button></article>';}
 return '<article class="delivery-target" data-delivery-target="'+deliveryEscape(target.id)+'"><header><strong>'+deliveryEscape(platform)+'</strong><span class="badge '+(target.configured?'idle':'warn')+'">'+(target.configured?deliverySettingsText('수정 중 · 비워 둔 칸은 그대로','Editing · blank fields stay as they are'):deliverySettingsText('연결 정보 필요','Connection details needed'))+'</span>'+remove+'</header><label>'+deliverySettingsText('받을 곳 이름','Destination name')+'<input data-target-label maxlength="80" value="'+deliveryEscape(target.configured?target.label||platform:'')+'" placeholder="'+deliverySettingsText('예: 내 텔레그램','e.g. My Telegram')+'"></label>'+(target.platform==='telegram'?'<div class="row"><label>Bot token<input data-target-token type="password" autocomplete="new-password" placeholder="'+(target.configured?deliverySettingsText('저장됨 · 바꿀 때만 입력','Saved · enter only to change'):deliverySettingsText('봇 토큰','Bot token'))+'"></label><label>Chat ID<input data-target-chat maxlength="100" placeholder="'+(target.configured&&target.detail?deliveryEscape(target.detail)+deliverySettingsText(' · 바꿀 때만 입력',' · enter only to change'):deliverySettingsText('채팅 ID','Chat ID'))+'"></label></div>':'<label>Webhook URL<input data-target-webhook type="password" autocomplete="new-password" placeholder="'+(target.configured?deliverySettingsText('저장됨 · 바꿀 때만 입력','Saved · enter only to change'):deliverySettingsText('Webhook URL','Webhook URL'))+'"></label>')+(hint?'<p class="muted keep delivery-hint">'+deliverySettingsText(hint[0],hint[1])+' <a href="'+hint[2]+'" target="_blank" rel="noreferrer">'+deliverySettingsText('안내','Guide')+'</a></p>':'')+'</article>';}
function removeDeliveryTarget(id){captureDeliveryDrafts();deliveryTargetDrafts=deliveryTargetDrafts.filter(target=>target.id!==id);if(deliverySettingsState)deliverySettingsState={...deliverySettingsState,default_target_ids:(deliverySettingsState.default_target_ids||['app']).filter(value=>value!==id)};renderDeliverySettings();notice(deliverySettingsText('저장을 누르면 삭제가 반영돼요.','Press Save to apply the removal.'));}
function renderDeliverySettings(){const host=$('delivery-targets'),defaults=$('delivery-defaults');if(!host||!defaults)return;host.innerHTML=deliveryTargetDrafts.length?deliveryTargetDrafts.map(deliveryTargetCard).join(''):'<p class="delivery-empty">'+deliverySettingsText('연결된 메신저가 없습니다. 필요한 플랫폼만 추가하세요.','No messenger is connected. Add only the platforms you need.')+'</p>';const selected=new Set(deliverySettingsState?.default_target_ids||['app']);defaults.innerHTML='<label class="delivery-choice"><input type="checkbox" value="app" data-delivery-default '+(selected.has('app')?'checked':'')+'><span>'+deliverySettingsText('피드','Feed')+'</span></label>'+deliveryTargetDrafts.map(target=>'<label class="delivery-choice"><input type="checkbox" value="'+deliveryEscape(target.id)+'" data-delivery-default '+(selected.has(target.id)?'checked':'')+'><span>'+deliveryEscape(!target.label||target.label===deliveryPlatformName[target.platform]?deliveryPlatformName[target.platform]:deliveryPlatformName[target.platform]+' · '+target.label)+'</span></label>').join('');host.querySelectorAll('[data-remove-delivery]').forEach(button=>button.onclick=()=>removeDeliveryTarget(button.dataset.removeDelivery));host.querySelectorAll('[data-edit-delivery]').forEach(button=>button.onclick=()=>{captureDeliveryDrafts();const draft=deliveryTargetDrafts.find(target=>target.id===button.dataset.editDelivery);if(draft)draft.editing=true;renderDeliverySettings();host.querySelector('[data-delivery-target="'+CSS.escape(button.dataset.editDelivery)+'"] [data-target-label]')?.focus();});}
async function loadDeliverySettings(){const data=await request('delivery/status');deliverySettingsState=data;deliveryTargetDrafts=(data.targets||[]).map(target=>({...target}));renderDeliverySettings();}
function captureDeliveryDrafts(){for(const card of document.querySelectorAll('[data-delivery-target]')){const draft=deliveryTargetDrafts.find(target=>target.id===card.dataset.deliveryTarget);if(!draft)continue;const labelInput=card.querySelector('[data-target-label]');if(labelInput)draft.label=labelInput.value.trim()||deliveryPlatformName[draft.platform];const token=card.querySelector('[data-target-token]')?.value.trim();const chat=card.querySelector('[data-target-chat]')?.value.trim();const webhook=card.querySelector('[data-target-webhook]')?.value.trim();if(token)draft.telegram_bot_token=token;if(chat)draft.telegram_chat_id=chat;if(webhook)draft.webhook_url=webhook;}}
async function saveDeliverySettings(){if(!deliverySettingsState)await loadDeliverySettings();captureDeliveryDrafts();const targetIds=Array.from(document.querySelectorAll('[data-delivery-default]:checked'),node=>node.value);if(!targetIds.length)throw Error(deliverySettingsText('기본 전달 대상을 하나 이상 선택하세요.','Select at least one default destination.'));const targets=deliveryTargetDrafts.map(({id,platform,label,telegram_bot_token,telegram_chat_id,webhook_url})=>({id,platform,label,...(telegram_bot_token?{telegram_bot_token}:{}),...(telegram_chat_id?{telegram_chat_id}:{}),...(webhook_url?{webhook_url}:{})}));const updated=await request('delivery/settings',{revision:deliverySettingsState.revision,targets,default_target_ids:targetIds});deliverySettingsState=updated;deliveryTargetDrafts=(updated.targets||[]).map(target=>({...target}));renderDeliverySettings();notice(deliverySettingsText('전달 설정을 저장했습니다. 실제 전송은 결과가 생길 때 확인됩니다.','Delivery settings saved. Actual delivery is checked when a result is available.'));}
document.querySelectorAll('[data-add-delivery]').forEach(button=>button.addEventListener('click',()=>{if(deliveryTargetDrafts.length>=20){notice(deliverySettingsText('전달 대상은 최대 20개까지 저장할 수 있습니다.','You can save up to 20 destinations.'));return;}captureDeliveryDrafts();deliverySettingsState.default_target_ids=Array.from(document.querySelectorAll('[data-delivery-default]:checked'),node=>node.value);const platform=button.dataset.addDelivery;deliveryTargetDrafts.push({id:crypto.randomUUID(),platform,label:deliveryPlatformName[platform],configured:false});renderDeliverySettings();const card=$('delivery-targets').lastElementChild;card?.querySelector('[data-target-label]')?.focus();}));
$('save-delivery').onclick=()=>action(saveDeliverySettings);
$('finish-delivery').onclick=()=>action(async()=>{await saveDeliverySettings();location.href='./';});
`;

export const deliveryWorkScript=String.raw`
let deliveryCatalog=null,deliverySelection=null,deliveryModalFocus=null,deliveryModalBusy=false;
const deliveryNames={telegram:'Telegram',slack:'Slack',discord:'Discord',app:'피드'};
intake.querySelector('label[for="prompt"]').textContent=deliveryText('작업 지침','Work instructions');
const deliveryIntake=document.createElement('div');deliveryIntake.className='intake-delivery';deliveryIntake.innerHTML='<label for="completion-condition">'+deliveryText('완료 조건','Completion condition')+'</label><textarea id="completion-condition" maxlength="2000" rows="2" placeholder="'+deliveryText('선택 · 비워 두면 AI가 작업 지침에서 정리합니다','Optional · AI will derive this from your instructions')+'"></textarea><label>'+deliveryText('작업물 확인 방법','How to receive the result')+'</label><div id="intake-delivery-choices" class="delivery-choice-list" role="group" aria-label="'+deliveryText('결과 전달 대상','Result destinations')+'"></div>';intake.querySelector('.intake-row').after(deliveryIntake);
const deliveryDialog=document.createElement('dialog');deliveryDialog.id='delivery-dialog';deliveryDialog.className='delivery-dialog';deliveryDialog.setAttribute('aria-label','결과 전달 대상');document.body.append(deliveryDialog);
function deliveryText(ko,en){return window.officeCopy?.(ko,en)??(document.documentElement.lang==='en'?en:ko);}
function deliveryReasonLabel(reason){const known={DELIVERY_TARGET_CHANGED:['대상 연결 정보가 바뀌어 전송을 멈췄습니다.','Destination details changed; delivery stopped.'],DELIVERY_SELECTION_CHANGED:['대상 선택을 바꿔 미전송 건을 취소했습니다.','Unsent delivery was canceled after destinations changed.'],DELIVERY_RESPONSE_UNOBSERVED:['전송 여부가 불확실합니다. 메신저에서 수신 여부를 확인하세요.','Delivery is uncertain. Check the messenger before retrying.'],DELIVERY_RECEIPT_INVALID:['전송 확인을 받지 못했습니다. 메신저에서 수신 여부를 확인하세요.','No valid receipt was received. Check the messenger before retrying.'],DELIVERY_INTERRUPTED_RECONCILE_RECEIPT:['전송 중 연결이 끊겼습니다. 메신저에서 수신 여부를 확인하세요.','Delivery was interrupted. Check the messenger before retrying.'],DELIVERY_BODY_TOO_LARGE:['본문이 길어 해당 메신저로 보내지 못했습니다.','The result text exceeds this messenger’s limit.']};const pair=known[reason];if(pair)return deliveryText(pair[0],pair[1]);const http=/^DELIVERY_PROVIDER_HTTP_(\d{3})$/.exec(reason||'');if(http){const code=Number(http[1]);if(code===401||code===403)return deliveryText('인증 또는 권한이 거절됐습니다. 연결 정보를 확인하세요.','Authentication or permission was denied. Check connection details.');if(code===404||code===410)return deliveryText('대상을 찾을 수 없습니다. 연결 대상을 확인하세요.','Destination not found. Check the connected destination.');if(code===429)return deliveryText('전송 한도에 걸렸습니다. 잠시 뒤 다시 시도하세요.','Rate limited. Try again later.');if([400,413,422].includes(code))return deliveryText('메신저가 본문을 거절했습니다. 길이와 형식을 확인하세요.','The messenger rejected the result text. Check its length and format.');}return deliveryText('전달 상태를 확인해야 합니다.','Delivery needs review.');}
function deliveryChoices(selectedIds,checkboxName){const selectedSet=new Set(selectedIds?.length?selectedIds:['app']),available=(deliveryCatalog?.targets||[]).filter(target=>target.configured),options=[{id:'app',platform:'app',label:deliveryText('피드','Feed')},...available];return options.map(target=>'<label class="delivery-choice"><input type="checkbox" name="'+checkboxName+'" value="'+esc(target.id)+'" '+(selectedSet.has(target.id)?'checked':'')+'><span>'+esc(target.platform==='app'?target.label:(deliveryNames[target.platform]||target.platform)+' · '+target.label)+'</span></label>').join('')+(available.length?'':'<a href="settings" class="delivery-setup-link">'+deliveryText('메신저 연결하기','Connect a messenger')+'</a>');}
function checkedDeliveryIds(name){return Array.from(document.querySelectorAll('input[name="'+name+'"]:checked'),input=>input.value);}
function renderIntakeDelivery(){const host=document.getElementById('intake-delivery-choices');if(!host)return;const chosen=checkedDeliveryIds('intake-delivery');host.innerHTML=deliveryChoices(chosen.length?chosen:(deliveryCatalog?.default_target_ids||['app']),'intake-delivery');}
async function refreshDeliveryCatalog(){try{const response=await fetch('delivery/status',{cache:'no-store'});if(!response.ok)throw Error('delivery settings unavailable');deliveryCatalog=await response.json();renderIntakeDelivery();}catch{deliveryCatalog={targets:[],default_target_ids:['app']};renderIntakeDelivery();}}
function deliveryStatusLabel(row){if(row.authority==='original_runtime')return deliveryText('원본에서 전달 · 여부 미확인','Original runtime delivery · unobserved');return ({available:deliveryText('앱에서 확인 가능','Available in this app'),delivered:deliveryText('전달 완료','Delivered'),failed:deliveryText('전달 실패','Failed'),sending:deliveryText('전달 중','Sending'),reconciliation_required:deliveryText('전달 결과 확인 필요','Review delivery outcome'),pending:deliveryText('전달 대기','Pending')})[row.status]||deliveryText('전달 여부 미확인','Delivery unobserved');}
function deliveryStageHtml(d){const selection=d.delivery;if(!selection)return '';const ids=Array.isArray(selection.target_ids)?selection.target_ids:['app'],rows=Array.isArray(selection.deliveries)?selection.deliveries:[],latest=(d.results||[])[0],verified=Boolean(latest?latest.work_completion_verified:d.supervisor?.completion_verified===true),complete=verified&&rows.length>0&&rows.every(row=>row.status==='delivered'||row.status==='available'),name=id=>id==='app'?deliveryText('이 앱','This app'):(deliveryCatalog?.targets||[]).find(target=>target.id===id)?.label||id,summary=rows.length?rows.map(row=>'<li>'+esc(name(row.target_alias||row.channel))+' · '+esc(!verified&&row.channel==='app'&&row.status==='available'?deliveryText('검증 대기 · 앱에서 초안 확인','Awaiting verification · draft available in app'):deliveryStatusLabel(row))+'</li>').join(''):'<li>'+deliveryText('결과 생성 후 전달 상태가 표시됩니다.','Delivery status appears after a result is created.')+'</li>';return '<section class="delivery-step"><button type="button" class="step '+(complete?'t-done':'t-pend')+'" id="delivery-stage" aria-haspopup="dialog"><span class="num">'+String((d.stages||[]).length+1).padStart(2,'0')+'</span><strong>'+deliveryText('결과 전달','Deliver results')+'</strong><small>'+esc(ids.map(name).join(' · '))+'</small></button><ul class="delivery-state-list">'+summary+'</ul></section>';}
function closeDeliveryDialog(){const dialog=document.getElementById('delivery-dialog');if(dialog?.open){dialog.close();deliveryModalFocus?.focus?.({preventScroll:true});}deliveryModalFocus=null;}
function renderDeliveryDialog(){const dialog=document.getElementById('delivery-dialog');if(!dialog||!deliverySelection)return;if(deliverySelection.authority==='original_runtime'){dialog.innerHTML='<header><h3>'+deliveryText('결과 전달 대상','Result destinations')+'</h3><button type="button" id="delivery-close">'+deliveryText('닫기','Close')+'</button></header><p>'+deliveryText('이 업무의 결과 전달은 원본 실행 환경이 맡습니다. 여기서는 전달 여부를 확인하거나 대상을 바꿀 수 없습니다.','The original runtime manages result delivery for this Work. Office cannot verify delivery or change its destinations.')+'</p>';document.getElementById('delivery-close').onclick=closeDeliveryDialog;return;}const selected=checkedDeliveryIds('work-delivery');const ids=selected.length?selected:deliverySelection.target_ids;dialog.innerHTML='<header><h3>'+deliveryText('결과 전달 대상','Result destinations')+'</h3><button type="button" id="delivery-close">'+deliveryText('닫기','Close')+'</button></header><p class="delivery-policy">'+deliveryText('변경 사항은 아직 보내지 않은 결과에만 적용됩니다. 이미 보낸 결과는 다시 전송하지 않습니다.','Changes apply only to unsent results. Already delivered results are not resent.')+'</p><div class="delivery-targets" role="group" aria-label="'+deliveryText('전달 대상','Destinations')+'">'+deliveryChoices(ids,'work-delivery')+'</div><p id="delivery-feedback" role="status" aria-live="polite"></p><div class="actions"><button type="button" class="primary" id="delivery-save" '+(deliveryModalBusy?'disabled':'')+'>'+deliveryText('저장','Save')+'</button></div>';document.getElementById('delivery-close').onclick=closeDeliveryDialog;document.getElementById('delivery-save').onclick=saveWorkDelivery;}
async function openDeliveryDialog(source){if(!detail)return;deliveryModalFocus=source;const dialog=document.getElementById('delivery-dialog');dialog.showModal();dialog.innerHTML='<p>'+deliveryText('전달 설정을 불러오는 중…','Loading delivery settings…')+'</p>';try{const response=await fetch('work/delivery?work_id='+encodeURIComponent(detail.id),{cache:'no-store'});if(!response.ok)throw Error(deliveryText('전달 설정을 읽지 못했습니다.','Could not load delivery settings.'));deliverySelection=await response.json();await refreshDeliveryCatalog();renderDeliveryDialog();}catch(error){dialog.innerHTML='<p role="alert">'+esc(String(error.message||error))+'</p><button type="button" id="delivery-close">'+deliveryText('닫기','Close')+'</button>';document.getElementById('delivery-close').onclick=closeDeliveryDialog;}}
async function saveWorkDelivery(){if(!detail||!deliverySelection||deliveryModalBusy)return;const ids=checkedDeliveryIds('work-delivery');if(!ids.length){document.getElementById('delivery-feedback').textContent=deliveryText('전달 대상을 하나 이상 선택하세요.','Select at least one destination.');return;}deliveryModalBusy=true;document.getElementById('delivery-save').disabled=true;try{const response=await fetch('work/delivery',{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify({work_id:detail.id,revision:deliverySelection.revision,target_ids:ids})});const data=await response.json();if(!response.ok)throw Error(data.error||deliveryText('저장하지 못했습니다.','Could not save.'));deliverySelection=data;closeDeliveryDialog();await loadDetail();setMessage(deliveryText('이후 전송할 결과의 대상을 저장했습니다.','Destinations for future results saved.'));}catch(error){document.getElementById('delivery-feedback').textContent=String(error.message||error);}finally{deliveryModalBusy=false;const button=document.getElementById('delivery-save');if(button)button.disabled=false;}}
document.getElementById('delivery-dialog')?.addEventListener('close',()=>{deliveryModalFocus?.focus?.({preventScroll:true});deliveryModalFocus=null;});
app.addEventListener('click',event=>{const button=event.target.closest('#delivery-stage');if(button)void openDeliveryDialog(button);});
function decorateDeliveryReasons(d){const latestRows=d.delivery?.deliveries||[],stageRows=app.querySelectorAll('.delivery-state-list li');latestRows.forEach((row,index)=>{if(row.reason&&stageRows[index])stageRows[index].append(document.createTextNode(' · '+deliveryReasonLabel(row.reason)));});app.querySelectorAll('.work-result').forEach((article,resultIndex)=>{const deliveries=d.results?.[resultIndex]?.deliveries||[];article.querySelectorAll('.result-deliveries p').forEach((line,deliveryIndex)=>{const reason=deliveries[deliveryIndex]?.reason;if(!reason)return;const label=document.createElement('small');label.className='delivery-reason';label.textContent=deliveryReasonLabel(reason);line.append(label);});});}
const renderDetailWithoutDelivery=renderDetail;renderDetail=function(){renderDetailWithoutDelivery();if(!detail||detail.server||detail.session)return;const steps=app.querySelector('.steps');if(steps)steps.insertAdjacentHTML('beforeend',deliveryStageHtml(detail));else app.insertAdjacentHTML('beforeend',deliveryStageHtml(detail));decorateDeliveryReasons(detail);};
renderIntakeDelivery();void refreshDeliveryCatalog();window.addEventListener('pageshow',()=>void refreshDeliveryCatalog());
`;
