// Feed: every output in one stream, newest first, read the way a news feed is read. A post is one result of a Work,
// a row a server bot recorded as sent, a post an AI app made with runtime_feed_post, or a conversation's last reply.
// Works that need the owner are pinned on top; what runs now, what runs next and the servers sit beside the stream.
export const feedCss=`.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}.feed{display:flex;flex-wrap:wrap;gap:24px;align-items:flex-start}
.feed-main{flex:1 1 520px;max-width:700px;min-width:0;display:flex;flex-direction:column;gap:14px}
.feed-rail{flex:0 1 300px;min-width:260px;display:flex;flex-direction:column;gap:12px}
.feed-tools{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.feed-tools .chips{display:flex;gap:6px;flex-wrap:wrap}.feed-tools select{width:auto;max-width:220px}
.feed-tools .chips button{min-height:34px;padding:0 12px;border-radius:999px;font:12px var(--mono);background:none;color:var(--dim);border:1px solid var(--line2)}
.feed-tools .chips button[aria-pressed="true"]{border-color:var(--accent);color:var(--accent);background:var(--acc-a)}
.feed-tools .push{margin-left:auto}
.post{display:flex;flex-direction:column;gap:11px;background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px 18px;min-width:0}
.post.new{border-color:color-mix(in srgb,var(--accent) 45%,var(--line))}.post.pin{border-color:var(--human);background:var(--human-a)}
.post .ph{display:flex;align-items:center;gap:11px;min-width:0}.post .av{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;font:600 13px var(--mono);color:#101317;flex:none}
.post .who{display:flex;flex-direction:column;gap:2px;min-width:0}.post .who strong{font:600 14.5px/1.3 var(--sans);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.post .who span{font:11.5px var(--mono);color:var(--dim)}.post .tags{margin-left:auto;display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end;flex:none;max-width:45%}
.post .tag{font:11px var(--mono);border:1px solid var(--line2);border-radius:999px;padding:2px 9px;color:var(--dim);white-space:nowrap}.post .tag.ok{color:var(--ok)}.post .tag.warn{color:var(--human);border-color:var(--human)}.post .tag.new{color:var(--accent);border-color:var(--accent)}
.post h4{margin:0;font:600 16px/1.4 var(--sans)}
.post .body{margin:0;font-size:14.5px;line-height:1.65;white-space:pre-line;overflow-wrap:anywhere;color:var(--text);opacity:.92;display:-webkit-box;-webkit-line-clamp:8;-webkit-box-orient:vertical;overflow:hidden}.post.open .body{display:block}
.post .more{align-self:flex-start;border:0;background:none;padding:0;min-height:0;color:var(--dim);font:12.5px var(--sans);text-decoration:underline}
.post .pics{display:grid;gap:6px;grid-template-columns:2fr 1fr;grid-template-rows:140px 140px;margin:0}.post .pics.n1{grid-template-columns:1fr;grid-template-rows:280px}.post .pics.n2{grid-template-columns:1fr 1fr;grid-template-rows:220px}
.post .pics img{width:100%;height:100%;object-fit:cover;border-radius:10px;background:var(--bg);display:block;cursor:zoom-in}.post img.capture{cursor:zoom-in}
/* A picture opened from the feed: the whole screen, the picture fitted; arrows when the result has more than one. */
.img-viewer{position:fixed;inset:0;z-index:80;display:grid;place-items:center;background:rgba(6,8,11,.92);touch-action:pan-y}.img-viewer[hidden]{display:none}.img-viewer img{max-width:96vw;max-height:88vh;object-fit:contain;border-radius:6px;background:#fff;box-shadow:0 12px 40px rgba(0,0,0,.5)}.img-viewer button{position:absolute;display:grid;place-items:center;width:44px;height:44px;padding:0;border-radius:50%;border:1px solid rgba(255,255,255,.25);background:rgba(16,19,23,.7);color:#fff;font:400 26px/1 var(--sans)}.img-viewer .iv-close{top:14px;right:14px}.img-viewer .iv-prev{left:14px;top:50%;margin-top:-22px}.img-viewer .iv-next{right:14px;top:50%;margin-top:-22px}.img-viewer .iv-bar{position:absolute;bottom:14px;left:0;right:0;display:flex;justify-content:center;gap:14px;font:12px var(--mono);color:#cfd5de}.img-viewer .iv-bar a{color:#cfd5de}.post .pics .big{grid-row:span 2}.post .pics .plus{position:relative}.post .pics .plus b{position:absolute;inset:0;display:grid;place-items:center;background:rgba(16,19,23,.6);border-radius:10px;font:600 22px var(--mono);color:#e6e8eb}
.post .acts{display:flex;gap:4px;flex-wrap:wrap;border-top:1px solid var(--line);padding-top:8px}.post .acts button{min-height:36px;border:0;background:none;color:var(--dim);font:12.5px var(--sans);padding:0 10px;border-radius:8px}.post .acts button:hover{background:var(--raise);color:var(--text)}
.feed-day{display:flex;align-items:center;gap:12px;font:500 11.5px var(--mono);letter-spacing:.1em;color:var(--dim)}.feed-day::after{content:"";flex:1;height:1px;background:var(--line)}
.feed-rail section{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:14px 16px;display:flex;flex-direction:column;gap:8px}
.feed-rail h3{margin:0;font:500 10.5px var(--mono);letter-spacing:.14em;color:var(--dim)}.feed-rail button{display:flex;align-items:center;gap:8px;border:0;background:none;padding:4px 0;min-height:30px;color:var(--text);font:13px var(--sans);text-align:left}
.feed-rail .dot{width:7px;height:7px;border-radius:50%;flex:none;background:var(--line2)}.feed-rail .dot.ok{background:var(--ok)}.feed-rail .dot.run{background:var(--accent)}.feed-rail .dot.warn,.feed-rail .dot.err{background:var(--human)}
.feed-rail button{width:100%;min-width:0}.feed-rail button span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.feed-rail time,.feed-rail em{margin-left:auto;flex:none;max-width:55%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:11.5px var(--mono);font-style:normal;color:var(--dim)}
.feed-end{align-self:center}
.post .player{border-radius:10px;overflow:hidden;background:#0b0d10;display:flex;justify-content:center}.post .player video{display:block;width:100%;max-height:440px;background:#0b0d10}
.post .sound{display:flex;flex-direction:column;gap:6px;background:var(--raise);border-radius:10px;padding:10px 12px}.post .sound span{font:11.5px var(--mono);color:var(--dim);overflow-wrap:anywhere}.post .sound audio{width:100%}
.post .snip{border:1px solid var(--line);border-radius:10px;overflow:hidden;background:var(--bg);min-width:0}.post .snip header{display:flex;gap:8px;padding:7px 12px;border-bottom:1px solid var(--line);font:11.5px var(--mono);color:var(--dim)}.post .snip header b{color:var(--text);font-weight:500;overflow-wrap:anywhere}
.post .snip pre{margin:0;padding:9px 0;font:12.5px/1.6 var(--mono);overflow-x:auto}.post .snip pre span.l{display:block;padding:0 12px;white-space:pre;min-height:1.6em}
.post .snip .hk{color:var(--llm)}.post .snip .hs{color:var(--ok)}.post .snip .hn{color:var(--accent)}.post .snip .hc{color:var(--dim);font-style:italic}
.post .snip .grid{overflow-x:auto}.post .snip table{border-collapse:collapse;width:100%;font:12.5px var(--mono)}.post .snip th{font-weight:500;color:var(--dim);text-align:left}.post .snip th,.post .snip td{padding:6px 12px;border-bottom:1px solid var(--line);white-space:nowrap;max-width:280px;overflow:hidden;text-overflow:ellipsis}
.post .snip footer{display:flex;gap:14px;align-items:center;padding:7px 12px;font:12px var(--sans);color:var(--dim)}.post .snip footer a{margin-left:auto}.post .snip footer a+a{margin-left:0}
.post .doc{display:flex;gap:12px;align-items:center;border:1px solid var(--line);border-radius:10px;padding:10px 12px;color:var(--text);text-decoration:none;min-width:0}.post .doc:hover{border-color:var(--line2)}
.post .doc i{width:38px;height:48px;flex:none;border-radius:5px;background:#e9e6df;color:#8a2a2a;font:600 10.5px var(--mono);font-style:normal;display:grid;place-items:center}.post .doc span{display:flex;flex-direction:column;gap:2px;min-width:0;overflow-wrap:anywhere}.post .doc small{font:11.5px var(--mono);color:var(--dim)}
@media(max-width:1000px){.feed-rail{display:none}}
@media(max-width:760px){.post .player{margin:0 -16px;border-radius:0}.post{border-radius:0;border-left:0;border-right:0;margin:0 -16px;padding:14px 16px}.post .tags{max-width:none}.post .pics{grid-template-rows:110px 110px}.post .pics.n1{grid-template-rows:220px}.post .acts button{min-height:44px}}`;

export function feedScript(){return `
// One viewer for every picture in the feed: arrows, the keyboard and a sideways swipe move between the pictures of
// one result; the backdrop, × and Escape close it.
let viewerList=[],viewerAt=0,viewerTouch=null;
function imageViewer(){let node=document.getElementById('img-viewer');if(node)return node;
  node=document.createElement('div');node.id='img-viewer';node.className='img-viewer';node.hidden=true;node.setAttribute('role','dialog');node.setAttribute('aria-modal','true');
  node.innerHTML='<img alt=""><button type="button" class="iv-close" aria-label="'+esc(ff(['닫기','Close']))+'">×</button><button type="button" class="iv-prev" aria-label="'+esc(ff(['이전 이미지','Previous picture']))+'">‹</button><button type="button" class="iv-next" aria-label="'+esc(ff(['다음 이미지','Next picture']))+'">›</button><div class="iv-bar"><span class="iv-count"></span><a class="iv-open" target="_blank" rel="noopener">'+esc(ff(['원본 열기','Open original']))+'</a></div>';
  node.addEventListener('click',event=>{if(event.target.closest('.iv-prev'))viewerStep(-1);else if(event.target.closest('.iv-next'))viewerStep(1);else if(!event.target.closest('img,.iv-bar'))closeImageViewer()});
  node.addEventListener('touchstart',event=>{viewerTouch=event.touches[0].clientX},{passive:true});
  node.addEventListener('touchend',event=>{if(viewerTouch===null)return;const dx=event.changedTouches[0].clientX-viewerTouch;viewerTouch=null;if(Math.abs(dx)>50)viewerStep(dx<0?1:-1)});
  document.addEventListener('keydown',event=>{if(node.hidden)return;if(event.key==='Escape')closeImageViewer();else if(event.key==='ArrowLeft')viewerStep(-1);else if(event.key==='ArrowRight')viewerStep(1)});
  document.body.append(node);return node}
function viewerShow(){const node=imageViewer(),item=viewerList[viewerAt],img=node.querySelector('img');img.src=item.src;img.alt=item.alt||'';
  node.querySelector('.iv-open').href=item.src.replace(/&inline=1$/u,'');const many=viewerList.length>1;
  node.querySelector('.iv-prev').hidden=!many;node.querySelector('.iv-next').hidden=!many;node.querySelector('.iv-count').textContent=many?(viewerAt+1)+' / '+viewerList.length:''}
function viewerStep(delta){if(viewerList.length<2)return;viewerAt=(viewerAt+delta+viewerList.length)%viewerList.length;viewerShow()}
function openImageViewer(list,at){viewerList=list;viewerAt=Math.max(0,at);viewerShow();imageViewer().hidden=false;document.documentElement.style.overflow='hidden';imageViewer().querySelector('.iv-close').focus()}
function closeImageViewer(){const node=document.getElementById('img-viewer');if(!node||node.hidden)return;node.hidden=true;document.documentElement.style.overflow=''}

let feed=null,feedAt=0,feedTried=0,feedLoading=false,feedFailed=false,feedKind='all',feedWork='',feedSeenAt='',feedOpen=new Set();
try{feedSeenAt=localStorage.getItem('office-feed-seen')||''}catch{}
const ff=pair=>pair[window.officeLang==='en'?1:0];
async function loadFeed(){if(feedLoading)return;feedLoading=true;feedTried=Date.now();try{const response=await fetch('work/feed',{cache:'no-store'});if(!response.ok)throw Error();feed=await response.json();feedAt=Date.now();feedFailed=false}catch{feedFailed=true}finally{feedLoading=false}updateFeedCount();if(!selected&&!importOpen&&view==='feed')renderBoard()}
async function loadMoreFeed(){if(!feed?.next_before||feedLoading)return;feedLoading=true;try{const response=await fetch('work/feed?before='+encodeURIComponent(feed.next_before),{cache:'no-store'});if(response.ok){const more=await response.json();feed.posts=feed.posts.concat(more.posts.filter(p=>!feed.posts.some(q=>q.id===p.id)));feed.next_before=more.next_before}}catch{}finally{feedLoading=false}renderBoard()}
// What the owner has seen: the newest post when they last left the feed. Kept in this browser only.
function markFeedSeen(){const newest=feed?.posts?.[0]?.at;if(!newest||newest<=feedSeenAt)return;feedSeenAt=newest;try{localStorage.setItem('office-feed-seen',newest)}catch{}updateFeedCount()}
function updateFeedCount(){const n=(feed?.posts||[]).filter(p=>p.at>feedSeenAt).length,node=document.querySelector('[data-count="feed"]');if(node)node.textContent=feedSeenAt&&n?ff(['새 ','new '])+n:''}
const FEED_CHANNELS={telegram:['텔레그램','Telegram'],slack:['슬랙','Slack'],discord:['디스코드','Discord'],email:['이메일','email'],chat:['채팅','chat'],file:['파일','file'],other:['외부','external']};
const FEED_COLORS=['#9fc0e3','#6CC08B','#f2c46d','#A99BE0','#E0708A','#6FA8DC','#c9a0dc','#8fd1c1'];
function feedAvatar(id,name){let h=0;for(const c of String(id))h=(h*31+c.charCodeAt(0))>>>0;const mark=String(name||'?').trim().replace(/^[^\\p{L}\\p{N}]+/u,'').slice(0,2)||'?';return '<span class="av" style="background:'+FEED_COLORS[h%FEED_COLORS.length]+'" aria-hidden="true" data-i18n-skip>'+esc(mark)+'</span>'}
function feedDay(at){const d=new Date(at),today=new Date(),y=new Date(Date.now()-86400000);return d.toDateString()===today.toDateString()?ff(['오늘','Today']):d.toDateString()===y.toDateString()?ff(['어제','Yesterday']):d.toLocaleDateString(window.officeLang==='en'?'en-US':'ko-KR',{month:'long',day:'numeric',weekday:'short'})}
function feedPics(post){const imgs=post.images||[];if(!imgs.length)return '';const n=Math.min(imgs.length,3),src=img=>'work/result/artifact?work_id='+encodeURIComponent(post.work_id)+'&amp;result_id='+encodeURIComponent(post.result_id)+'&amp;artifact_id='+encodeURIComponent(img.artifact_id);
return '<div class="pics n'+n+'">'+imgs.slice(0,3).map((img,i)=>'<span class="'+(n===3&&i===0?'big':'')+(i===2&&post.image_count>3?' plus':'')+'"><img loading="lazy" alt="'+esc(img.label)+'" src="'+src(img)+'">'+(i===2&&post.image_count>3?'<b>+'+(post.image_count-3)+'</b>':'')+'</span>').join('')+'</div>'}
// The rest of a result shows by kind: a player, the first lines of code or text, the first rows of a table, a document.
const artifactUrl=(post,id,inline)=>'work/result/artifact?work_id='+encodeURIComponent(post.work_id)+'&amp;result_id='+encodeURIComponent(post.result_id)+'&amp;artifact_id='+encodeURIComponent(id)+(inline?'&amp;inline=1':'');
const fileSize=n=>n>=1048576?(n/1048576).toFixed(1)+'MB':n>=1024?Math.round(n/1024)+'KB':n+'B';
function feedMedia(post){const m=post.media;if(!m)return '';const src=artifactUrl(post,m.artifact_id,true);
 return m.kind==='video'?'<div class="player"><video controls playsinline preload="metadata" src="'+src+'" aria-label="'+esc(m.label)+'"></video></div>':'<div class="sound"><span data-i18n-skip>'+esc(m.label)+'</span><audio controls preload="none" src="'+src+'"></audio></div>'}
const HL_WORDS=new Set('and as async await break case catch class const continue def default del do elif else enum except export extends false False finally fn for from func function if impl import in interface is lambda let match mod new nil None not null or package pass pub raise return self static struct switch this throw true True try type typeof undefined use var while with yield'.split(' '));
const HL_RE={hash:/(#.*$)|("(?:[^"\\\\]|\\\\.)*"|'(?:[^'\\\\]|\\\\.)*')|\\b(\\d+(?:\\.\\d+)?)\\b|\\b([A-Za-z_]\\w*)\\b/g,dash:/(--.*$)|("(?:[^"\\\\]|\\\\.)*"|'(?:[^'\\\\]|\\\\.)*')|\\b(\\d+(?:\\.\\d+)?)\\b|\\b([A-Za-z_]\\w*)\\b/g,slash:/(\\/\\/.*$)|("(?:[^"\\\\]|\\\\.)*"|'(?:[^'\\\\]|\\\\.)*'|\`[^\`]*\`)|\\b(\\d+(?:\\.\\d+)?)\\b|\\b([A-Za-z_]\\w*)\\b/g};
function hlLine(line,lang){if(lang==='text'||lang==='markdown')return esc(line);const re=HL_RE[['python','shell','ruby','yaml','toml'].includes(lang)?'hash':lang==='sql'?'dash':'slash'];re.lastIndex=0;let out='',at=0,m;
 while((m=re.exec(line))){out+=esc(line.slice(at,m.index));const cls=m[1]?'hc':m[2]?'hs':m[3]?'hn':HL_WORDS.has(m[4])?'hk':'';out+=cls?'<span class="'+cls+'">'+esc(m[0])+'</span>':esc(m[0]);at=re.lastIndex;if(!m[0])re.lastIndex++}
 return out+esc(line.slice(at))}
function feedPreview(post){const p=post.preview;if(!p)return '';const full='<a href="'+artifactUrl(post,p.artifact_id,true)+'" target="_blank" rel="noopener">'+esc(ff(['전체 보기','Open']))+'</a><a href="'+artifactUrl(post,p.artifact_id,false)+'" download>'+esc(ff(['받기','Download']))+'</a>';
 if(p.kind==='table')return '<figure class="snip" style="margin:0"><header><b data-i18n-skip>'+esc(p.label)+'</b></header><div class="grid"><table><thead><tr>'+p.header.map(c=>'<th data-i18n-skip>'+esc(c)+'</th>').join('')+'</tr></thead><tbody>'+p.rows.map(r=>'<tr>'+r.map(c=>'<td data-i18n-skip>'+esc(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><footer><span>'+esc(ff([p.total_rows+'행',p.total_rows+' rows']))+'</span>'+full+'</footer></figure>';
 return '<figure class="snip" style="margin:0"><header><b data-i18n-skip>'+esc(p.label)+'</b><span>'+esc(p.lang)+'</span></header><pre data-i18n-skip>'+p.lines.map(l=>'<span class="l">'+hlLine(l,p.lang)+'</span>').join('')+'</pre><footer><span>'+esc(p.total_lines>p.lines.length?ff([p.total_lines+'줄 중 '+p.lines.length+'줄','first '+p.lines.length+' of '+p.total_lines+' lines']):ff([p.total_lines+'줄',p.total_lines+' lines']))+'</span>'+full+'</footer></figure>'}
function feedDoc(post){const d=post.doc;if(!d)return '';return '<a class="doc" href="'+artifactUrl(post,d.artifact_id,true)+'" target="_blank" rel="noopener"><i>PDF</i><span><b data-i18n-skip>'+esc(d.label)+'</b><small>'+esc(fileSize(d.bytes)+' · '+ff(['열어 읽기','Open to read']))+'</small></span></a>'}
const FEED_KINDS=[['all',['전체','All']],['images',['이미지','Images']],['media',['영상·소리','Video · audio']],['code',['코드','Code']],['data',['표','Tables']],['changes',['변화','Changes']],['apps',['앱','Apps']],['docs',['문서','Documents']],['text',['글','Text']],['reply',['대화','Conversations']],['attention',['확인 필요','Needs you']]];
function postKinds(post){if(post.kind==='reply')return ['reply'];if(post.kind==='change')return ['changes'];const kinds=[];if(post.apps?.length)kinds.push('apps');if(post.images?.length)kinds.push('images');if(post.media)kinds.push('media');if(post.preview)kinds.push(post.preview.kind==='table'?'data':'code');if(post.doc)kinds.push('docs');return kinds.length?kinds:['text']}
function feedPostHtml(post,works){const work=works.get(post.work_id),name=post.work_title||post.source_label||ff(['AI 앱','AI app']),isNew=feedSeenAt&&post.at>feedSeenAt;
const who=[post.kind==='change'?ff(['감시','Monitor']):post.kind==='external'?post.source_label:post.kind==='reply'?(post.client==='claude'?'Claude Code':'Codex')+ff([' 대화',' conversation']):work?kindLabel({...work,run:{kind:work.kind},client:work.client?{id:work.client}:null}):'',work&&post.kind==='result'?scheduleChip(work):'',ago(post.at)].filter(Boolean).join(' · ');
const sent=(post.deliveries||[]).map(d=>'<span class="tag'+(d.status==='delivered'?' ok':['failed','reconciliation_required'].includes(d.status)?' warn':'')+'">'+(d.status==='delivered'?'✓ ':'')+esc(ff(FEED_CHANNELS[d.channel]||[d.channel,d.channel]))+'</span>').join('');
const tags=(isNew?'<span class="tag new">'+esc(ff(['새','new']))+'</span>':'')+(post.kind==='change'?'<span class="tag new">'+esc(ff(['변화','Change']))+'</span>':'')+(post.kind==='external'?'<span class="tag">'+esc(ff(['직접 발송','sent directly']))+'</span>':'')+sent;
const open=feedOpen.has(post.id);
const acts=(post.work_id?'<button type="button" data-feed-open="'+esc(post.work_id)+'">'+esc(post.kind==='reply'?ff(['대화 열기','Open conversation']):ff(['업무 열기','Open Work']))+'</button>':'')+(post.files?'<button type="button" data-feed-open="'+esc(post.work_id)+'">'+esc(ff(['파일 ','Files '])+post.files)+'</button>':'')+(post.work_id&&work&&!work.server?'<button type="button" data-feed-direct="'+esc(post.work_id)+'">'+esc(ff(['이 결과에 지시하기','Direct from this result']))+'</button>':'');
return '<article class="post'+(isNew?' new':'')+(open?' open':'')+'" data-post="'+esc(post.id)+'"><div class="ph">'+feedAvatar(post.work_id||post.source_label,name)+'<span class="who"><strong data-i18n-skip>'+esc(name)+'</strong><span>'+esc(who)+'</span></span><span class="tags">'+tags+'</span></div>'
+articleHtml(post)+(post.kind==='change'?changeHtml(post):'')+cardHtml(post.card,post.work_id)+feedPics(post)+feedMedia(post)+feedPreview(post)+feedDoc(post)+(post.apps||[]).map(a=>appHtml(post,a)).join('')+(acts?'<div class="acts">'+acts+'</div>':'')+'</article>'}
function feedPinHtml(work){return '<article class="post pin"><div class="ph">'+feedAvatar(work.id,work.title)+'<span class="who"><strong data-i18n-skip>'+esc(work.title)+'</strong><span>'+esc([kindLabel({...work,run:{kind:work.kind},client:work.client?{id:work.client}:null}),ago(work.last_event?.at||'')].filter(Boolean).join(' · '))+'</span></span><span class="tags"><span class="tag warn">'+esc(groups[0][1])+'</span></span></div>'+(work.questions?.length?questionsHtml(work):'<p class="body" data-i18n-skip>'+esc(work.note||(work.server?serverSummary(work):labels[work.status]||work.status))+'</p>')+'<div class="acts"><button type="button" data-feed-open="'+esc(work.id)+'">'+esc(ff(['열어서 처리하기','Open and handle']))+'</button></div></article>'}
function feedRailHtml(works){const running=works.filter(w=>groupOf(w.status)==='active'&&!w.server),next=works.filter(w=>w.schedule?.enabled&&w.schedule.next_run_at).sort((a,b)=>a.schedule.next_run_at.localeCompare(b.schedule.next_run_at)).slice(0,5),servers=new Map();
for(const w of works)if(w.server){const key=w.server.host+'|'+w.server.target;if(!servers.has(key))servers.set(key,{name:w.server.target,items:[]});servers.get(key).items.push(w)}
return '<div class="feed-rail" role="region" aria-label="'+esc(ff(['지금 상태','Now']))+'">'+(running.length?'<section><h3>'+esc(ff(['지금 실행 중','RUNNING']))+'</h3>'+running.map(w=>'<button type="button" data-feed-open="'+esc(w.id)+'"><i class="dot run"></i><span data-i18n-skip>'+esc(w.title)+'</span><time>'+esc(ago(w.last_event?.at||''))+'</time></button>').join('')+'</section>':'')
+(next.length?'<section><h3>'+esc(ff(['다음 산출물','NEXT']))+'</h3>'+next.map(w=>'<button type="button" data-feed-open="'+esc(w.id)+'"><span data-i18n-skip>'+esc(w.title)+'</span><time>'+esc(clock(w.schedule.next_run_at))+'</time></button>').join('')+'</section>':'')
+[...servers.values()].map(s=>{const bad=s.items.filter(i=>groupOf(i.status)==='attention');return '<section><h3 data-i18n-skip>'+esc(s.name)+'</h3>'+s.items.map(i=>'<button type="button" data-feed-open="'+esc(i.id)+'"><i class="dot '+tone(i.status)+'"></i><span data-i18n-skip>'+esc(i.title)+'</span><em data-i18n-skip>'+esc(groupOf(i.status)==='attention'?serverSummary(i):'')+'</em></button>').join('')+(bad.length?'':'<em>'+esc(ff(['모두 정상','All healthy']))+'</em>')+'</section>'}).join('')+'</div>'}
function renderFeed(q){if((!feed||Date.now()-feedAt>15000)&&Date.now()-feedTried>5000)loadFeed();
const focused=document.activeElement;if(feed&&app.querySelector('.feed')&&focused&&app.contains(focused)&&focused.closest('.post')&&focused.matches('input,select,textarea')){feedDeferred=true;return}
if(!feed){app.innerHTML=feedFailed?'<p class="muted keep">'+esc(ff(['피드를 불러오지 못했어요. 잠시 뒤 다시 시도해요.','The feed could not be loaded. Trying again shortly.']))+'</p>':'<div class="feed" aria-busy="true" aria-label="'+esc(ff(['피드를 모으는 중','Gathering the feed']))+'"><div class="feed-main">'+[0,1,2].map(()=>'<div class="post skel-post"><div class="ph"><span class="sk" style="width:38px;height:38px;border-radius:10px"></span><span class="who" style="flex:1;gap:6px"><span class="sk" style="width:45%"></span><span class="sk" style="width:30%;height:10px"></span></span></div><span class="sk" style="width:70%;height:18px"></span><span class="sk" style="width:100%"></span><span class="sk" style="width:92%"></span><span class="sk" style="width:60%"></span></div>').join('')+'</div></div>';return}
const works=new Map(feed.works.map(w=>[w.id,w])),match=post=>(!feedWork||post.work_id===feedWork)&&(feedKind==='all'||postKinds(post).includes(feedKind))&&(!q||String(post.work_title||post.source_label||'').toLowerCase().includes(q)||String(post.text).toLowerCase().includes(q));
const approvals=(feed.approvals||[]).filter(a=>!feedWork||a.work_id===feedWork),waiting=new Set(approvals.map(a=>a.work_id)),pins=feed.works.filter(w=>groupOf(w.status)==='attention'&&!waiting.has(w.id)&&(!feedWork||w.id===feedWork)),posts=feedKind==='attention'?[]:feed.posts.filter(match);let day='',stream='';
for(const post of posts){const d=feedDay(post.at);if(d!==day){day=d;stream+='<div class="feed-day">'+esc(d)+'</div>'}stream+=feedPostHtml(post,works)}
const authors=[...new Map(feed.works.map(w=>[w.id,w.title])).entries()];
const tools='<div class="feed-tools"><div class="chips" role="group" aria-label="'+esc(ff(['산출물 거르기','Filter outputs']))+'">'+FEED_KINDS.filter(([id])=>id==='all'||id==='attention'||id===feedKind||feed.posts.some(p=>postKinds(p).includes(id))).map(([id,label])=>'<button type="button" data-feed-kind="'+id+'" aria-pressed="'+(feedKind===id)+'">'+esc(ff(label))+(id==='attention'&&pins.length+approvals.length?' '+(pins.length+approvals.length):'')+'</button>').join('')+'</div><label class="sr-only" for="feed-work">'+esc(ff(['업무로 거르기','Filter by Work']))+'</label><select id="feed-work"><option value="">'+esc(ff(['모든 업무','All Works']))+'</option>'+authors.map(([id,title])=>'<option value="'+esc(id)+'"'+(feedWork===id?' selected':'')+' data-i18n-skip>'+esc(title)+'</option>').join('')+'</select><button type="button" class="push" id="feed-push">'+esc(pushLabel())+'</button></div>';
// A player that has started keeps playing across refreshes: the same element goes back in place.
const kept=new Map([...app.querySelectorAll('.post video,.post audio')].filter(m=>m.currentTime>0||!m.paused).map(m=>[m.getAttribute('src'),m]));
app.innerHTML='<div class="feed"><div class="feed-main">'+tools+watchLineHtml(feed.works.filter(w=>!feedWork||w.id===feedWork))+approvals.map(approvalHtml).join('')+pins.map(feedPinHtml).join('')+(stream||(pins.length||approvals.length?'':'<div class="empty">'+esc(feedKind==='all'&&!feedWork&&!q?ff(['아직 산출물이 없어요. 업무가 결과를 내면 여기에 쌓여요.','No outputs yet. Results land here as your Works produce them.']):ff(['조건에 맞는 산출물이 없어요.','No output matches.']))+'</div>'))+(feed.next_before&&feedKind!=='attention'?'<button type="button" class="feed-end" id="feed-more">'+esc(ff(['이전 산출물 더 보기','Older outputs']))+'</button>':'')+'</div>'+feedRailHtml(feed.works)+'</div>';
for(const m of app.querySelectorAll('.post video,.post audio')){const old=kept.get(m.getAttribute('src'));if(old)m.replaceWith(old)}}
app.addEventListener('click',event=>{if(view!=='feed'||selected)return;const t=event.target;
const pic=t.closest('.post .pics img, .post img.capture');if(pic){const all=[...pic.closest('.pics, .post').querySelectorAll(pic.matches('.capture')?'img.capture':'.pics img')];openImageViewer(all.map(img=>({src:img.currentSrc||img.src,alt:img.alt})),all.indexOf(pic));return}
const kind=t.closest('[data-feed-kind]');if(kind){feedKind=kind.dataset.feedKind;renderBoard();return}
const more=t.closest('[data-feed-more]');if(more){const id=more.dataset.feedMore;feedOpen.has(id)?feedOpen.delete(id):feedOpen.add(id);renderBoard();return}
const open=t.closest('[data-feed-open]');if(open){markFeedSeen();openWork(open.dataset.feedOpen);return}
const direct=t.closest('[data-feed-direct]');if(direct){markFeedSeen();chatFocus=true;openWork(direct.dataset.feedDirect);return}
if(t.closest('#feed-more')){loadMoreFeed();return}
if(t.closest('#feed-push'))togglePush()});
app.addEventListener('change',event=>{if(event.target.id==='feed-work'&&view==='feed'){feedWork=event.target.value;renderBoard()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&view==='feed'&&!selected)markFeedSeen()});
// A picture that cannot be served any more (its file was replaced) is left out rather than shown broken.
app.addEventListener('error',event=>{const img=event.target;if(img?.tagName==='IMG'&&img.classList.contains('capture')){img.hidden=true;return}if(img?.tagName!=='IMG'||!img.closest('.pics,.rpics'))return;(img.closest('.pics>span')||img).hidden=true;const pics=img.closest('.pics');if(pics&&[...pics.children].every(c=>c.hidden))pics.hidden=true},true);
// Push: the browser's own push service carries Office's notices to this device. On an iPhone it works in the app added to the home screen.
let pushState='unknown';
const pushSupported=()=>'serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window;
function pushLabel(){return pushState==='on'?ff(['알림 켜짐','Notifications on']):ff(['알림 받기','Get notifications'])}
async function pushRegistration(){return navigator.serviceWorker.register('sw.js')}
async function refreshPushState(){if(!pushSupported()){pushState='unsupported';return}try{const reg=await pushRegistration(),sub=await reg.pushManager.getSubscription();pushState=sub&&Notification.permission==='granted'?'on':'off'}catch{pushState='off'}const b=document.getElementById('feed-push');if(b)b.textContent=pushLabel()}
const keyBytes=key=>{const padded=(key+'='.repeat((4-key.length%4)%4)).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(padded);return Uint8Array.from(raw,c=>c.charCodeAt(0))};
async function pushPost(path,body){const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(body)});if(!response.ok)throw Error((await response.json().catch(()=>({}))).error||'PUSH_REQUEST_INVALID');return response.json()}
async function togglePush(){
 if(!pushSupported()){setMessage(ff(['이 브라우저에서는 알림을 켤 수 없어요. 아이폰은 Safari에서 홈 화면에 추가한 Agent Office 앱을 열어 켜 주세요.','This browser cannot take notifications. On an iPhone, open the Agent Office app added to the home screen from Safari.']));return}
 try{const reg=await pushRegistration(),current=await reg.pushManager.getSubscription();
  if(pushState==='on'&&current){if(!confirm(ff(['이 기기의 알림을 끌까요?','Turn notifications off on this device?'])))return;await pushPost('push/unsubscribe',{endpoint:current.endpoint});await current.unsubscribe();pushState='off';setMessage(ff(['이 기기의 알림을 껐어요.','Notifications are off on this device.']))}
  else{const permission=await Notification.requestPermission();if(permission!=='granted'){setMessage(ff(['알림이 허용되지 않았어요. 기기 설정에서 Agent Office 알림을 허용해 주세요.','Notifications were not allowed. Allow them for Agent Office in the device settings.']));return}
   const {public_key}=await (await fetch('push/key',{cache:'no-store'})).json(),sub=current||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(public_key)});
   await pushPost('push/subscribe',{subscription:sub.toJSON()});await pushPost('push/test',{});pushState='on';setMessage(ff(['알림을 켰어요. 시험 알림을 보냈어요.','Notifications are on. A test notice is on its way.']))}}
 catch(error){setMessage(ff(['알림을 켜지 못했어요: ','Could not turn notifications on: '])+String(error.message||error))}
 const b=document.getElementById('feed-push');if(b)b.textContent=pushLabel()}
refreshPushState();
`;}
