// Feed cards that take the owner's press: a prepared write to approve, a Work's questions, a monitor's change and its
// one-line status, the structured cards an AI app posts, and app cards that run a declared command on this computer.
export const feedCardsCss=`.watch-line{display:flex;gap:6px;flex-wrap:wrap}.watch-line button{display:flex;align-items:center;gap:8px;min-height:34px;border-radius:999px;padding:0 13px;font:12px var(--mono);color:var(--text);background:var(--panel);border:1px solid var(--line);max-width:100%}
.watch-line button span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.watch-line i{width:8px;height:8px;border-radius:50%;flex:none;background:var(--accent)}.watch-line i.bad{background:var(--human)}.watch-line i.off{background:var(--idle)}
.post .kv{display:grid;grid-template-columns:minmax(80px,max-content) minmax(0,1fr);gap:6px 14px;margin:0;background:var(--raise);border-radius:10px;padding:12px;font-size:13.5px}.post .kv dt{color:var(--dim)}.post .kv dd{margin:0;overflow-wrap:anywhere}.post .kv s{color:var(--dim)}
.post .capture{max-width:100%;max-height:360px;object-fit:contain;border:1px solid var(--line);border-radius:10px;background:#fff;align-self:flex-start}
.post .press{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.post .press button,.post .press a{min-height:40px;padding:0 16px;border-radius:9px;font:13px var(--sans);border:1px solid var(--line2);background:none;color:var(--text);display:inline-flex;align-items:center;text-decoration:none}
.post .press .main{border:0;background:var(--accent);color:var(--accent-ink);font-weight:600}.post .press button[aria-pressed="true"]{border-color:var(--accent);color:var(--accent);background:var(--acc-a)}.post .press button:disabled{opacity:.55}
.post .note{font:11.5px var(--mono);color:var(--dim);margin:0}
.post .snip.diff td.mark{font:11px var(--mono);color:var(--dim)}.post .snip.diff tr.added td{background:var(--ok-a)}.post .snip.diff tr.removed td{color:var(--dim);text-decoration:line-through}.post .snip.diff s{color:var(--dim)}.post .snip.diff tr.changed .mark{color:var(--accent)}
.post .q{display:flex;flex-direction:column;gap:8px}.post .qvalue{display:flex;flex-direction:column;gap:4px;font-size:12px;color:var(--dim)}.post .qvalue input{min-height:40px}.post .q b{font:600 14.5px/1.45 var(--sans)}
.post .low{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}.post .low s{font:14px var(--mono);color:var(--dim)}.post .low b{font:600 22px var(--mono)}
.post .cmp-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px}.post .cmp-item{display:flex;flex-direction:column;gap:5px;background:var(--raise);border:1px solid transparent;border-radius:10px;padding:11px;min-width:0}
.post .cmp-item.rec{border-color:var(--accent)}.post .cmp-item b{font:600 13.5px var(--sans)}.post .cmp-item span{font-size:12.5px;color:var(--dim);overflow-wrap:anywhere}.post .cmp-item em{font:500 10.5px var(--mono);color:var(--accent);font-style:normal}
.post .chg{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);gap:10px;align-items:center;background:var(--raise);border-radius:10px;padding:12px}.post .chg s{color:var(--dim);overflow-wrap:anywhere}.post .chg b{overflow-wrap:anywhere}
.post .metric{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}.post .metric b{font:600 32px var(--mono)}.post .metric span,.post .metric small{font:12px var(--mono);color:var(--dim)}.post .metric em{font:600 14px var(--mono);font-style:normal;color:var(--accent)}
.post .draft{display:flex;flex-direction:column;gap:6px;background:var(--raise);border-radius:10px;padding:12px}.post .draft small{font:11.5px var(--mono);color:var(--dim)}.post .draft p{margin:0;white-space:pre-wrap;font-size:13.5px;line-height:1.6;overflow-wrap:anywhere}
.post .evt{display:flex;gap:12px;align-items:center;background:var(--raise);border-radius:10px;padding:12px}.post .evt .cal{width:52px;flex:none;display:flex;flex-direction:column;align-items:center;border-radius:8px;background:var(--bg);padding:6px 0}.post .evt .cal small{font:11px var(--mono);color:var(--human)}.post .evt .cal b{font:600 22px var(--mono)}.post .evt span{display:flex;flex-direction:column;gap:2px;min-width:0}.post .evt span small{font:12px var(--mono);color:var(--dim)}
.post .chk{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:6px;font-size:13.5px}.post .chk li.done{color:var(--dim);text-decoration:line-through}.post .chk li::before{content:"○ ";color:var(--dim)}.post .chk li.done::before{content:"✓ ";color:var(--ok)}
.post .appcard{display:flex;flex-direction:column;gap:10px;border:1px solid var(--line);border-radius:10px;padding:12px;min-width:0}.post .appcard header{display:flex;gap:8px;align-items:baseline;font:600 13.5px var(--sans)}.post .appcard header small{font:11px var(--mono);color:var(--dim);font-weight:400}
.post .appcard .fields{display:flex;gap:10px;flex-wrap:wrap;align-items:flex-end}.post .appcard label{display:flex;flex-direction:column;gap:4px;font-size:12px;color:var(--dim)}.post .appcard label.tog{flex-direction:row;align-items:center;gap:8px;min-height:40px;color:var(--text);font-size:13px}
.post .appcard select,.post .appcard input[type=text],.post .appcard input[type=number]{min-height:40px;min-width:120px}.post .appcard input[type=checkbox]{width:18px;height:18px;accent-color:var(--accent)}
.post .appcard pre{margin:0;white-space:pre-wrap;font:12.5px/1.6 var(--mono);background:var(--bg);border-radius:8px;padding:10px;max-height:320px;overflow:auto;overflow-wrap:anywhere}.post .appcard code{font:11.5px var(--mono);overflow-wrap:anywhere}
.post .appcard .grid{overflow-x:auto;border:1px solid var(--line);border-radius:8px}.post .appcard table{border-collapse:collapse;width:100%;font:12.5px var(--mono)}.post .appcard th{font-weight:500;color:var(--dim);text-align:left}.post .appcard th,.post .appcard td{padding:6px 10px;border-bottom:1px solid var(--line);white-space:nowrap}
.post .appcard .err{color:var(--human)}
@media(max-width:760px){.post .press button,.post .press a{min-height:44px}.post .appcard .fields{flex-direction:column;align-items:stretch}.post .appcard select,.post .appcard input[type=text],.post .appcard input[type=number]{width:100%;min-height:44px}}`;

export function feedCardsScript(){return `
const appVals={},appBusy=new Map(),answerPicks={},answerValues={};let feedDeferred=false;
const httpsUrl=u=>/^https:\\/\\//.test(String(u||''));
const minutesLeft=at=>Math.max(0,Math.round((Date.parse(at)-Date.now())/60000));
// A prepared write waiting for the owner: the exact values (and what they replace), the capture, approve or decline.
function approvalHtml(a){const vals=Object.entries(a.values||{}),before=a.before||{};
 return '<article class="post pin" data-post="a:'+esc(a.task_id)+'"><div class="ph">'+feedAvatar(a.work_id||a.task_id,a.work_title||a.target||'?')+'<span class="who"><strong data-i18n-skip>'+esc(a.work_title||a.target||ff(['외부 변경','External change']))+'</strong><span>'+esc([a.family==='record.update'?ff(['기록 수정','Record update']):ff(['제출 준비','Ready to submit']),ff([minutesLeft(a.expires_at)+'분 안에 승인',''+minutesLeft(a.expires_at)+' min left to approve'])].join(' · '))+'</span></span><span class="tags"><span class="tag warn">'+esc(ff(['승인 필요','Needs approval']))+'</span></span></div>'
 +(vals.length?'<dl class="kv" data-i18n-skip>'+vals.map(([k,v])=>'<dt>'+esc(k)+'</dt><dd>'+(k in before&&before[k]!==v?'<s>'+esc(before[k])+'</s> → ':'')+esc(v)+'</dd>').join('')+'</dl>':'')
 +'<img class="capture" loading="lazy" alt="'+esc(ff(['제출 직전 화면','The page just before submitting']))+'" src="work/approval/capture?task_id='+encodeURIComponent(a.task_id)+'">'
 +'<div class="press"><button type="button" class="main" data-approval="approve" data-task="'+esc(a.task_id)+'" data-hash="'+esc(a.proposal_hash)+'">'+esc(a.family==='record.update'?ff(['반영 승인','Approve change']):ff(['제출 승인','Approve submit']))+'</button><button type="button" data-approval="decline" data-task="'+esc(a.task_id)+'" data-hash="'+esc(a.proposal_hash)+'">'+esc(ff(['취소','Decline']))+'</button>'+(a.work_id?'<button type="button" data-feed-open="'+esc(a.work_id)+'">'+esc(ff(['업무 열기','Open Work']))+'</button>':'')+'</div>'
 +'<p class="note">'+esc(ff(['이 화면 그대로일 때 한 번만 제출해요. 제출 뒤 결과를 다시 읽어 확인해요.','Submits once, only while it is exactly this. The result is read back after.']))+'</p></article>'}
// A Work waiting on the owner's answers: tap an option; one plain question goes as soon as it is picked. An option that
// needs a value opens a field for it under the question.
const answerReady=w=>{const picks=answerPicks[w.id]||{},vals=answerValues[w.id]||{};return w.questions.every(q=>{const o=q.options.find(x=>x.id===picks[q.id]);return o?!o.needs_value||Boolean((vals[q.id]||'').trim()):!q.required})};
function questionsHtml(w){const picks=answerPicks[w.id]||{},vals=answerValues[w.id]||{},needsField=w.questions.some(q=>q.options.find(o=>o.id===picks[q.id])?.needs_value);
 return w.questions.map(q=>{const picked=q.options.find(o=>o.id===picks[q.id]);return '<div class="q"><b data-i18n-skip>'+esc(q.prompt)+'</b><div class="press">'+q.options.map(o=>'<button type="button" data-answer="'+esc(w.id)+'" data-q="'+esc(q.id)+'" data-o="'+esc(o.id)+'" aria-pressed="'+(picks[q.id]===o.id)+'"'+(o.id===q.recommended_id?' class="main"':'')+' data-i18n-skip>'+esc(o.label)+(o.needs_value?' …':'')+'</button>').join('')+'</div>'
  +(picked?.needs_value?'<label class="qvalue"><span data-i18n-skip>'+esc(picked.value_hint||ff(['값을 적어 주세요','Enter the value']))+'</span><input type="text" maxlength="700" data-answer-value="'+esc(w.id)+'" data-q="'+esc(q.id)+'" value="'+esc(vals[q.id]||'')+'"></label>':'')+'</div>'}).join('')
 +(w.questions.length>1||needsField?'<div class="press"><button type="button" class="main" data-answer-send="'+esc(w.id)+'"'+(answerReady(w)?'':' disabled')+'>'+esc(ff(['답하고 계속하기','Answer and go on']))+'</button></div>':'')}
function watchLineHtml(works){const watching=works.filter(w=>w.watch);if(!watching.length)return '';
 return '<div class="watch-line" role="list" aria-label="'+esc(ff(['감시 중','Watching']))+'">'+watching.map(w=>{const s=w.watch,state=s.paused?ff(['멈춤','paused']):s.failing?ff(['확인 실패','check failed']):s.changes?ff(['변화 '+s.changes+'회','changed '+s.changes+'×']):ff(['아직 없음','no change yet']);
  return '<button type="button" role="listitem" data-feed-open="'+esc(w.id)+'"><i class="'+(s.paused?'off':s.failing?'bad':'')+'"></i><span data-i18n-skip>'+esc([w.title,s.checked_at?ago(s.checked_at)+ff([' 확인',' checked']):'',s.paused?'':ff(['다음 ','next '])+clock(s.next_at),state].filter(Boolean).join(' · '))+'</span></button>'}).join('')+'</div>'}
// A monitor's change: the lowest value before and after when it tracks one, the rows it saw and its source page.
function changeHtml(post){const c=post.change||{};
 return (c.lowest_after!==null&&c.lowest_after!==undefined?'<div class="low"><s>'+esc(Number(c.lowest_before).toLocaleString())+'</s><span aria-hidden="true">→</span><b>'+esc(Number(c.lowest_after).toLocaleString())+'</b><span class="note">'+esc(ff(['최저값','lowest']))+'</span></div>':'<p class="body">'+esc(ff(['살펴보던 내용이 바뀌었어요.','What it watches has changed.']))+'</p>')
 +(c.diff?.changes?.length?'<figure class="snip diff" style="margin:0"><div class="grid"><table><thead><tr><th></th>'+c.diff.header.map(h=>'<th data-i18n-skip>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+c.diff.changes.map(r=>'<tr class="'+r.kind+'"><td class="mark">'+esc(r.kind==='added'?ff(['새로','new']):r.kind==='removed'?ff(['사라짐','gone']):ff(['바뀜','changed']))+'</td>'+r.cells.map(v=>'<td data-i18n-skip>'+(v.old!==undefined?'<s>'+esc(v.old)+'</s> → <b>'+esc(v.value)+'</b>':esc(v.value))+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'+(c.diff.total>c.diff.changes.length?'<footer><span>'+esc(ff(['바뀐 행 '+c.diff.total+'개 중 '+c.diff.changes.length+'개',c.diff.changes.length+' of '+c.diff.total+' changed rows']))+'</span></footer>':'')+'</figure>'
 :c.rows?.length?'<figure class="snip" style="margin:0"><div class="grid"><table><thead><tr>'+c.header.map(h=>'<th data-i18n-skip>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+c.rows.map(r=>'<tr>'+r.map(v=>'<td data-i18n-skip>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'+(c.total_rows>c.rows.length?'<footer><span>'+esc(ff([c.total_rows+'행 중 '+c.rows.length+'행','first '+c.rows.length+' of '+c.total_rows]))+'</span></footer>':'')+'</figure>':'')
 +(httpsUrl(c.url)?'<div class="press"><a class="main" href="'+esc(c.url)+'" target="_blank" rel="noopener noreferrer">'+esc(ff(['원본 페이지 열기','Open the page']))+'</a></div>':'')}
function cardHtml(card,workId){if(!card)return '';let body='';
 if(card.type==='compare')body='<div class="cmp-grid">'+card.items.map(it=>'<div class="cmp-item'+(it.recommended?' rec':'')+'" data-i18n-skip><b>'+esc(it.title)+'</b>'+(it.lines||[]).map(l=>'<span>'+esc(l)+'</span>').join('')+(it.recommended?'<em>'+esc(ff(['추천','Pick']))+'</em>':'')+(httpsUrl(it.url)?'<a href="'+esc(it.url)+'" target="_blank" rel="noopener noreferrer">'+esc(ff(['보기','View']))+'</a>':'')+'</div>').join('')+'</div>';
 else if(card.type==='change')body=(card.label?'<p class="note" data-i18n-skip>'+esc(card.label)+'</p>':'')+'<div class="chg" data-i18n-skip><s>'+esc(card.before)+'</s><span aria-hidden="true">→</span><b>'+esc(card.after)+'</b></div>'+(httpsUrl(card.url)?'<div class="press"><a href="'+esc(card.url)+'" target="_blank" rel="noopener noreferrer">'+esc(ff(['원본 열기','Open source']))+'</a></div>':'');
 else if(card.type==='metric')body='<div class="metric" data-i18n-skip><b>'+esc(card.value)+'</b>'+(card.unit?'<span>'+esc(card.unit)+'</span>':'')+(card.delta?'<em>'+esc(card.delta)+'</em>':'')+'<small>'+esc(card.label)+'</small></div>';
 else if(card.type==='draft'){const mail=/^[^@\\s]+@[^@\\s]+$/.test(card.to||'')?card.to:'',href='mailto:'+encodeURIComponent(mail)+'?'+(card.subject?'subject='+encodeURIComponent(card.subject)+'&amp;':'')+'body='+encodeURIComponent(card.body);
  body='<div class="draft" data-i18n-skip>'+(card.to||card.subject?'<small>'+esc([card.to,card.subject].filter(Boolean).join(' · '))+'</small>':'')+'<p>'+esc(card.body)+'</p></div><div class="press"><button type="button" class="main" data-card-copy="'+esc(card.body)+'">'+esc(ff(['복사','Copy']))+'</button><a href="'+href+'">'+esc(ff(['메일 앱에서 열기','Open in mail app']))+'</a></div>'}
 else if(card.type==='event'){const d=new Date(card.start),lang=window.officeLang==='en'?'en-US':'ko-KR';
  body='<div class="evt" data-i18n-skip><span class="cal"><small>'+esc(d.toLocaleDateString(lang,{month:'short'}))+'</small><b>'+d.getDate()+'</b></span><span><b>'+esc(card.name)+'</b><small>'+esc([d.toLocaleString(lang,{weekday:'short',hour:'2-digit',minute:'2-digit'}),card.location].filter(Boolean).join(' · '))+'</small></span></div><div class="press"><button type="button" class="main" data-card-ics="1" data-name="'+esc(card.name)+'" data-start="'+esc(card.start)+'" data-end="'+esc(card.end||'')+'" data-place="'+esc(card.location||'')+'">'+esc(ff(['캘린더에 추가','Add to calendar']))+'</button></div>'}
 else if(card.type==='checklist')body='<ul class="chk" data-i18n-skip>'+card.items.map(i=>'<li class="'+(i.done?'done':'')+'">'+esc(i.text)+'</li>').join('')+'</ul>';
 const links=(card.actions||[]).filter(a=>httpsUrl(a.url)).map(a=>'<a href="'+esc(a.url)+'" target="_blank" rel="noopener noreferrer" data-i18n-skip>'+esc(a.label)+'</a>').join(''),replies=workId?(card.replies||[]).map(r=>'<button type="button" data-card-reply="'+esc(workId)+'" data-text="'+esc(r.text)+'" data-i18n-skip>'+esc(r.label)+'</button>').join(''):'';
 return (card.title?'<h4 data-i18n-skip>'+esc(card.title)+'</h4>':'')+body+(links||replies?'<div class="press">'+replies+links+'</div>':'')}
// An app card: the declared inputs and buttons; the first press shows the exact command for the owner to approve.
function appHtml(post,a){const key=post.result_id+'|'+a.artifact_id,vals=appVals[key]||(appVals[key]={}),run=a.last_run,busy=appBusy.get(key)||(run?.status==='running'?run.button:null),value=i=>i.id in vals?vals[i.id]:i.default;
 const fields=a.inputs.map(i=>i.type==='toggle'?'<label class="tog"><input type="checkbox" data-app-input="'+esc(i.id)+'"'+(value(i)?' checked':'')+'><span data-i18n-skip>'+esc(i.label)+'</span></label>'
  :i.type==='select'?'<label><span data-i18n-skip>'+esc(i.label)+'</span><select data-app-input="'+esc(i.id)+'">'+i.options.map(o=>'<option value="'+esc(o.value)+'"'+(String(value(i)??'')===o.value?' selected':'')+' data-i18n-skip>'+esc(o.label)+'</option>').join('')+'</select></label>'
  :'<label><span data-i18n-skip>'+esc(i.label)+'</span><input type="'+(i.type==='number'?'number':'text')+'" data-app-input="'+esc(i.id)+'" value="'+esc(value(i)??'')+'"></label>').join('');
 const out=run?.output,status=run?(busy?ff(['이 컴퓨터에서 실행하는 중…','Running on this computer…']):(run.status==='failed'?ff(['실패 · ','Failed · ']):ff(['마지막 실행 ','Last run ']))+ago(run.at)+(run.elapsed_ms!==null&&run.elapsed_ms!==undefined?' · '+(run.elapsed_ms/1000).toFixed(1)+ff(['초','s']):'')):(busy?ff(['이 컴퓨터에서 실행하는 중…','Running on this computer…']):'');
 return '<div class="appcard" data-app-key="'+esc(key)+'" data-work="'+esc(post.work_id)+'" data-result="'+esc(post.result_id)+'" data-artifact="'+esc(a.artifact_id)+'" data-approved="'+Boolean(a.approved)+'" data-command="'+esc(a.command.join(' '))+'"><header><span data-i18n-skip>'+esc(a.title)+'</span><small>'+esc(ff(['앱','app']))+' · '+esc(a.label)+'</small></header>'
  +(fields?'<div class="fields">'+fields+'</div>':'')+'<div class="press">'+a.buttons.map((b,i)=>'<button type="button" data-app-run="'+esc(b.id)+'"'+(i===0?' class="main"':'')+(busy?' disabled':'')+' data-i18n-skip>'+esc(busy===b.id?ff(['실행 중…','Running…']):b.label)+'</button>').join('')+'</div>'
  +(a.approved?'':'<p class="note">'+esc(ff(['처음 누르면 실행할 명령을 확인해요: ','The first press shows the command to approve: ']))+'<code data-i18n-skip>'+esc(a.command.join(' '))+'</code></p>')
  +(out?.text?'<pre data-i18n-skip>'+esc(out.text)+'</pre>':'')+(out?.table?'<div class="grid"><table><thead><tr>'+out.table.header.map(h=>'<th data-i18n-skip>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+out.table.rows.map(r=>'<tr>'+r.map(v=>'<td data-i18n-skip>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'')
  +(run?.error?'<p class="note err" data-i18n-skip>'+esc(run.error)+'</p>':'')+(status?'<p class="note">'+esc(status)+'</p>':'')+'</div>'}
async function feedPress(path,body){const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'FEED_ACTION_FAILED');return data}
async function sendAnswers(workId){const work=feed?.works.find(w=>w.id===workId);if(!work||!answerReady(work))return;const picks=answerPicks[workId]||{},vals=answerValues[workId]||{},answers={};
 for(const q of work.questions){const o=q.options.find(x=>x.id===picks[q.id]);if(o)answers[q.id]=o.needs_value?o.id+': '+vals[q.id].trim():o.id}
 try{setMessage(ff(['답을 보내는 중…','Sending the answer…']));await feedPress('work/answer',{work_id:workId,revision:work.revision,answers,execute:true,cost_acknowledged:true});delete answerPicks[workId];delete answerValues[workId];setMessage(ff(['답을 보냈어요. 업무가 이어서 진행돼요.','Answer sent. The Work goes on.']))}
 catch(error){setMessage(ff(['답을 보내지 못했어요: ','Could not send the answer: '])+String(error.message||error))}loadFeed()}
async function pressApp(card,button){const key=card.dataset.appKey,body={work_id:card.dataset.work,result_id:card.dataset.result,artifact_id:card.dataset.artifact};
 if(card.dataset.approved!=='true'){if(!confirm(ff(['이 명령을 이 컴퓨터에서 실행할까요? 이 파일이 바뀌기 전까지 다시 묻지 않아요.','Run this command on this computer? You will not be asked again until this file changes.'])+'\\n\\n'+card.dataset.command))return;
  try{await feedPress('work/app/approve',body)}catch(error){setMessage(String(error.message||error));return}}
 appBusy.set(key,button);renderBoard();
 try{const run=await feedPress('work/app/run',{...body,button,inputs:appVals[key]||{}});if(run.status==='failed')setMessage(ff(['앱 실행이 실패했어요.','The app run failed.']))}
 catch(error){setMessage(ff(['앱을 실행하지 못했어요: ','Could not run the app: '])+String(error.message||error))}
 finally{appBusy.delete(key);await loadFeed()}}
function icsFile(node){const stamp=v=>new Date(v).toISOString().replace(/[-:]/g,'').replace(/\\.\\d+/,''),line=v=>String(v).replace(/[\\\\;,]/g,m=>'\\\\'+m).replace(/\\n/g,' ');
 const start=node.dataset.start,end=node.dataset.end||new Date(Date.parse(start)+3600000).toISOString();
 const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Agent Office//Feed//KO','BEGIN:VEVENT','UID:'+Date.now()+'@agent-office','DTSTAMP:'+stamp(new Date()),'DTSTART:'+stamp(start),'DTEND:'+stamp(end),'SUMMARY:'+line(node.dataset.name)].concat(node.dataset.place?['LOCATION:'+line(node.dataset.place)]:[]).concat(['END:VEVENT','END:VCALENDAR']).join('\\r\\n');
 const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/calendar'}));a.download='event.ics';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
app.addEventListener('change',event=>{const input=event.target.closest?.('[data-app-input]');if(!input||view!=='feed')return;const key=input.closest('.appcard').dataset.appKey;(appVals[key]||(appVals[key]={}))[input.dataset.appInput]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value});
app.addEventListener('input',event=>{const field=event.target.closest?.('[data-answer-value]');if(field){const id=field.dataset.answerValue;(answerValues[id]||(answerValues[id]={}))[field.dataset.q]=field.value;const work=feed?.works.find(w=>w.id===id),send=app.querySelector('[data-answer-send="'+CSS.escape(id)+'"]');if(work&&send)send.disabled=!answerReady(work);return}});
app.addEventListener('input',event=>{const input=event.target.closest?.('input[data-app-input]');if(!input||input.type==='checkbox'||view!=='feed')return;const key=input.closest('.appcard').dataset.appKey;(appVals[key]||(appVals[key]={}))[input.dataset.appInput]=input.type==='number'?Number(input.value):input.value});
// While the owner types in a card the feed does not repaint under them; it repaints when they leave the field.
app.addEventListener('focusout',()=>{if(feedDeferred){feedDeferred=false;setTimeout(()=>{if(!app.contains(document.activeElement)||!document.activeElement.matches('input,select,textarea'))renderBoard()},0)}});
app.addEventListener('click',async event=>{if(view!=='feed'||selected)return;const t=event.target;
 const approval=t.closest('[data-approval]');if(approval){const approve=approval.dataset.approval==='approve';if(approve&&!confirm(ff(['보이는 내용 그대로 한 번 제출할까요?','Submit exactly this, once?'])))return;approval.disabled=true;
  try{const done=await feedPress('work/approval',{task_id:approval.dataset.task,proposal_hash:approval.dataset.hash,decision:approve?'approve':'decline'});setMessage(approve?(done.resumed?ff(['승인했어요. 업무가 제출을 이어가요.','Approved. The Work goes on to submit.']):ff(['승인했어요. 업무를 열어 이어가 주세요.','Approved. Open the Work to go on.'])):ff(['취소했어요. 제출하지 않아요.','Declined. Nothing is submitted.']))}
  catch(error){setMessage(ff(['처리하지 못했어요: ','Could not do that: '])+String(error.message||error))}loadFeed();return}
 const pick=t.closest('[data-answer]');if(pick){const id=pick.dataset.answer;(answerPicks[id]||(answerPicks[id]={}))[pick.dataset.q]=pick.dataset.o;const work=feed?.works.find(w=>w.id===id),option=work?.questions.find(q=>q.id===pick.dataset.q)?.options.find(o=>o.id===pick.dataset.o);
  if(work?.questions?.length===1&&!option?.needs_value){sendAnswers(id);return}renderBoard();if(option?.needs_value)app.querySelector('[data-answer-value="'+CSS.escape(id)+'"][data-q="'+CSS.escape(pick.dataset.q)+'"]')?.focus();return}
 const send=t.closest('[data-answer-send]');if(send){sendAnswers(send.dataset.answerSend);return}
 // A reply goes into the Work conversation for the owner to send; a Work that takes no instruction now gets it copied instead.
 const reply=t.closest('[data-card-reply]');if(reply){markFeedSeen();const text=reply.dataset.text,id=reply.dataset.cardReply;openWork(id);chatDraft=text;chatFocus=true;
  setTimeout(async()=>{if(selected!==id||document.getElementById('chat-input'))return;chatFocus=false;try{await navigator.clipboard.writeText(text)}catch{}setMessage(ff(['이 업무는 지금 대화로 지시할 수 없어 문장을 복사했어요: ','This Work takes no instruction now; the text is copied: '])+text)},2500);return}
 const copy=t.closest('[data-card-copy]');if(copy){try{await navigator.clipboard.writeText(copy.dataset.cardCopy);setMessage(ff(['복사했어요.','Copied.']))}catch{setMessage(ff(['복사하지 못했어요.','Could not copy.']))}return}
 const ics=t.closest('[data-card-ics]');if(ics){icsFile(ics);return}
 const run=t.closest('[data-app-run]');if(run){pressApp(run.closest('.appcard'),run.dataset.appRun);return}});
`;}
