// Import by address: one field for a local folder, a repository or a server. The owner's own AI app analyses a folder
// or repository read-only; the candidates it reports become Works through the same paste-and-accept path as a draft
// written by another AI, and a server address opens server observation.
export const importAddressCss=`.addr-candidates{display:flex;flex-direction:column;gap:10px;margin:12px 0}.addr-card{border:1px solid var(--line);border-radius:var(--r);padding:10px 12px;display:grid;grid-template-columns:auto minmax(0,1fr);gap:4px 10px;align-items:start}.addr-card h4{margin:0;font:600 14px var(--sans)}.addr-card p{margin:2px 0;font-size:13px;overflow-wrap:anywhere}.addr-card small{font:11.5px var(--mono);color:var(--dim)}.addr-card .tag{font:11px var(--mono);border:1px solid var(--line2);border-radius:5px;padding:0 6px;margin-left:6px;color:var(--dim)}.addr-card .tag.run{color:var(--accent);border-color:var(--accent)}.addr-card details{grid-column:2}.addr-events{font:12px var(--mono);color:var(--dim);list-style:none;padding:0;margin:8px 0}.addr-events li{padding:2px 0;overflow-wrap:anywhere}`;

export function importAddressScript(){return `
let addressJob=null,addressReport=null,addressTimer=null,addressBusy=false;
const ad=pair=>pair[window.officeLang==='en'?1:0];
const ADDRESS_KINDS={run_in_office:['Office에서 실행','Run in Office'],observe:['원래 자리에서 관측','Watch where it runs'],skip:['건너뜀','Skip']};
const ADDRESS_WHERE={this_computer:['이 컴퓨터','this computer'],server:['서버','server'],github_actions:['GitHub Actions','GitHub Actions'],other_ai:['다른 AI 서비스','another AI service'],unknown:['확인 안 됨','unknown']};
const ADDRESS_ERRORS={IMPORT_ADDRESS_NOT_FOUND:['그 경로를 찾지 못했어요.','That path was not found.'],PROJECT_PATH_ABSOLUTE_REQUIRED:['/home/... 이나 C:\\\\... 처럼 전체 경로를 넣어 주세요.','Enter a full path such as /home/... or C:\\\\....'],IMPORT_CLIENT_REQUIRED:['분석을 맡을 Codex나 Claude Code가 없어요. 연결 및 설정에서 연결하세요.','No Codex or Claude Code to analyse it. Connect one in Connections & settings.'],CLIENT_RUN_DISABLED:['이 설치에서는 AI 앱 실행이 꺼져 있어요.','Running the AI app is turned off in this install.'],IMPORT_REPORT_MISSING:['AI 앱이 분석 결과 파일을 남기지 않았어요. 다시 시도해 보세요.','The AI app left no report. Try again.'],IMPORT_REPORT_INVALID:['분석 결과의 형식이 맞지 않았어요. 다시 시도해 보세요.','The report did not match the expected form. Try again.']};
const addressError=code=>ADDRESS_ERRORS[code]?ad(ADDRESS_ERRORS[code]):code;
async function addressPost(action,body){const response=await fetch('work/import/address/'+action,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(addressError(data.error)||'IMPORT_REQUEST_INVALID');return data}
const routes=document.querySelector('.import-routes');routes.insertAdjacentHTML('afterbegin','<button type="button" data-import-route="address" aria-pressed="false">주소로 가져오기</button>');routes.append(routes.querySelector('[data-import-route="external"]'));
document.getElementById('import-external').insertAdjacentHTML('beforebegin','<div id="import-address" class="import-pane" hidden><p class="muted">로컬 폴더, GitHub 저장소 또는 서버 주소를 넣으면 내 AI 앱이 읽기 전용으로 살펴보고 관제센터에 붙일 업무를 찾아요. 원본은 바꾸지 않아요.</p><label for="import-address-value">주소</label><input id="import-address-value" maxlength="2048" placeholder="예: /home/me/projects/bot · owner/repo · root@203.0.113.7"><label for="import-address-scope">찾을 범위 · 선택</label><textarea id="import-address-scope" rows="2" maxlength="2000" placeholder="예: 매일 도는 수집·알림만"></textarea><div class="row action-grid"><button type="button" id="import-address-start" class="primary">분석 시작</button></div><ul id="import-address-events" class="addr-events" aria-live="polite"></ul><div id="import-address-result"></div></div>');
function addressCardHtml(c,i){const checked=c.kind==='run_in_office';return '<div class="addr-card"><input type="checkbox" data-address-pick="'+i+'"'+(checked?' checked':'')+(c.kind==='skip'?' disabled':'')+' aria-label="'+esc(c.title)+'"><div><h4 data-i18n-skip>'+esc(c.title)+'<span class="tag'+(c.kind==='run_in_office'?' run':'')+'">'+esc(ad(ADDRESS_KINDS[c.kind]))+'</span></h4><p data-i18n-skip>'+esc(c.why)+'</p><small>'+esc(ad(ADDRESS_WHERE[c.where]||ADDRESS_WHERE.unknown))+(c.trigger?' · '+esc(c.trigger):'')+'</small>'+(c.kind==='observe'&&c.where==='server'&&c.server?'<p><button type="button" class="import-link" data-address-server="'+i+'">'+esc(ad(['서버 서비스로 관측하기','Watch it as server services']))+'</button></p>':'')+'</div>'+(c.evidence.length?'<details><summary>'+esc(ad(['근거','Evidence']))+' '+c.evidence.length+'</summary>'+c.evidence.map(e=>'<p data-i18n-skip><small>'+esc(e.file+(e.line?':'+e.line:''))+'</small> '+esc(e.note)+'</p>').join('')+'</details>':'')+'</div>'}
function renderAddress(){const events=document.getElementById('import-address-events'),box=document.getElementById('import-address-result');
events.innerHTML=addressJob&&addressJob.state==='running'?'<li>'+esc(ad(['분석 중 · ','Analysing · ']))+esc(addressJob.client==='claude'?'Claude Code':'Codex')+'</li>'+addressJob.events.map(e=>'<li data-i18n-skip>'+esc(e)+'</li>').join(''):'';
if(!addressReport){box.innerHTML=addressJob&&addressJob.state==='failed'?'<p role="alert">'+esc(addressError(addressJob.error))+'</p>':'';return}
const usable=addressReport.candidates.filter(c=>c.kind==='run_in_office').length;
box.innerHTML='<p data-i18n-skip>'+esc(addressReport.summary)+'</p>'+(addressReport.rejected.length?'<p class="muted">'+esc(ad(['형식이 맞지 않아 뺀 후보 ','Candidates left out for their form: ']))+addressReport.rejected.length+'</p>':'')+'<div class="addr-candidates">'+addressReport.candidates.map(addressCardHtml).join('')+'</div>'+(usable?'<div class="row action-grid"><button type="button" id="import-address-attach" class="primary">'+esc(ad(['선택한 업무 만들기','Create the selected Works']))+'</button></div><p class="muted">'+esc(ad(['만든 업무는 내 AI 앱이 원래 절차대로 실행해요. 예약은 업무 화면에서 확인할 수 있어요.','The Works run on your AI app with the original steps. Check their schedule on the Work screen.']))+'</p>':'')}
async function pollAddress(){if(!addressJob)return;try{addressJob=await addressPost('status',{job_id:addressJob.job_id});if(addressJob.state==='done')addressReport=addressJob.report;renderAddress();if(addressJob.state==='running')addressTimer=setTimeout(pollAddress,2000);else setMessage(addressJob.state==='done'?ad(['분석을 마쳤어요. 붙일 업무를 고르세요.','Analysis finished. Choose what to attach.']):addressError(addressJob.error))}catch(error){setMessage(String(error.message||error))}}
document.getElementById('import-address-start').onclick=async()=>{if(addressBusy)return;const address=document.getElementById('import-address-value').value.trim();if(!address){setMessage(ad(['주소를 넣어 주세요.','Enter an address.']));return}
addressBusy=true;clearTimeout(addressTimer);addressJob=null;addressReport=null;renderAddress();
try{const scope=document.getElementById('import-address-scope').value.trim(),r=await addressPost('start',{address,...(scope?{scope}:{}),language:window.officeLang==='en'?'en':'ko'});
if(r.kind==='server'){setImportRoute('server');const d=document.querySelector('#import-server details');if(d)d.open=true;document.getElementById('server-host').value=r.server.host;document.getElementById('server-user').value=r.server.user;document.getElementById('server-port').value=String(r.server.port);setMessage(ad(['서버 주소예요. 연결 정보를 저장하고 서비스 찾기를 누르세요.','This is a server. Save the connection and find its services.']));return}
addressJob={job_id:r.job_id,client:r.client,state:'running',events:[]};renderAddress();setMessage(ad(['내 AI 앱이 읽기 전용으로 살펴보고 있어요. 몇 분 걸릴 수 있어요.','Your AI app is reading it, read-only. This can take a few minutes.']));addressTimer=setTimeout(pollAddress,1500)}
catch(error){setMessage(String(error.message||error))}finally{addressBusy=false}};
document.getElementById('import-address-result').addEventListener('click',async event=>{const server=event.target.closest('[data-address-server]');
if(server){const c=addressReport.candidates[Number(server.dataset.addressServer)];setImportRoute('server');const d=document.querySelector('#import-server details');if(d)d.open=true;document.getElementById('server-host').value=c.server.host;if(c.server.user)document.getElementById('server-user').value=c.server.user;return}
if(!event.target.closest('#import-address-attach')||addressBusy)return;
const picks=[...document.querySelectorAll('[data-address-pick]:checked')].map(n=>addressReport.candidates[Number(n.dataset.addressPick)]).filter(c=>c.kind==='run_in_office'&&c.draft);
if(!picks.length){setMessage(ad(['만들 업무를 하나 이상 고르세요.','Choose at least one Work to create.']));return}
addressBusy=true;const made=[];
try{for(const c of picks){const post=async(path,body)=>{const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(data.error||path);return data};
  const pasted=await post('work/import/paste',{text:JSON.stringify(c.draft)}),accepted=await post('work/import/accept',{import_id:pasted.import_id,mode:'migrate'});made.push(accepted.work_id)}
  setMessage(ad(['업무 ','Created '])+made.length+ad(['개를 만들었어요.',' Works.']));importOpen=false;showBoard()}
catch(error){setMessage((made.length?ad(['업무 ','Created '])+made.length+ad(['개를 만든 뒤 멈췄어요: ',' Works, then stopped: ']):'')+String(error.message||error))}finally{addressBusy=false}});
`;}
