// Server observation in the Control Center: the import pane that registers a server and links groups of its services
// as Works, the board card summary, and the read-only detail of one watched group.
export const serverWatchCss=`.server-groups{display:flex;flex-direction:column;gap:12px;margin:12px 0}.server-group{border:1px solid var(--line);border-radius:var(--r);padding:10px 12px;margin:0}.server-group legend{padding:0 4px}.server-group legend input{font:600 13px var(--sans);width:min(320px,100%)}
.sg-unit{display:grid;grid-template-columns:auto 8px minmax(0,1fr) auto;gap:8px;align-items:center;padding:4px 0;font:12.5px var(--mono)}.sg-unit small{color:var(--dim);display:block}.sg-unit select{font:11.5px var(--mono);max-width:160px}
.sdot{width:8px;height:8px;border-radius:50%;background:var(--line2);display:inline-block}.sdot.ok{background:var(--ok)}.sdot.problem{background:var(--human)}.sdot.off{background:var(--faint)}
.server-table{width:100%;border-collapse:collapse;font-size:13px}.server-table th{font:500 10.5px var(--mono);letter-spacing:.1em;text-transform:uppercase;color:var(--dim);text-align:left;padding:8px;border-bottom:1px solid var(--line)}.server-table td{padding:8px;border-bottom:1px solid var(--line);vertical-align:top;overflow-wrap:anywhere}.server-table td.mono{font:12px var(--mono)}.server-table tr.u-problem td{color:var(--human)}.server-wrap{overflow-x:auto}
.server-units>header{display:flex;justify-content:space-between;align-items:center;gap:10px}`;

export function serverWatchScript(){return `
let serverBusy=false,serverTargets=[],serverFound=null,serverGroups=[];
const sv=pair=>pair[window.officeLang==='en'?1:0];
const SERVER_NOTES={failed:['실패','failed'],stopped:['멈춤','stopped'],last_run_failed:['마지막 실행 실패','last run failed'],timer_inactive:['타이머 꺼짐','timer off'],unhealthy:['상태 이상','unhealthy'],exited:['종료됨','exited'],not_found:['찾을 수 없음','not found']};
const SERVER_KINDS={service:['서비스','service'],timer:['예약','timer'],container:['컨테이너','container']};
const SERVER_ERRORS={SERVER_CONNECTION_FAILED:['서버에 접속하지 못했어요. 이 컴퓨터에서 SSH 키로 접속되는지, 호스트 키가 등록돼 있는지 확인하세요.','Could not connect. Check that this computer can SSH in with a key and that the host key is known.'],SERVER_CONNECTION_TIMEOUT:['서버 응답이 25초 안에 오지 않았어요.','The server did not answer within 25 seconds.'],SERVER_SSH_UNAVAILABLE:['이 컴퓨터에서 ssh를 실행하지 못했어요.','ssh could not be started on this computer.'],SERVER_RESPONSE_INVALID:['서버 응답을 읽지 못했어요. systemd 246 이상이 필요해요.','Could not read the answer. systemd 246 or later is needed.'],SERVER_UNIT_IN_TWO_GROUPS:['한 서비스는 한 묶음에만 넣을 수 있어요.','A service can be in one group only.'],SERVER_TARGET_NOT_FOUND:['서버 연결을 찾지 못했어요.','The server connection was not found.']};
function serverNote(n){return n&&SERVER_NOTES[n]?sv(SERVER_NOTES[n]):''}
function serverWhen(sec){if(!sec)return '';const d=new Date(sec*1000);return (new Date().toDateString()===d.toDateString()?'':(d.getMonth()+1)+'/'+d.getDate()+' ')+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
async function serverPost(action,body={}){const response=await fetch('work/server/'+action,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(SERVER_ERRORS[data.error]?sv(SERVER_ERRORS[data.error]):data.error||'SERVER_REQUEST_INVALID');return data}
async function serverDo(fn){if(serverBusy)return;serverBusy=true;try{await fn()}catch(error){setMessage(String(error.message||error))}finally{serverBusy=false}}
document.querySelector('.import-routes').insertAdjacentHTML('beforeend','<button type="button" data-import-route="server" aria-pressed="false">서버 서비스</button>');
document.getElementById('import-remote').insertAdjacentHTML('afterend','<div id="import-server" class="import-pane" hidden><p>내 리눅스 서버의 systemd 서비스·예약 작업·Docker 컨테이너 상태를 읽기 전용으로 지켜봐요. 서비스를 켜거나 끄지 않아요.</p><label for="server-target">연결된 서버</label><select id="server-target"></select><button type="button" id="server-discover">서비스 찾기</button><details><summary>서버 연결 추가</summary><p class="muted">이 컴퓨터에서 SSH 키로 접속할 수 있어야 해요(호스트 키 등록 포함). 비밀번호는 여기에 입력하지 않아요.</p><label for="server-name">연결 이름</label><input id="server-name" maxlength="80" placeholder="예: 내 서버"><label for="server-host">서버 주소</label><input id="server-host" maxlength="253" placeholder="서버 IP 또는 호스트 이름"><label for="server-user">SSH 사용자</label><input id="server-user" maxlength="32"><label for="server-port">SSH 포트</label><input id="server-port" type="number" min="1" max="65535" value="22"><button type="button" id="server-register">연결 정보 저장</button></details><div id="server-found"></div></div>');
function serverOptions(){return serverTargets.map(t=>'<option value="'+esc(t.id)+'">'+esc(t.name+' · '+t.host)+'</option>').join('')}
async function serverLoadTargets(){await serverDo(async()=>{serverTargets=await serverPost('targets');document.getElementById('server-target').innerHTML=serverOptions();setMessage(serverTargets.length?sv(['서버를 고르고 서비스 찾기를 누르세요.','Choose a server and find its services.']):sv(['먼저 서버 연결을 추가하세요.','Add a server connection first.']))})}
document.getElementById('server-register').onclick=()=>serverDo(async()=>{const value=id=>document.getElementById(id).value.trim(),r=await serverPost('register',{name:value('server-name'),host:value('server-host'),user:value('server-user'),port:Number(value('server-port'))});serverTargets=await serverPost('targets');document.getElementById('server-target').innerHTML=serverOptions();document.getElementById('server-target').value=r.id;setMessage(sv(['연결 정보를 저장했어요. 서비스 찾기로 접속을 확인하세요.','Saved. Find services to check the connection.']))});
function renderServerFound(){const box=document.getElementById('server-found');if(!serverFound){box.innerHTML='';return}const units=new Map(serverFound.units.map(u=>[u.id,u])),names=serverGroups.map(g=>g.name);
box.innerHTML='<p class="muted">'+esc(sv(['서비스를 묶음으로 나눴어요. 묶음 하나가 보드의 카드 하나예요. 이름을 고치고, 서비스를 다른 묶음으로 옮기거나 빼세요.','Services are grouped. Each group becomes one card. Rename groups, move services or leave them out.']))+(serverFound.watched.length?' '+esc(sv(['이미 관측 중인 서비스 ','Already watched: '])+serverFound.watched.length)+sv(['개는 빼고 보여요.',' (not shown).']):'')+'</p><div class="server-groups">'+serverGroups.map((g,gi)=>'<fieldset class="server-group"><legend><input class="sg-name" data-g="'+gi+'" maxlength="80" value="'+esc(g.name)+'" aria-label="'+esc(sv(['묶음 이름','Group name']))+'"></legend>'+g.units.map(id=>{const u=units.get(id)||{id,kind:'service',state:'problem'};return '<label class="sg-unit"><input type="checkbox" data-pick="'+esc(id)+'"'+(g.skip?.includes(id)?'':' checked')+'><i class="sdot '+esc(u.state)+'"></i><span>'+esc(id)+'<small>'+esc(sv(SERVER_KINDS[u.kind]||['','']))+(u.note?' · '+esc(serverNote(u.note)):'')+'</small></span><select data-move="'+esc(id)+'" aria-label="'+esc(sv(['옮길 묶음','Move to group']))+'">'+names.map((n,ni)=>'<option value="'+ni+'"'+(ni===gi?' selected':'')+'>'+esc(n)+'</option>').join('')+'<option value="add-group">'+esc(sv(['새 묶음','New group']))+'</option></select></label>'}).join('')+'</fieldset>').join('')+'</div><button type="button" id="server-link" class="primary">'+esc(sv(['선택한 묶음 관측 시작','Start watching the selected groups']))+'</button>'}
document.getElementById('server-discover').onclick=()=>serverDo(async()=>{const id=document.getElementById('server-target').value;if(!id)throw Error(sv(['먼저 서버 연결을 고르세요.','Choose a server connection first.']));setMessage(sv(['서버에서 서비스 상태를 읽고 있어요. 아무것도 바꾸지 않아요.','Reading service states from the server. Nothing is changed.']));serverFound=await serverPost('discover',{target_id:id});serverFound.target_id=id;serverGroups=serverFound.groups.map(g=>({name:g.name,units:[...g.units],skip:[]}));renderServerFound();setMessage(sv(['서비스 ','Found '])+serverFound.units.length+sv(['개를 찾았어요.',' services.']))});
document.getElementById('server-found').addEventListener('input',event=>{const n=event.target.closest('.sg-name');if(n)serverGroups[Number(n.dataset.g)].name=n.value});
document.getElementById('server-found').addEventListener('change',event=>{const pick=event.target.closest('[data-pick]'),move=event.target.closest('[data-move]');
if(pick){const g=serverGroups.find(x=>x.units.includes(pick.dataset.pick));if(g)g.skip=pick.checked?g.skip.filter(u=>u!==pick.dataset.pick):[...g.skip,pick.dataset.pick];return}
if(move){const id=move.dataset.move,from=serverGroups.find(x=>x.units.includes(id));from.units=from.units.filter(u=>u!==id);if(move.value==='add-group')serverGroups.push({name:id.replace(/\\.(service|timer)$/,''),units:[id],skip:[]});else serverGroups[Number(move.value)].units.push(id);serverGroups=serverGroups.filter(g=>g.units.length);renderServerFound()}});
document.getElementById('server-found').addEventListener('click',event=>{if(!event.target.closest('#server-link'))return;serverDo(async()=>{const groups=serverGroups.map(g=>({name:g.name.trim(),units:g.units.filter(u=>!g.skip.includes(u))})).filter(g=>g.name&&g.units.length);if(!groups.length)throw Error(sv(['관측할 서비스를 하나 이상 고르세요.','Pick at least one service.']));const r=await serverPost('link',{target_id:serverFound.target_id,acknowledged:true,groups});serverFound=null;renderServerFound();importOpen=false;setMessage(sv(['업무 ','Created '])+r.work_ids.length+sv(['개로 관측을 시작했어요. 정상인 묶음은 반복 실행 칸에 있어요.',' Works. Healthy groups are in Recurring.']));showBoard()})});
// The board card of a server Work: one dot for its health and a short summary in place of the cycle stages.
function serverTrailHtml(w){const s=w.server;if(!s)return '';const c=s.counts||{service:0,timer:0,container:0},parts=['service','timer','container'].filter(k=>c[k]).map(k=>sv(SERVER_KINDS[k])+' '+c[k]);
const text=s.problems.length?s.problems.map(p=>p.id+' '+serverNote(p.note)).join(', '):w.status==='service_unreachable'?sv(['서버 연결 안 됨','Server unreachable']):w.status==='service_unobserved'?sv(['아직 확인 전','Not checked yet']):parts.join(' · ')+(s.off?' · '+sv(['꺼 둠 ','off '])+s.off:'');
return '<span class="trail"><i class="'+(s.problems.length||w.status==='service_unreachable'?'problem':w.status==='service_ok'?'done':'pending')+'"></i><em data-i18n-skip>'+esc(text)+(s.stale&&s.observed_at?' · '+esc(sv(['확인 지연','check delayed'])):'')+'</em></span>'}
function renderServerDetail(){const d=detail,s=d.server,rows=[...s.units].sort((a,b)=>(a.state==='problem'?0:a.state==='ok'?1:2)-(b.state==='problem'?0:b.state==='ok'?1:2)||a.id.localeCompare(b.id));
app.innerHTML='<button type="button" class="back" id="back">← 업무 목록</button><section class="work-head"><div><span class="state">'+esc(labels[d.run_status]||d.run_status)+'</span><h2 data-i18n-skip>'+esc(d.title)+'</h2><p data-i18n-skip>'+esc(s.target_name+' · '+s.host)+'</p><p class="muted">'+esc(sv(['마지막 확인 ','Last checked ']))+esc(s.observed_at?serverWhen(Date.parse(s.observed_at)/1000):sv(['아직 없음','never']))+(s.stale?' · '+esc(sv(['확인이 늦어지고 있어요','checks are delayed'])):'')+'</p>'+(s.error?'<p role="alert">'+esc(SERVER_ERRORS[s.error]?sv(SERVER_ERRORS[s.error]):s.error)+'</p>':'')+'</div></section>'
+'<section class="panel server-units"><header><h3>'+esc(sv(['서비스','Services']))+'</h3><button type="button" id="server-refresh">'+esc(sv(['지금 확인','Check now']))+'</button></header><div class="server-wrap"><table class="server-table"><thead><tr><th></th><th>'+esc(sv(['이름','Name']))+'</th><th>'+esc(sv(['종류','Kind']))+'</th><th>'+esc(sv(['상태','State']))+'</th><th>'+esc(sv(['시작 · 마지막 실행','Started · last run']))+'</th><th>'+esc(sv(['다음 실행','Next run']))+'</th><th>'+esc(sv(['재시작','Restarts']))+'</th></tr></thead><tbody>'
+rows.map(u=>'<tr class="u-'+esc(u.state)+'"><td><i class="sdot '+esc(u.state)+'"></i></td><td class="mono" data-i18n-skip>'+esc(u.id)+(u.description&&u.kind!=='container'?'<br><small class="muted">'+esc(u.description)+'</small>':'')+'</td><td>'+esc(sv(SERVER_KINDS[u.kind]||['','']))+'</td><td class="mono" data-i18n-skip>'+esc(u.note?serverNote(u.note):u.state==='off'?sv(['꺼 둠','off']):[u.active,u.sub].filter(Boolean).join(' · '))+'</td><td class="mono">'+esc(serverWhen(u.kind==='timer'?u.last_run:u.since))+'</td><td class="mono">'+esc(serverWhen(u.next_run))+'</td><td class="mono">'+esc(u.kind==='service'?String(u.restarts):'')+'</td></tr>').join('')+'</tbody></table></div><p class="muted">'+esc(sv(['Office는 서버에서 상태를 읽기만 해요. 서비스를 켜거나 끄거나 다시 시작하지 않아요. 약 2분마다 확인해요.','Office only reads states on the server. It never starts, stops or restarts a service. It checks about every two minutes.']))+'</p></section>'
+'<section class="panel"><h3>'+esc(sv(['변화 기록','Changes']))+'</h3>'+((d.activity||[]).filter(a=>String(a.kind).startsWith('server.')).slice(-20).reverse().map(a=>'<p><span class="muted">'+esc(serverWhen(Date.parse(a.created_at)/1000))+'</span> '+esc(a.summary)+'</p>').join('')||'<p class="muted">'+esc(sv(['아직 바뀐 것이 없어요.','No changes yet.']))+'</p>')+'</section>';
document.getElementById('back').onclick=showBoard;document.getElementById('server-refresh').onclick=()=>serverDo(async()=>{const id=d.id;setMessage(sv(['서버 상태를 읽고 있어요.','Reading the server state.']));const value=await serverPost('refresh',{work_id:id});if(selected!==id)return;detail={...detail,...value};renderDetail();setMessage(value.server.error?sv(['서버에 접속하지 못했어요. 마지막 기록을 보여 줘요.','Could not reach the server. Showing the last record.']):sv(['방금 확인했어요.','Checked just now.']))})}
`;}
