// Server observation in the Control Center: the import pane that registers a server and links groups of its services
// as Works, the board card summary, and the read-only detail of one watched group.
export const serverWatchCss=`.server-mode{display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin:8px 0 0;font:12px var(--mono);color:var(--dim)}.server-mode button{min-height:32px;padding:0 12px;border-radius:999px;font:12px var(--mono)}.server-mode button[aria-pressed="true"]{border-color:var(--accent);color:var(--accent);background:var(--acc-a)}.link-btn{border:0;background:none;padding:0;min-height:0;color:var(--code);text-decoration:underline;font:12px var(--sans)}
.server-groups{display:flex;flex-direction:column;gap:12px;margin:12px 0}.server-group{border:1px solid var(--line);border-radius:var(--r);padding:10px 12px;margin:0}.server-group legend{padding:0 4px}.server-group legend input{font:600 13px var(--sans);width:min(320px,100%)}
.sg-unit{display:grid;grid-template-columns:auto 8px minmax(0,1fr) auto;gap:8px;align-items:center;padding:4px 0;font:12.5px var(--mono)}.sg-unit small{color:var(--dim);display:block}.sg-unit select{font:11.5px var(--mono);max-width:160px}.server-group.watched legend{font:600 13px var(--sans)}.sg-head{font:500 10.5px var(--mono);letter-spacing:.1em;text-transform:uppercase;color:var(--dim);margin:16px 0 0}
.sdot{width:8px;height:8px;border-radius:50%;background:var(--line2);display:inline-block}.sdot.ok{background:var(--ok)}.sdot.problem{background:var(--human)}.sdot.off{background:var(--faint)}
/* Each cell stays on one line; a table wider than the screen scrolls sideways in .server-wrap. */
.server-table{width:100%;min-width:max-content;border-collapse:collapse;font-size:13px}.server-table th{font:500 10.5px var(--mono);letter-spacing:.1em;text-transform:uppercase;color:var(--dim);text-align:left;padding:8px;border-bottom:1px solid var(--line)}.server-table td{padding:8px;border-bottom:1px solid var(--line);vertical-align:top;white-space:nowrap}.server-table td.desc{color:var(--dim)}.server-table td.mono{font:12px var(--mono)}.server-table tr.u-problem td{color:var(--human)}.server-wrap{overflow-x:auto}
.server-units>header{display:flex;justify-content:space-between;align-items:center;gap:10px}.server-form{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:8px;margin-top:10px}.server-form .wide{grid-column:1/-1}.server-form label{font-size:12px;color:var(--dim)}.server-targets label{display:flex;gap:8px;align-items:center;padding:3px 0}`;

export function serverWatchScript(){return `
let serverBusy=false,serverTargets=[],serverFound=null,serverGroups=[];
const sv=pair=>pair[window.officeLang==='en'?1:0];
const SERVER_NOTES={no_recent_activity:['최근 기록 없음','no recent activity'],failed:['실패','failed'],stopped:['멈춤','stopped'],last_run_failed:['마지막 실행 실패','last run failed'],timer_inactive:['타이머 꺼짐','timer off'],unhealthy:['상태 이상','unhealthy'],exited:['종료됨','exited'],not_found:['찾을 수 없음','not found']};
const SERVER_KINDS={service:['서비스','service'],timer:['예약','timer'],container:['컨테이너','container']};
const SERVER_ERRORS={SESSION_BUSY:['이 서버 대화가 아직 앞 지시를 처리하고 있어요. 답변이 오면 다시 보내 주세요.','This conversation is still working on the last message. Send again once it replies.'],CLIENT_NOT_INSTALLED:['Codex나 Claude Code가 이 컴퓨터에 없어요. 연결 및 설정에서 AI 앱을 설치해 주세요.','Neither Codex nor Claude Code is installed here. Install one in Connections & settings.'],CLIENT_RUN_DISABLED:['이 설치에서는 AI 앱 실행이 꺼져 있어요.','Running the AI app is turned off in this install.'],SERVER_CONNECTION_FAILED:['서버에 접속하지 못했어요. 이 컴퓨터에서 SSH 키로 접속되는지, 호스트 키가 등록돼 있는지 확인하세요.','Could not connect. Check that this computer can SSH in with a key and that the host key is known.'],SERVER_CONNECTION_TIMEOUT:['서버 응답이 25초 안에 오지 않았어요.','The server did not answer within 25 seconds.'],SERVER_SSH_UNAVAILABLE:['이 컴퓨터에서 ssh를 실행하지 못했어요.','ssh could not be started on this computer.'],SERVER_RESPONSE_INVALID:['서버 응답을 읽지 못했어요. systemd 246 이상이 필요해요.','Could not read the answer. systemd 246 or later is needed.'],SERVER_UNIT_IN_TWO_GROUPS:['한 서비스는 한 묶음에만 넣을 수 있어요.','A service can be in one group only.'],SERVER_TARGET_NOT_FOUND:['서버 연결을 찾지 못했어요.','The server connection was not found.']};
function serverNote(n){return n&&SERVER_NOTES[n]?sv(SERVER_NOTES[n]):''}
function serverWhen(sec){if(!sec)return '';const d=new Date(sec*1000);return (new Date().toDateString()===d.toDateString()?'':(d.getMonth()+1)+'/'+d.getDate()+' ')+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
async function serverPost(action,body={}){const response=await fetch('work/server/'+action,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(SERVER_ERRORS[data.error]?sv(SERVER_ERRORS[data.error]):data.error||'SERVER_REQUEST_INVALID');return data}
async function serverDo(fn){if(serverBusy)return;serverBusy=true;try{await fn()}catch(error){setMessage(String(error.message||error))}finally{serverBusy=false}}
document.querySelector('.import-routes').insertAdjacentHTML('beforeend','<button type="button" data-import-route="server" aria-pressed="false">서버 서비스</button>');
document.getElementById('import-remote').insertAdjacentHTML('afterend','<div id="import-server" class="import-pane" hidden><p>내 리눅스 서버의 systemd 서비스·예약 작업·Docker 컨테이너 상태를 읽기 전용으로 지켜봐요. 서비스를 켜거나 끄지 않아요.</p><label for="server-target">연결된 서버</label><select id="server-target"></select><button type="button" id="server-discover">서비스 찾기</button><details id="server-edit" hidden><summary>서버 설정</summary><p class="muted">고른 서버의 이름과 접속 정보예요. 이 서버를 지켜보는 업무 모두에 적용돼요.</p><label for="server-edit-name">연결 이름</label><input id="server-edit-name" maxlength="80"><label for="server-edit-host">서버 주소</label><input id="server-edit-host" maxlength="253"><label for="server-edit-user">SSH 사용자</label><input id="server-edit-user" maxlength="32"><label for="server-edit-port">SSH 포트</label><input id="server-edit-port" type="number" min="1" max="65535"><button type="button" id="server-edit-save">설정 저장</button></details><details><summary>서버 연결 추가</summary><p class="muted">이 컴퓨터에서 SSH 키로 접속할 수 있어야 해요(호스트 키 등록 포함). 비밀번호는 여기에 입력하지 않아요.</p><label for="server-name">연결 이름</label><input id="server-name" maxlength="80" placeholder="예: 내 서버"><label for="server-host">서버 주소</label><input id="server-host" maxlength="253" placeholder="서버 IP 또는 호스트 이름"><label for="server-user">SSH 사용자</label><input id="server-user" maxlength="32"><label for="server-port">SSH 포트</label><input id="server-port" type="number" min="1" max="65535" value="22"><button type="button" id="server-register">연결 정보 저장</button></details><div id="server-found"></div></div>');
function serverOptions(){return serverTargets.map(t=>'<option value="'+esc(t.id)+'">'+esc(t.name)+'</option>').join('')}
function serverFillEdit(){const t=serverTargets.find(x=>x.id===document.getElementById('server-target').value),box=document.getElementById('server-edit');box.hidden=!t;if(!t)return;
for(const [id,key] of [['server-edit-name','name'],['server-edit-host','host'],['server-edit-user','user'],['server-edit-port','port']])document.getElementById(id).value=String(t[key]??'')}
document.getElementById('server-target').addEventListener('change',serverFillEdit);
document.getElementById('server-edit-save').onclick=()=>serverDo(async()=>{const value=id=>document.getElementById(id).value.trim(),id=document.getElementById('server-target').value;
await serverPost('update',{target_id:id,name:value('server-edit-name'),host:value('server-edit-host'),user:value('server-edit-user'),port:Number(value('server-edit-port'))});
serverTargets=await serverPost('targets');document.getElementById('server-target').innerHTML=serverOptions();document.getElementById('server-target').value=id;serverFillEdit();setMessage(sv(['서버 설정을 저장했어요.','Server settings saved.']))});
async function serverLoadTargets(){await serverDo(async()=>{serverTargets=await serverPost('targets');document.getElementById('server-target').innerHTML=serverOptions();serverFillEdit();setMessage(serverTargets.length?sv(['서버를 고르고 서비스 찾기를 누르세요.','Choose a server and find its services.']):sv(['먼저 서버 연결을 추가하세요.','Add a server connection first.']))})}
document.getElementById('server-register').onclick=()=>serverDo(async()=>{const value=id=>document.getElementById(id).value.trim(),r=await serverPost('register',{name:value('server-name'),host:value('server-host'),user:value('server-user'),port:Number(value('server-port'))});serverTargets=await serverPost('targets');document.getElementById('server-target').innerHTML=serverOptions();document.getElementById('server-target').value=r.id;serverFillEdit();setMessage(sv(['연결 정보를 저장했어요. 서비스 찾기로 접속을 확인하세요.','Saved. Find services to check the connection.']))});
function serverUnitRow(u){return '<i class="sdot '+esc(u.state)+'"></i><span>'+esc(u.id)+'<small>'+esc(sv(SERVER_KINDS[u.kind]||['','']))+(u.note?' · '+esc(serverNote(u.note)):'')+'</small></span>'}
function renderServerFound(){const box=document.getElementById('server-found');if(!serverFound){box.innerHTML='';return}const units=new Map(serverFound.units.map(u=>[u.id,u])),names=serverGroups.map(g=>g.name);
const watched=(serverFound.watched_works||[]).map(w=>'<fieldset class="server-group watched"><legend>'+esc(w.title)+'</legend>'+w.units.map(id=>'<div class="sg-unit"><span></span>'+serverUnitRow(units.get(id)||{id,kind:'service',state:'problem'})+'</div>').join('')+'</fieldset>').join('');
box.innerHTML=(serverGroups.length?'<p class="muted">'+esc(sv(['새로 찾은 서비스를 묶음으로 나눴어요. 묶음 하나가 보드의 카드 하나예요. 이름을 고치고, 서비스를 다른 묶음으로 옮기거나 빼세요.','New services are grouped. Each group becomes one card. Rename groups, move services or leave them out.']))+'</p><div class="server-groups">'+serverGroups.map((g,gi)=>'<fieldset class="server-group"><legend><input class="sg-name" data-g="'+gi+'" maxlength="80" value="'+esc(g.name)+'" aria-label="'+esc(sv(['묶음 이름','Group name']))+'"></legend>'+g.units.map(id=>{const u=units.get(id)||{id,kind:'service',state:'problem'};return '<label class="sg-unit"><input type="checkbox" data-pick="'+esc(id)+'"'+(g.skip?.includes(id)?'':' checked')+'>'+serverUnitRow(u)+'<select data-move="'+esc(id)+'" aria-label="'+esc(sv(['옮길 묶음','Move to group']))+'">'+names.map((n,ni)=>'<option value="'+ni+'"'+(ni===gi?' selected':'')+'>'+esc(n)+'</option>').join('')+'<option value="add-group">'+esc(sv(['새 묶음','New group']))+'</option></select></label>'}).join('')+'</fieldset>').join('')+'</div><button type="button" id="server-link" class="primary">'+esc(sv(['선택한 묶음 관측 시작','Start watching the selected groups']))+'</button>':'<p class="muted">'+esc(sv(['새로 관측할 서비스가 없어요. 찾은 서비스는 모두 아래 업무에서 관측 중이에요.','No new services. Every service found is watched by the Works below.']))+'</p>')+(watched?'<h3 class="sg-head">'+esc(sv(['이미 관측 중','Already watched']))+'</h3><div class="server-groups">'+watched+'</div>':'')}
document.getElementById('server-discover').onclick=()=>serverDo(async()=>{const id=document.getElementById('server-target').value;if(!id)throw Error(sv(['먼저 서버 연결을 고르세요.','Choose a server connection first.']));setMessage(sv(['서버에서 서비스 상태를 읽고 있어요. 아무것도 바꾸지 않아요.','Reading service states from the server. Nothing is changed.']));serverFound=await serverPost('discover',{target_id:id});serverFound.target_id=id;serverGroups=serverFound.groups.map(g=>({name:g.name,units:[...g.units],skip:[]}));renderServerFound();const fresh=serverGroups.reduce((n,g)=>n+g.units.length,0);setMessage(sv(['서비스 ','Found '])+serverFound.units.length+sv(['개를 찾았어요 · 새로 고를 서비스 ',' services · '])+fresh+sv(['개',' new']))});
document.getElementById('server-found').addEventListener('input',event=>{const n=event.target.closest('.sg-name');if(n)serverGroups[Number(n.dataset.g)].name=n.value});
document.getElementById('server-found').addEventListener('change',event=>{const pick=event.target.closest('[data-pick]'),move=event.target.closest('[data-move]');
if(pick){const g=serverGroups.find(x=>x.units.includes(pick.dataset.pick));if(g)g.skip=pick.checked?g.skip.filter(u=>u!==pick.dataset.pick):[...g.skip,pick.dataset.pick];return}
if(move){const id=move.dataset.move,from=serverGroups.find(x=>x.units.includes(id));from.units=from.units.filter(u=>u!==id);if(move.value==='add-group')serverGroups.push({name:id.replace(/\\.(service|timer)$/,''),units:[id],skip:[]});else serverGroups[Number(move.value)].units.push(id);serverGroups=serverGroups.filter(g=>g.units.length);renderServerFound()}});
document.getElementById('server-found').addEventListener('click',event=>{if(!event.target.closest('#server-link'))return;serverDo(async()=>{const groups=serverGroups.map(g=>({name:g.name.trim(),units:g.units.filter(u=>!g.skip.includes(u))})).filter(g=>g.name&&g.units.length);if(!groups.length)throw Error(sv(['관측할 서비스를 하나 이상 고르세요.','Pick at least one service.']));const r=await serverPost('link',{target_id:serverFound.target_id,acknowledged:true,groups});serverFound=null;renderServerFound();importOpen=false;setMessage(sv(['업무 ','Created '])+r.work_ids.length+sv(['개로 관측을 시작했어요. 정상인 묶음은 반복 실행 칸에 있어요.',' Works. Healthy groups are in Recurring.']));showBoard()})});
// The board card of a server Work: one dot for its health and a short summary in place of the cycle stages.
function serverTrailHtml(w){const s=w.server;if(!s)return '';
return '<span class="trail"><i class="'+(s.problems.length||w.status==='service_unreachable'?'problem':w.status==='service_ok'||w.status==='service_standby'?'done':'pending')+'"></i><em data-i18n-skip>'+esc(serverSummary(w))+(s.stale&&s.observed_at?' · '+esc(sv(['확인 지연','check delayed'])):'')+'</em></span>'}
// A server Work in one line: its problems, else what it watches.
function serverSummary(w){const s=w.server,c=s.counts||{service:0,timer:0,container:0},parts=['service','timer','container'].filter(k=>c[k]).map(k=>sv(SERVER_KINDS[k])+' '+c[k]);
return s.problems.length?s.problems.map(p=>p.id+' '+serverNote(p.note)).join(', '):w.status==='service_unreachable'?sv(['서버 연결 안 됨','Server unreachable']):w.status==='service_unobserved'?sv(['아직 확인 전','Not checked yet']):parts.join(' · ')+(s.off?' · '+sv(['꺼 둠 ','off '])+s.off:'')}

// Where a state change is sent: the Work's own delivery destinations, the same setting results use.
function serverNoticeHtml(d){const targets=d.delivery_targets||[],chosen=new Set(d.delivery?.target_ids||[]);
return '<section class="panel server-targets"><h3>'+esc(sv(['알림 받을 곳','Notices go to']))+'</h3><p class="muted">'+esc(sv(['상태가 바뀔 때(문제 발생·서버 연결 안 됨·회복) 한 번씩 보내요.','Sent once when the state changes: a problem, an unreachable server, a recovery.']))+'</p>'
+(targets.length?targets.map(t=>'<label><input type="checkbox" data-server-target="'+esc(t.id)+'"'+(chosen.has(t.id)?' checked':'')+'> <span data-i18n-skip>'+esc(t.label)+'</span></label>').join('')+'<button type="button" id="server-targets-save">'+esc(sv(['저장','Save']))+'</button>':'<p class="muted">'+esc(sv(['연결 및 설정에서 텔레그램 같은 전달 대상을 먼저 추가하세요.','Add a destination such as Telegram in Connections & settings first.']))+'</p>')+'</section>'}
// Activity checks: a unit's journal must show a matching line within the window.
function serverWindow(m){return m%1440===0?m/1440+sv(['일','d']):m%60===0?m/60+sv(['시간','h']):m+sv(['분','min'])}
// What an activity check looks for, picked from a list: the pattern is set here, not typed.
const CHECK_KINDS=[['any',['로그가 계속 찍히는지','Log lines keep coming'],'.'],['success',['성공 기록이 찍히는지','Success lines keep coming'],'[Ss]ucce(ss|ed)|[Cc]omplete|executed|성공|완료']];
const CHECK_WINDOWS=[[10,['10분','10 min']],[30,['30분','30 min']],[60,['1시간','1 hour']],[360,['6시간','6 hours']],[1440,['하루','1 day']],[4320,['3일','3 days']],[10080,['1주','1 week']]];
const checkWhat=pattern=>{const kind=CHECK_KINDS.find(k=>k[2]===pattern);return kind?sv(kind[1]):pattern};
function serverChecksHtml(d){const s=d.server,services=s.units.filter(u=>u.kind==='service').map(u=>u.id);
return '<section class="panel"><h3>'+esc(sv(['활동 점검','Activity checks']))+'</h3><p class="muted">'+esc(sv(['서비스는 살아 있는데 할 일을 안 하는 경우를 잡아요. 정한 기간 동안 그 서비스 로그에 해당 기록이 하나도 없으면 확인 필요로 올려요.','Catches a service that is up but no longer doing its job: if its log shows no such line in the window, the Work needs you.']))+'</p>'
+(s.checks.length?'<div class="server-wrap"><table class="server-table"><thead><tr><th></th><th>'+esc(sv(['이름','Name']))+'</th><th>'+esc(sv(['서비스','Service']))+'</th><th>'+esc(sv(['확인할 것','Looks for']))+'</th><th>'+esc(sv(['기간','Window']))+'</th><th>'+esc(sv(['최근 건수','Matches']))+'</th><th></th></tr></thead><tbody>'+s.checks.map((c,i)=>'<tr class="u-'+(c.count===0?'problem':c.count==null?'off':'ok')+'"><td><i class="sdot '+(c.count===0?'problem':c.count==null?'off':'ok')+'"></i></td><td data-i18n-skip>'+esc(c.label)+'</td><td class="mono" data-i18n-skip>'+esc(c.unit)+'</td><td data-i18n-skip>'+esc(checkWhat(c.pattern))+'</td><td class="mono">'+esc(serverWindow(c.minutes))+'</td><td class="mono">'+esc(c.count==null?sv(['다음 확인 때','next check']):String(c.count))+'</td><td><button type="button" class="import-link" data-check-remove="'+i+'">'+esc(sv(['지우기','Remove']))+'</button></td></tr>').join('')+'</tbody></table></div>':'')
+(services.length?'<div class="server-form"><label>'+esc(sv(['서비스','Service']))+'<select id="check-unit">'+services.map(u=>'<option>'+esc(u)+'</option>').join('')+'</select></label><label>'+esc(sv(['확인할 것','Looks for']))+'<select id="check-kind">'+CHECK_KINDS.map(k=>'<option value="'+k[0]+'">'+esc(sv(k[1]))+'</option>').join('')+'<option value="custom">'+esc(sv(['직접 입력 (정규식)','Custom (regex)']))+'</option></select></label>'
+'<label class="wide" id="check-pattern-wrap" hidden>'+esc(sv(['로그에 있어야 할 문구 (정규식)','Pattern the log must show (regex)']))+'<input id="check-pattern" maxlength="200" placeholder="'+esc(sv(['예: executed successfully','e.g. executed successfully']))+'"></label>'
+'<label>'+esc(sv(['기간','Window']))+'<select id="check-window">'+CHECK_WINDOWS.map(w=>'<option value="'+w[0]+'"'+(w[0]===1440?' selected':'')+'>'+esc(sv(w[1]))+'</option>').join('')+'</select></label><label>'+esc(sv(['이름 (비우면 자동)','Name (optional)']))+'<input id="check-label" maxlength="80"></label><div class="wide"><button type="button" id="check-add">'+esc(sv(['점검 추가','Add check']))+'</button></div></div>':'')+'</section>'}
app.addEventListener('change',event=>{if(event.target.id==='check-kind')document.getElementById('check-pattern-wrap').hidden=event.target.value!=='custom'});
// A bot's own record of what it sent, read into the feed: a SQLite table or a JSONL file on the server, read-only.
function serverFeedHtml(d){const f=d.server.feed||[];if(!f.length)return '';
return '<section class="panel server-feed"><h3>'+esc(sv(['발송 기록 → 피드','Send records → feed']))+'</h3><p class="muted">'+esc(sv(['이 서버의 봇이 텔레그램 등으로 직접 보낸 글을 봇의 발송 기록에서 읽어 피드에 같이 올리고 있어요.','Posts what the bots on this server sent (to Telegram and elsewhere) to the feed, read from their own send records.']))+'</p>'
+'<div class="server-wrap"><table class="server-table"><thead><tr><th></th><th>'+esc(sv(['이름','Name']))+'</th><th>'+esc(sv(['기록','Record']))+'</th><th>'+esc(sv(['마지막 글','Last post']))+'</th><th></th></tr></thead><tbody>'+f.map((x,i)=>'<tr class="u-'+(x.error?'problem':x.last_at?'ok':'off')+'"><td><i class="sdot '+(x.error?'problem':x.last_at?'ok':'off')+'"></i></td><td data-i18n-skip>'+esc(x.label)+'</td><td class="mono" data-i18n-skip>'+esc(x.kind+' · '+x.path)+'</td><td class="mono">'+esc(x.error?sv(['읽기 실패 ','Read failed '])+x.error:x.last_at?serverWhen(Date.parse(x.last_at)/1000):sv(['다음 확인 때','next check']))+'</td><td><button type="button" class="import-link" data-feed-remove="'+i+'">'+esc(sv(['지우기','Remove']))+'</button></td></tr>').join('')+'</tbody></table></div></section>'}
// The conversation with the owner's AI app that works on this server over SSH: one session per server Work.
let serverChatDraft='',serverChatSeen='';
function serverChatHtml(d){const c=d.chat;if(!c)return '';const name=c.client==='claude'?'Claude Code':c.client==='codex'?'Codex':sv(['AI 앱','AI app']);
return '<section class="ws-pane session-pane server-chat"><header><h3>'+esc(sv(['대화 · 이 서버에 지시하기','Conversation · direct this server']))+'</h3><span class="hint-inline">'+esc(name)+'</span></header><div class="chat session-chat" id="server-chat-log">'
+(c.messages.length?c.messages.map(m=>m.role==='tool'?'<div class="turn tool" data-i18n-skip>⚙ '+esc(m.text)+'</div>':'<div class="turn '+(m.role==='user'?'me':'ai')+'"><span class="who">'+esc(m.role==='user'?sv(['나','You']):name)+'</span><p data-i18n-skip>'+esc(m.text)+'</p>'+(m.at?'<time>'+esc(clock(m.at))+'</time>':'')+'</div>').join(''):'<p class="hint">'+esc(sv([name+'에게 이 서버의 서비스를 고치라고 지시할 수 있어요. '+name+'는 이 컴퓨터에서 SSH로 서버에 들어가 확인하고 고치며, 바꾸기 전에 백업해요.','Ask '+name+' to change the services on this server. It works on the server over SSH from this computer and backs up before changing anything.']))+'</p>')+'</div>'
+'<div class="chat-send"><textarea id="server-chat-input" rows="2" maxlength="4000" placeholder="'+esc(sv(['예: 미국장 리포트에 국내 증시 소식이 섞이지 않게 고쳐 줘','e.g. Keep Korean market news out of the US close report']))+'"'+(c.can_send?'':' disabled')+'></textarea><button type="button" id="server-chat-send" class="primary"'+(c.can_send?'':' disabled')+'>'+esc(c.sending?sv(['답변 기다리는 중','Waiting for the reply']):sv(['보내기','Send']))+'</button></div><p class="hint">'+esc(c.sending?sv(['지시를 처리하고 있어요. 끝나면 답변이 여기에 보여요.','Working on it. The reply shows here when done.']):sv(['같은 대화로 이어져요. 서버를 바꾸는 일은 이 대화의 AI가 직접 해요.','It continues the same conversation. The AI in this conversation makes the server changes itself.']))+'</p></section>'}
function paintServerChat(d){const input=document.getElementById('server-chat-input');if(input)input.value=serverChatDraft;const log=document.getElementById('server-chat-log'),key=(d.chat?.messages.length||0)+':'+(d.chat?.messages.at(-1)?.at||'');if(log&&serverChatSeen!==key){log.scrollTop=log.scrollHeight;serverChatSeen=key}}
app.addEventListener('input',event=>{if(event.target.id==='server-chat-input')serverChatDraft=event.target.value});
async function saveServerFeed(list){const d=detail;await serverDo(async()=>{const value=await serverPost('feed',{work_id:d.id,sources:list.map(x=>x.kind==='sqlite'?{label:x.label,kind:'sqlite',path:x.path,query:x.query}:{label:x.label,kind:'jsonl',path:x.path})});if(selected!==d.id)return;detail={...detail,...value};renderDetail();setMessage(sv(['연결했어요. 다음 서버 확인 때 새 글이 피드에 올라와요.','Connected. New posts reach the feed with the next server check.']))})}
async function saveServerChecks(list){const d=detail;await serverDo(async()=>{const value=await serverPost('checks',{work_id:d.id,checks:list.map(c=>({label:c.label,unit:c.unit,pattern:c.pattern,minutes:c.minutes}))});if(selected!==d.id)return;detail={...detail,...value};renderDetail();setMessage(sv(['점검을 저장했어요. 다음 확인 때 반영돼요.','Saved. It runs with the next check.']))})}
app.addEventListener('click',async event=>{if(!detail?.server)return;
if(event.target.closest('#server-targets-save')){const d=detail,ids=[...document.querySelectorAll('[data-server-target]:checked')].map(n=>n.dataset.serverTarget);await serverDo(async()=>{const response=await fetch('work/delivery',{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify({work_id:d.id,revision:d.delivery?.revision||0,target_ids:['app',...ids]})}),data=await response.json();if(!response.ok)throw Error(data.error||'DELIVERY_SELECTION_FAILED');if(selected!==d.id)return;detail={...detail,delivery:{...detail.delivery,...data}};renderDetail();setMessage(sv(['알림 받을 곳을 저장했어요.','Saved where notices go.']))});return}
if(event.target.closest('#server-chat-send')){const text=serverChatDraft.trim(),id=detail.id;if(!text)return;await serverDo(async()=>{await serverPost('chat',{work_id:id,text});serverChatDraft='';setMessage(sv(['보냈어요. 서버 작업이 끝나면 답변이 여기에 보여요.','Sent. The reply shows here when the server work is done.']));if(selected===id)await loadDetail()});return}
const feedRemove=event.target.closest('[data-feed-remove]');if(feedRemove){await saveServerFeed(detail.server.feed.filter((_,i)=>i!==Number(feedRemove.dataset.feedRemove)));return}
const remove=event.target.closest('[data-check-remove]');if(remove){await saveServerChecks(detail.server.checks.filter((_,i)=>i!==Number(remove.dataset.checkRemove)));return}
if(event.target.closest('#check-add')){const unit=document.getElementById('check-unit').value,kind=document.getElementById('check-kind').value,minutes=Number(document.getElementById('check-window').value),preset=CHECK_KINDS.find(k=>k[0]===kind),pattern=preset?preset[2]:document.getElementById('check-pattern').value.trim();
if(!pattern){setMessage(sv(['찾을 문구를 넣어 주세요.','Enter the pattern to look for.']));return}
const label=document.getElementById('check-label').value.trim()||unit.replace(/\\.service$/,'')+' · '+(preset?sv(preset[1]):pattern).slice(0,40);
await saveServerChecks([...detail.server.checks,{label:label.slice(0,80),unit,pattern,minutes}])}});
function renderServerDetail(){const d=detail,s=d.server,rows=[...s.units].sort((a,b)=>(a.state==='problem'?0:a.state==='ok'?1:2)-(b.state==='problem'?0:b.state==='ok'?1:2)||a.id.localeCompare(b.id));
app.innerHTML='<button type="button" class="back" id="back">← 업무 목록</button><section class="work-head"><div><span class="state">'+esc(labels[d.run_status]||d.run_status)+'</span><h2 data-i18n-skip>'+esc(d.title)+'</h2><p><span data-i18n-skip>'+esc(s.target_name)+'</span></p><div class="server-mode" role="group" aria-label="'+esc(sv(['실행 방식','How it runs']))+'"><span>'+esc(sv(['실행 방식','How it runs']))+'</span>'+[['auto',['자동','Auto']],['recurring',['반복 실행','Recurring']],['standby',['상시 대기','Always on']]].map(([id,label])=>'<button type="button" data-server-mode="'+id+'" aria-pressed="'+(s.mode_set?s.mode===id:id==='auto')+'">'+esc(sv(label))+(id==='auto'&&!s.mode_set?' · '+esc(sv(s.mode==='standby'?['상시 대기','always on']:['반복','recurring'])):'')+'</button>').join('')+'</div><p class="muted">'+esc(sv(['마지막 확인 ','Last checked ']))+esc(s.observed_at?serverWhen(Date.parse(s.observed_at)/1000):sv(['아직 없음','never']))+(s.stale?' · '+esc(sv(['확인이 늦어지고 있어요','checks are delayed'])):'')+'</p>'+(s.error?'<p role="alert">'+esc(SERVER_ERRORS[s.error]?sv(SERVER_ERRORS[s.error]):s.error)+'</p>':'')+'</div></section>'
+serverChatHtml(d)+'<section class="panel server-units"><header><h3>'+esc(sv(['서비스','Services']))+'</h3><button type="button" id="server-refresh">'+esc(sv(['지금 확인','Check now']))+'</button></header><div class="server-wrap"><table class="server-table"><thead><tr><th></th><th>'+esc(sv(['이름','Name']))+'</th><th>'+esc(sv(['종류','Kind']))+'</th><th>'+esc(sv(['상태','State']))+'</th><th>'+esc(sv(['시작 · 마지막 실행','Started · last run']))+'</th><th>'+esc(sv(['주기','Schedule']))+'</th><th>'+esc(sv(['다음 실행','Next run']))+'</th><th>'+esc(sv(['재시작','Restarts']))+'</th><th>'+esc(sv(['설명','Description']))+'</th></tr></thead><tbody>'
+rows.map(u=>'<tr class="u-'+esc(u.state)+'"><td><i class="sdot '+esc(u.state)+'"></i></td><td class="mono" data-i18n-skip>'+esc(u.id)+'</td><td>'+esc(sv(SERVER_KINDS[u.kind]||['','']))+'</td><td class="mono" data-i18n-skip>'+esc(u.note?serverNote(u.note):u.state==='off'?sv(['꺼 둠','off']):[u.active,u.sub].filter(Boolean).join(' · '))+'</td><td class="mono">'+esc(serverWhen(u.kind==='timer'?u.last_run:u.since))+'</td><td class="mono" title="'+esc(u.schedule?.raw||'')+'">'+esc(u.schedule?sv([u.schedule.ko,u.schedule.en]):'')+'</td><td class="mono">'+esc(serverWhen(u.next_run))+'</td><td class="mono">'+esc(u.kind==='service'?String(u.restarts):'')+'</td><td class="desc" data-i18n-skip>'+esc(u.kind==='container'?'':u.description||'')+'</td></tr>').join('')+'</tbody></table></div><p class="muted">'+esc(sv(['Office는 서버에서 상태를 읽기만 해요. 서비스를 켜거나 끄거나 다시 시작하지 않아요. 약 2분마다 확인해요.','Office only reads states on the server. It never starts, stops or restarts a service. It checks about every two minutes.']))+'</p></section>'
+serverNoticeHtml(d)+serverChecksHtml(d)+serverFeedHtml(d)
+'<section class="panel"><h3>'+esc(sv(['변화 기록','Changes']))+'</h3>'+((d.activity||[]).filter(a=>String(a.kind).startsWith('server.')&&!String(a.kind).startsWith('server.chat.')).slice(-20).reverse().map(a=>'<p><span class="muted">'+esc(serverWhen(Date.parse(a.created_at)/1000))+'</span> '+esc(a.summary)+'</p>').join('')||'<p class="muted">'+esc(sv(['아직 바뀐 것이 없어요.','No changes yet.']))+'</p>')+'</section>';
document.getElementById('back').onclick=backToBoard;paintServerChat(d);
app.querySelectorAll('[data-server-mode]').forEach(button=>button.onclick=()=>serverDo(async()=>{const id=d.id;await serverPost('mode',{work_id:id,mode:button.dataset.serverMode});if(selected!==id)return;await loadDetail();setMessage(sv(['실행 방식을 바꿨어요.','How it runs is updated.']))}));
document.getElementById('server-refresh').onclick=()=>serverDo(async()=>{const id=d.id;setMessage(sv(['서버 상태를 읽고 있어요.','Reading the server state.']));const value=await serverPost('refresh',{work_id:id});if(selected!==id)return;detail={...detail,...value};renderDetail();setMessage(value.server.error?sv(['서버에 접속하지 못했어요. 마지막 기록을 보여 줘요.','Could not reach the server. Showing the last record.']):sv(['방금 확인했어요.','Checked just now.']))})}
`;}
