// Sessions from the owner's own AI app: an import route that lists recent Claude Code and Codex sessions and attaches
// one as a Work, and the detail that shows its conversation and continues it while it is idle.
export const sessionMirrorCss=`.session-list{display:flex;flex-direction:column;gap:6px;margin:12px 0}.session-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:4px 12px;align-items:center;border:1px solid var(--line);border-radius:8px;padding:8px 10px}.session-row strong{font:500 13px var(--sans);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.session-row small{grid-column:1;font:11.5px var(--mono);color:var(--dim);overflow-wrap:anywhere}.session-row button{grid-row:1/3;grid-column:2}
.session-chat{max-height:none;height:min(70vh,760px)}.session-chat .turn.tool{align-self:flex-start;font:11.5px var(--mono);color:var(--dim);padding:0 4px;background:none;border:0}`;

export function sessionMirrorScript(){return `
let sessionBusy=false,sessionDraft='',sessionSeen='',sessionRows=[],sessionTab=null;
const se=pair=>pair[window.officeLang==='en'?1:0];
const SESSION_ERRORS={SESSION_BUSY:['이 대화는 지금 다른 곳에서 쓰는 중이에요. 1분쯤 조용해진 뒤에 보낼 수 있어요.','This conversation is in use elsewhere. You can send once it has been quiet for a minute.'],SESSION_FOLDER_MISSING:['이 대화의 작업 폴더가 없어졌어요.','The folder of this conversation is gone.'],SESSION_NOT_FOUND:['세션을 찾지 못했어요.','The session was not found.'],CLIENT_RUN_DISABLED:['이 설치에서는 AI 앱 실행이 꺼져 있어요.','Running the AI app is turned off in this install.'],SESSION_WINDOWS_UNAVAILABLE:['이 대화의 폴더나 Windows용 앱을 찾지 못해 여기서는 이어갈 수 없어요. 원래 앱에서 이어가 주세요.','The folder of this conversation or its Windows client was not found; continue it in its own app.']};
async function sessionPost(action,body={}){const response=await fetch('work/session/'+action,{method:'POST',headers:{'content-type':'application/json','x-agent-driver':'human-office'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(SESSION_ERRORS[data.error]?se(SESSION_ERRORS[data.error]):data.error||'SESSION_REQUEST_INVALID');return data}
async function sessionDo(fn){if(sessionBusy)return;sessionBusy=true;try{await fn()}catch(error){setMessage(String(error.message||error))}finally{sessionBusy=false}}
// Before the prompt route, which stays last.
document.querySelector('.import-routes [data-import-route="external"]').insertAdjacentHTML('beforebegin','<button type="button" data-import-route="session" aria-pressed="false">AI 대화 연결</button>');
document.getElementById('import-external').insertAdjacentHTML('beforebegin','<div id="import-session" class="import-pane" hidden><p class="muted">데스크톱 앱이나 터미널에서 쓰던 Claude Code·Codex 대화를 업무로 붙여요. 대화는 원래 세션 파일에서 읽고, 대화가 쉬는 동안 여기서 이어서 지시할 수 있어요.</p><div class="seg" role="group" id="session-tabs"><button type="button" data-session-tab="claude" aria-pressed="false">Claude Code</button><button type="button" data-session-tab="codex" aria-pressed="false">Codex</button></div><div id="session-list" class="session-list"></div></div>');
const sessionClient=c=>c==='claude'?'Claude Code':'Codex';
// One tab per app; the tab opens on the app used most recently.
function renderSessionList(){const rows=sessionRows.filter(s=>s.client===sessionTab),box=document.getElementById('session-list');
document.querySelectorAll('[data-session-tab]').forEach(b=>{const n=sessionRows.filter(s=>s.client===b.dataset.sessionTab).length;b.setAttribute('aria-pressed',String(b.dataset.sessionTab===sessionTab));b.textContent=sessionClient(b.dataset.sessionTab)+' '+n});
box.innerHTML=rows.length?rows.map(s=>'<div class="session-row"><strong data-i18n-skip title="'+esc(s.title)+'">'+esc(s.title)+'</strong><small data-i18n-skip>'+esc((s.windows?se(['Windows 앱','Windows app'])+' · ':'')+(s.cwd||'')+' · '+ago(s.updated_at))+'</small><button type="button" data-session-attach="'+esc(s.client+':'+s.id)+'"'+(s.attached?' disabled':'')+'>'+esc(s.attached?se(['연결됨','Attached']):se(['연결','Attach']))+'</button></div>').join(''):'<p class="muted">'+esc(se(['최근 대화를 찾지 못했어요.','No recent conversations were found.']))+'</p>'}
async function sessionLoadList(){await sessionDo(async()=>{sessionRows=await sessionPost('list');if(!sessionTab)sessionTab=sessionRows[0]?.client||'claude';renderSessionList()})}
document.getElementById('session-tabs').addEventListener('click',event=>{const b=event.target.closest('[data-session-tab]');if(!b)return;sessionTab=b.dataset.sessionTab;renderSessionList()});
document.getElementById('session-list').addEventListener('click',event=>{const b=event.target.closest('[data-session-attach]');if(!b)return;const [client,session_id]=b.dataset.sessionAttach.split(':');sessionDo(async()=>{const r=await sessionPost('attach',{client,session_id});importOpen=false;openWork(r.work_id)})});
function renderSessionDetail(){const d=detail,s=d.session,key=s.messages.length+':'+(s.messages.at(-1)?.at||'');
app.innerHTML='<button type="button" class="back" id="back">← 업무 목록</button><section class="work-head"><div><span class="state">'+esc(labels[d.run_status]||d.run_status)+'</span><h2 data-i18n-skip>'+esc(d.title)+'</h2><p data-i18n-skip>'+esc(sessionClient(s.client)+' · '+(s.cwd||''))+'</p><p class="muted">'+esc(se(['마지막 활동 ','Last activity ']))+esc(ago(d.updated_at))+'</p>'+(s.missing?'<p role="alert">'+esc(se(['세션 파일이 없어졌어요.','The session file is gone.']))+'</p>':'')+'</div></section>'
+'<section class="ws-pane session-pane"><header><h3>'+esc(se(['대화','Conversation']))+'</h3><span class="hint-inline">'+esc(se(['원래 세션 파일에서 읽어요','Read from the session file']))+'</span></header><div class="chat session-chat" id="session-log">'+s.messages.map(m=>m.role==='tool'?'<div class="turn tool" data-i18n-skip>⚙ '+esc(m.text)+'</div>':'<div class="turn '+(m.role==='user'?'me':'ai')+'"><span class="who">'+esc(m.role==='user'?se(['나','You']):sessionClient(s.client))+'</span><p data-i18n-skip>'+esc(m.text)+'</p>'+(m.at?'<time>'+esc(clock(m.at))+'</time>':'')+'</div>').join('')+'</div>'
+'<div class="chat-send"><textarea id="session-input" rows="2" maxlength="4000" placeholder="'+esc(se(['이 대화에 이어서 보낼 지시','A message to continue this conversation']))+'"'+(s.can_send?'':' disabled')+'></textarea><button type="button" id="session-send" class="primary"'+(s.can_send?'':' disabled')+'>'+esc(s.sending?se(['답변 기다리는 중','Waiting for the reply']):se(['보내기','Send']))+'</button></div><p class="hint">'+esc(s.windows&&!s.ready?se(['이 대화의 폴더(네트워크 공유 등)나 Windows용 앱을 찾지 못해 여기서는 읽기만 해요. 이어서 지시는 원래 앱에서 해 주세요.','The folder of this conversation (a network share, say) or its Windows client was not found, so it is read only here. Continue it in its own app.']):s.sending?se(['보낸 지시를 처리하고 있어요.','Your message is being handled.']):s.can_send?se(['같은 세션에 이어져요. 데스크톱 앱에 이 대화가 열려 있으면 앱 화면에는 바로 보이지 않을 수 있어요.','It continues the same session. If the desktop app has this conversation open, its screen may not show it at once.']):se(['대화가 진행 중이에요. 1분쯤 조용해지면 보낼 수 있어요.','The conversation is active. You can send once it has been quiet for a minute.']))+'</p></section>';
document.getElementById('back').onclick=showBoard;const input=document.getElementById('session-input');if(input)input.value=sessionDraft;const log=document.getElementById('session-log');if(log&&sessionSeen!==key){log.scrollTop=log.scrollHeight;sessionSeen=key}}
app.addEventListener('input',event=>{if(event.target.id==='session-input')sessionDraft=event.target.value});
app.addEventListener('click',event=>{if(!event.target.closest('#session-send')||!detail?.session)return;const text=sessionDraft.trim();if(!text)return;const id=detail.id;sessionDo(async()=>{await sessionPost('send',{work_id:id,text});sessionDraft='';setMessage(se(['보냈어요. 답변이 오면 여기에 보여요.','Sent. The reply shows here when it arrives.']));if(selected===id)await loadDetail()})});
`;}
