import {displayOptionsHtml,sidebarHtml,themeScript,uiCss} from './ui-shell.js';
import {i18nScript} from './i18n.js';
import {browserSetupHtml,browserSetupScript} from './browser-setup-ui.js';
import {deliveryCss,deliverySettingsHtml,deliverySettingsScript} from './delivery-ui.js';
export function settingsHtml(nonce:string){return `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>연결 및 설정 · Agent Office</title>
<style>${uiCss}${deliveryCss}
.flow{display:grid;grid-template-columns:1fr 28px 1fr 28px 1fr;align-items:stretch;margin:0 0 18px}.flow i{height:1px;background:var(--line2);align-self:center}.nd{border:1px solid var(--line2);border-radius:var(--r);padding:10px 14px;background:var(--panel);min-width:0;text-align:center;display:grid;align-content:center}.nd b{display:block;font:500 14px var(--mono)}.nd small{font:11.5px var(--mono);color:var(--dim)}.nd.hot{border-color:var(--accent);box-shadow:0 0 0 3px var(--acc-a)}
@media(max-width:700px){.flow{grid-template-columns:1fr}.flow i{width:1px;height:12px;margin:auto}}
.steps4{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:4px;border-bottom:1px solid var(--line);margin:4px 0 14px}.steps4 button{border:0;border-bottom:2px solid transparent;border-radius:0;background:none;color:var(--dim);padding:8px 6px;display:flex;align-items:center;justify-content:center;gap:6px;white-space:normal}
.steps4 button.active{color:var(--text);border-bottom-color:var(--accent);font-weight:600}.si{width:16px;height:16px;border-radius:50%;border:1px solid var(--line2);font-size:10px;line-height:14px;text-align:center;color:var(--faint)}.si.done{background:var(--ok);border-color:var(--ok);color:var(--bg)}
.settings{max-width:760px}.panel h2{font-size:16px;margin-bottom:4px}.panel>p.muted{margin:0 0 10px}
.runtime-line{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid var(--line)}.runtime-line>div{min-width:0}.runtime-line .badge{white-space:normal}
.cli-maintenance{margin:14px 0;padding:12px;border:1px solid var(--line);border-radius:8px}.cli-maintenance-head{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px}.cli-maintenance-head label{margin:0}.cli-maintenance-head button{width:auto;min-width:0}.cli-maintenance p{margin:6px 0 0;font-size:12px;overflow-wrap:anywhere}
.list,.browser-list{display:grid;grid-template-columns:minmax(0,1fr) max-content max-content;column-gap:16px}.client{min-width:0;padding:14px 0;border-bottom:1px solid var(--line);display:grid;grid-column:1/-1;grid-template-columns:subgrid;align-items:center;row-gap:12px}.crow{display:grid;grid-column:1/-1;grid-template-columns:subgrid;align-items:center;column-gap:16px;row-gap:12px}
.client strong{display:grid;grid-column:1/span 2;grid-template-columns:subgrid;align-items:center;font-weight:500}.client>.hint{grid-column:1/-1;justify-self:end;margin:0}.client .sep{display:none}.client .cname{min-width:0;overflow-wrap:anywhere;justify-self:stretch;text-align:left;display:flex;gap:10px;align-items:center;font-weight:600}.client-icon{display:inline-flex;align-items:center;justify-content:center;width:36px;height:36px;flex:0 0 36px;border:1px solid var(--line);border-radius:8px;background:var(--bg);color:var(--text)}.client-icon svg{width:24px;height:24px}.client-icon[data-client=claude]{color:#d97757}.client-icon[data-client=hermes]{color:var(--accent)}.client .badge{white-space:normal;justify-self:center;align-self:center}.cact{grid-column:3;min-width:0;max-width:100%;display:flex;flex-wrap:wrap;gap:8px;align-items:center;justify-content:flex-end;justify-self:end;min-height:36px}.cact button,.cact .action-link{width:auto;min-width:0;min-height:36px;text-align:center;font-size:12.5px;white-space:normal;line-height:1.4}.cact a{font-size:12px}.cact button[data-setup-complete]{opacity:1;color:var(--ok);border-color:var(--ok);background:var(--ok-a);cursor:default}.client>.browser-help{grid-column:1/-1;margin-top:0}.browser-help a{display:block;margin-top:8px;color:var(--code);text-decoration:underline;text-underline-offset:3px}.cact .login-action{border-color:var(--accent);color:var(--accent);background:var(--acc-a)}
.client p{grid-column:1/-1;margin:0;font-size:12px}.client p.muted.hinted{display:none}.client>.device{grid-column:1/-1}.client>.cact{justify-content:flex-end}.client .login-hint{display:block;font-size:12px;margin-top:12px;color:var(--dim)}
.device{margin-top:8px;padding:8px 10px;background:var(--raise);border-radius:6px;overflow-wrap:anywhere;font-size:13px}.device code{display:block;font-size:20px;margin-top:6px;letter-spacing:.08em}
.row{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,200px),1fr));gap:12px;align-items:start}.row>*{min-width:0}.row label{text-align:left;margin:0 0 6px}#app-model-row{margin-top:14px}#catalog-state{margin:10px 0 16px;line-height:1.6}.actions{display:flex;flex-wrap:wrap;gap:8px;justify-content:flex-end;align-items:center;margin-top:22px}.actions button{width:auto;white-space:normal;line-height:1.4}
.role-model-row{min-width:0;margin:12px 0;padding:8px 12px;border:1px solid var(--line);border-radius:8px}.role-model-row legend{padding:0 6px;color:var(--text)}
details{margin-top:12px;color:var(--dim)}details summary{cursor:pointer}details label{color:var(--text)}#windows-bridge-config{white-space:pre-wrap;overflow-wrap:anywhere}
.settings-help{margin:8px 0 12px}.settings-help p{margin:8px 0;font-size:13px;line-height:1.6}.settings-help>summary{width:max-content;max-width:100%}.browser-guide{margin-top:16px;padding-top:12px;border-top:1px solid var(--line)}.browser-guide h4{margin:0 0 8px;color:var(--text);font-size:13px}.browser-guide a{display:block;width:fit-content;margin-top:8px;color:var(--code);text-decoration:underline;text-underline-offset:3px}.browser-feedback[hidden],#browser-setup-notice[hidden]{display:none}
.consent{margin-top:14px;padding:10px 12px;border:1px solid var(--line);border-radius:6px}.consent label{margin:0;color:var(--text)}
.terminal{margin:14px 0 0;border:1px solid var(--line);border-radius:var(--r);background:var(--panel)}.terminal-head{display:grid;grid-template-columns:140px minmax(0,1fr) 100px;align-items:center;gap:12px;padding:8px 12px;font-size:12px;cursor:pointer;list-style:none;text-align:center}.terminal-head::-webkit-details-marker{display:none}
#tail-last{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.terminal pre{margin:0;padding:10px 12px;max-height:220px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;border-top:1px solid var(--line);color:var(--dim)}
#mcp-clients{grid-auto-rows:1fr;row-gap:8px;margin:12px 0}#mcp-clients .client{border:1px solid var(--line);border-radius:8px;padding:12px;align-content:center}.connection-title{margin-top:16px}#browser-setup-refresh{margin-top:0}.runtime-line .connection-title{margin:0}.small-action{font-size:12px;padding:4px 10px}.poll-note{margin-right:auto;font-size:12px}.site-login-section{margin-top:14px;padding-top:4px;border-top:1px solid var(--line)}.site-add-row{display:flex;gap:8px;margin-top:10px}.site-add-row input{flex:1;min-width:0}.key-state{display:inline-flex;align-items:center;gap:8px;margin:6px 0 0}.icon-btn{border:1px solid var(--line);background:transparent;border-radius:6px;width:24px;height:24px;padding:0;line-height:1;cursor:pointer;color:var(--dim)}.icon-btn.danger{color:#c62828;border-color:#c62828}.icon-btn:hover{filter:brightness(1.15)}.field-action{display:flex;justify-content:flex-end;margin:12px 0}.field-action>button{width:auto;min-width:0;white-space:normal;line-height:1.4}.browser-list{grid-template-columns:minmax(0,1fr) minmax(0,1fr) minmax(0,2fr)}.browser-list strong{grid-column:auto;display:block;justify-self:center;text-align:center;min-width:0;overflow-wrap:anywhere}.settings>button{display:block;margin:12px 0 0 auto}#windows-bridge>button{display:block;margin:12px 0 0 auto}
@media(max-width:620px){.list{grid-template-columns:minmax(0,1fr) minmax(0,max-content)}.browser-list{grid-template-columns:repeat(2,minmax(0,1fr))}.cact{grid-column:2;justify-self:end}.browser-list .cact{grid-column:1/-1}.client-icon{width:28px;height:28px;flex-basis:28px}.client-icon svg{width:20px;height:20px}.client .cname{gap:8px}.terminal-head{grid-template-columns:minmax(0,1fr) 100px}.terminal-head #tail-last{grid-column:1/-1;grid-row:2}.terminal-head #tail-state{grid-column:2;grid-row:1}}@media(max-width:380px){.runtime-line{flex-wrap:wrap}.steps4 .si{display:none}}</style>
<div class="app">${sidebarHtml('settings')}<main class="main"><div class="settings"><header class="top"><h1>연결 및 설정</h1><span class="muted mono" id="progress">설정을 불러오는 중…</span>${displayOptionsHtml}</header><div class="flow" aria-hidden="true"><div class="nd"><b>mcp client</b><small>codex · claude code</small></div><i></i><div class="nd hot"><b>agent-office mcp</b><small>stdio · observe · pack plan</small></div><i></i><div class="nd"><b>LOCAL</b><small>no cloud relay</small></div></div><nav class="steps4" aria-label="설정 단계"><button data-step="0"><span class="si" id="si-0" aria-hidden="true">1</span>AI 앱</button><button data-step="1"><span class="si" id="si-1" aria-hidden="true">2</span>브라우저·로그인</button><button data-step="2"><span class="si" id="si-2" aria-hidden="true">3</span>AI 설정</button><button data-step="3"><span class="si" id="si-3" aria-hidden="true">4</span>Jev</button><button data-step="4"><span class="si" id="si-4" aria-hidden="true">5</span>결과 전달</button></nav>
<section class="panel" id="step-0" hidden><h2>에이전트 연결</h2><div class="runtime-line"><h3 class="connection-title">WSL 연결</h3><span class="badge idle" id="driver-state">설치 확인 중</span></div><div id="mcp-clients" class="list"></div><h3 class="connection-title" id="windows-title" hidden>Windows 연결</h3><details id="windows-bridge" hidden><summary>Windows AI 앱에 MCP 등록하기 · 선택</summary><p class="muted keep" id="windows-bridge-help">Cursor 같은 Windows AI 앱의 채팅에서 Agent Office에 업무를 맡기고 싶을 때만 설정하세요. 위에서 WSL 앱을 연결했다면 건너뛰어도 됩니다.</p><p class="muted keep">예: Windows AI 앱에서 요청 → WSL의 Agent Office가 도구 실행 → 같은 채팅에서 결과 확인.</p><ol class="muted keep"><li>사용할 Windows AI 앱의 설정에서 MCP 서버 추가를 여세요.</li><li>이름은 agent-office로 지정하세요. JSON 입력란에는 아래 설정을, 명령·인수가 나뉜 입력란에는 command와 args 값을 각각 넣으세요.</li><li>저장한 뒤 해당 앱의 MCP 목록에서 연결 상태와 도구 목록을 확인하세요. 이 관제센터에서는 Windows 앱의 등록 여부를 확인할 수 없습니다.</li></ol><p class="muted keep">아래 내용은 앱의 MCP 설정 화면에 넣는 값입니다. 터미널이나 채팅에 입력하는 명령이 아닙니다.</p><pre class="device" id="windows-bridge-config" data-i18n-skip></pre><button id="copy-windows-bridge">설정 복사</button></details><div class="actions"><span class="muted keep poll-note" id="mcp-poll-note"></span><button id="refresh-mcp">지금 확인</button><button id="mcp-next" data-next="1" class="primary">다음</button></div></section>
<section class="panel" id="step-1" hidden><h2>브라우저와 로그인 환경</h2><div class="runtime-line" id="computer-line" hidden><strong>이 컴퓨터에서 실행</strong><span class="badge idle" id="computer-state"></span></div>${browserSetupHtml}<div class="actions"><span class="muted keep poll-note" id="browser-poll-note"></span><button id="connect-computer" class="primary">이 컴퓨터에서 실행 허용</button><button data-next="2">다음</button></div></section>
<section class="panel" id="step-2" hidden><h2>AI 연결</h2><label for="client">담당 AI 앱</label><select id="client" data-seg><option value="codex">Codex</option><option value="claude">Claude Code</option></select><div class="row" id="app-model-row"><div data-for-client="codex"><label for="codex-model">Codex 모델</label><select id="codex-model"><option value="">클라이언트 기본값</option></select></div><div data-for-client="codex"><label for="codex-reasoning">Codex 추론 강도</label><select id="codex-reasoning" data-slider><option value="">클라이언트 기본값</option><option>low</option><option>medium</option><option>high</option><option>xhigh</option></select></div><div data-for-client="claude"><label for="claude-model">Claude Code 모델</label><select id="claude-model"><option value="">클라이언트 기본값</option></select></div><div hidden><label for="opencode-model">OpenCode 모델</label><select id="opencode-model"><option value="">클라이언트 기본값</option></select></div></div><p class="muted keep" id="catalog-state" role="status"></p><div id="role-model-block" hidden></div>
<div class="cli-maintenance" id="cli-maintenance"><div class="cli-maintenance-head"><label for="cli-auto-update"><input id="cli-auto-update" type="checkbox" checked> AI 앱 자동 업데이트 · 24시간마다</label><button id="cli-update-now" type="button">지금 업데이트</button></div><p class="muted" id="cli-maintenance-status" role="status">상태 확인 중…</p></div>
<div class="consent" id="work-data-row" hidden><label><input id="work-data" type="checkbox"> 업무 내용을 담당 AI에 보내 분석·실행 허용</label></div><div class="actions"><button id="save-model">저장</button><button data-save-next="3" class="primary">다음</button></div></section>
<section class="panel" id="step-3" hidden><h2>Jev 연결</h2><p class="muted">정해진 판단 지점에서 쓰는 선택 기능이에요. 연결하지 않으면 담당 AI가 그 판단도 맡아요.</p><label for="jev-mode">사용 방식</label><select id="jev-mode" data-seg><option value="inherit">자동</option><option value="off">사용하지 않음</option><option value="on">API 키로 연결</option></select><div id="jev-fields" hidden><label for="jev-key">TypeSafe / Jev API 키</label><input id="jev-key" type="password" autocomplete="new-password" placeholder="키 입력"><p id="jev-state" class="muted key-state"><span id="jev-state-text"></span><button type="button" id="remove-jev-btn" class="icon-btn danger" hidden aria-label="저장된 Jev 키 삭제" title="저장된 키 삭제">✕</button></p><input type="checkbox" id="remove-jev" hidden></div><div class="actions"><button id="save-jev">저장</button><button id="finish" class="primary">다음</button></div></section>
${deliverySettingsHtml}
<p class="notice" role="status" aria-live="polite" id="notice"></p><details class="terminal" aria-label="연결 작업 기록"><summary class="terminal-head"><span>연결 작업 기록</span><span id="tail-last"></span><span id="tail-state">연결 중</span></summary><p class="muted" style="margin:12px 14px 0;font-size:13px">이 화면에서 실행한 설치·연결의 시작과 결과입니다. 터미널 원문은 저장하지 않습니다. 실제 업무 기록은 <a href="./">업무 현황</a>의 업무 상세에서 확인하세요.</p><pre id="setup-log" aria-live="polite">아직 연결 작업 기록이 없습니다.</pre></details></div></main></div>
<script nonce="${nonce}">
${i18nScript}
${themeScript}
function compactHints(root){for(const scope of root.querySelectorAll('.panel,.consent')){const notes=[...scope.querySelectorAll('p.muted:not([id]):not(.keep)')].filter(node=>!node.closest('details,.client')&&node.closest('.panel,.consent')===scope);if(!notes.length)continue;let help=scope.querySelector('details.settings-help[data-section-help]')||[...scope.children].find(node=>node.matches('details.settings-help:not([id])'));if(!help){help=document.createElement('details');help.className='settings-help';const summary=document.createElement('summary');summary.textContent='설명 보기';help.append(summary);const heading=scope.querySelector('h2');if(heading)heading.after(help);else scope.append(help);}for(const note of notes)help.append(note);}}
const $=id=>document.getElementById(id);let state,mcpState,bootstrapState,step=0,busy=false,initialized=false,flowTimer,clientsLoaded=false,mcpLoaded=false,maintenanceLoaded=false,maintenanceState=null,clientCatalogs={},codexChoiceTouched=false,codexEffortTouched=false;
const localized=(ko,en)=>window.officeCopy?.(ko,en)??(window.officeLang==='ko'?ko:en);
function scopeFields(locked=busy){$('work-data-row').hidden=!state?.work_model_data?.editable;document.querySelectorAll('#step-2 input,#step-2 select,#step-2 button').forEach(node=>{if(node.id!=='save-model'&&!node.hasAttribute('data-save-next'))node.disabled=locked;});$('cli-auto-update').disabled=locked||!maintenanceState;$('cli-update-now').disabled=locked||!maintenanceState||maintenanceState.state==='running';clientFields();}
function fillModels(id,models,selected,defaultLabel='클라이언트 기본값'){const field=$(id);field.replaceChildren();const first=document.createElement('option');first.value='';first.textContent=window.officeText(defaultLabel);field.append(first);for(const row of models){const item=document.createElement('option');item.value=row.id;item.textContent=row.label===row.id?row.id:row.label.split(' · ').map(part=>window.officeText(part)).join(' · ');field.append(item);}if(selected&&!models.some(row=>row.id===selected)){const item=document.createElement('option');item.value=selected;item.textContent=state?.configured?selected+(clientCatalogs[id.replace('-model','')]?.status==='available'?localized(' · 현재 계정 목록에 없음',' · Not in current account catalog'):localized(' · 저장된 모델 · 목록 미확인',' · Saved model · Catalog unavailable')):selected+localized(' · 계정 지원 미확인',' · Account access unverified');field.append(item);}field.value=selected||'';}
const preferredCodexId='gpt-6.1-sol';
const notice=text=>$('notice').textContent=text;
const authWindows=new Map();
function reserveAuthWindow(id){if(!['codex','opencode','cursor'].includes(id)||busy||!initialized)return;const prior=authWindows.get(id);if(prior&&!prior.closed){prior.focus();return;}const tab=window.open('about:blank','_blank');if(tab){tab.opener=null;tab.document.title='Agent Office · Login';tab.document.body.textContent=window.officeLang==='ko'?'공식 로그인 화면을 준비하고 있습니다. 이 창은 자동으로 이동합니다.':'Preparing the official login page. This window will continue automatically.';authWindows.set(id,tab);}}
function closeAuthWindow(id){const tab=authWindows.get(id);try{if(tab&&!tab.closed&&tab.location.href==='about:blank')tab.close();}catch{}authWindows.delete(id);}
function pollAuth(){clearInterval(flowTimer);flowTimer=setInterval(pollFlows,1200);}
function loginAction(id,kind){reserveAuthWindow(id);return action(async()=>{try{const started=await request('settings/login',{client:id,flow:kind});renderFlow(started);pollAuth();}catch(error){closeAuthWindow(id);throw error;}});}
function installAction(id){reserveAuthWindow(id);return action(async()=>{try{notice('설치 중… 연결 작업 기록에서 진행 상황을 확인하세요.');const result=await request('settings/client/install',{client:id});await refreshMcp();if(step===2)await refreshClients(true);if(result.login){renderFlow(result.login);pollAuth();}}catch(error){closeAuthWindow(id);throw error;}});}
function clientRow(name,stateLabel,tone,id){const row=document.createElement('div');row.className='crow';const title=document.createElement('strong'),n=document.createElement('span'),icon=document.createElement('span'),label=document.createElement('span'),sep=document.createElement('span'),badge=document.createElement('span'),actions=document.createElement('div');n.className='cname';icon.className='client-icon';icon.dataset.client=id;icon.setAttribute('aria-hidden','true');const paths={codex:'<rect x="3" y="4" width="18" height="16" rx="4"/><path d="m7 9 3 3-3 3m6 0h4"/>',claude:'<path d="M12 3v18M3 12h18M5.6 5.6l12.8 12.8M5.6 18.4 18.4 5.6M8.6 3.7l6.8 16.6M3.7 8.6l16.6 6.8M3.7 15.4l16.6-6.8M8.6 20.3l6.8-16.6"/>',opencode:'<path d="m8 7-5 5 5 5m8-10 5 5-5 5m-3-12-2 14"/>',cursor:'<path d="m12 3 9 5v8l-9 5-9-5V8l9-5Zm0 0v18M3 8l9 5 9-5"/>',hermes:'<path d="M4 20c2-10 5-15 16-16-1 9-6 14-14 14m-2 2L16 8M8 13h6"/>'};icon.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'+(paths[id]||paths.codex)+'</svg>';label.textContent=name;n.append(icon,label);sep.className='sep';sep.textContent=' · ';badge.className='badge '+tone;badge.textContent=stateLabel;title.append(n,sep,badge);actions.className='cact';row.append(title,actions);return row}
function addClientManage(actions,id,name){const button=document.createElement('button');button.textContent='관리';button.dataset.manageClient=id;button.setAttribute('aria-label',name+' 관리');button.onclick=async()=>{let target;await action(async()=>{await show($(id+'-model')?2:0);const field=$(id+'-model');target=field&&!field.closest('[hidden]')?field:document.querySelector('#mcp-clients [data-client="'+id+'"]');if(target?.closest('[hidden]'))target=$('client');});if(target?.isConnected){if(!['SELECT','BUTTON','INPUT'].includes(target.tagName))target.tabIndex=-1;target.scrollIntoView({block:'center',behavior:'auto'});target.focus({preventScroll:true});}};actions.append(button);}
function stepMarks(){const done=[Boolean(mcpState?.registered_count),Boolean(state?.computer?.connected),Boolean(state?.configured&&state.onboarding_step>=3),Boolean(state?.configured&&state.onboarding_step>=4),Boolean(deliverySettingsState)];done.forEach((ok,i)=>{const m=$('si-'+i);if(m){m.classList.toggle('done',ok);m.textContent=ok?'✓':String(i+1)}})}
const labels={ready:'연결됨',signed_out:'로그인 필요',expired:'다시 로그인 필요',unavailable:'사용할 수 없음',unknown:'확인되지 않음',unchecked:'미확인',needs_login:'로그인 필요',challenge:'사용자 확인 필요',retry_requested:'재확인 요청됨',policy_blocked:'미확인'};
async function request(path,body,site=false){const checking=['settings/mcp/check','settings/refresh','settings/browsers/check'].includes(path);if(checking)$('tail-last').textContent=window.officeText('연결 상태 확인 중…');let response;try{response=await fetch(path,{cache:'no-store',...(body===undefined?{}:{method:'POST',headers:{'content-type':'application/json','X-Agent-Driver':path==='delivery/settings'?'human-office':site?'human-connection':'human-settings'},body:JSON.stringify(body)})});}catch(error){if(checking)appendActivity({at:new Date().toISOString(),area:'setup',state:'error',message:'관제센터에 연결하지 못했습니다. 네트워크를 확인한 뒤 다시 누르세요.'});throw error;}const data=await response.json();if(!response.ok)throw Error(data.error||'연결 오류');return data;}
function lockControls(locked){window.officeBusy?.(locked);document.querySelectorAll('.steps4 button,.panel button,.panel input,.panel select,#copy-windows-bridge').forEach(node=>node.disabled=locked);if(!locked){$('connect-computer').disabled=state?.computer.connected??true;$('mcp-next').disabled=!(mcpState?.registered_count||mcpState?.windows_bridge);}scopeFields(locked);document.querySelectorAll('[data-setup-complete]').forEach(node=>node.disabled=true);}
async function action(fn){if(!initialized||busy)return;busy=true;lockControls(true);try{await fn();}catch(error){notice(({MODEL_SETTINGS_CONFLICT:'다른 창에서 설정이 바뀌었습니다. 새로고침 후 다시 저장하세요.',JEV_CREDENTIAL_REQUIRED:'Jev 키를 입력하거나 사용하지 않음을 선택하세요.',MCP_CLIENT_UNAVAILABLE:'이 WSL/Linux 환경에 클라이언트가 설치되지 않았습니다.',MCP_REGISTRATION_CONFLICT:'기존 agent-driver 설정이 달라 자동으로 덮어쓰지 않았습니다.',MCP_REGISTRATION_FAILED:'클라이언트가 MCP 등록을 완료하지 못했습니다.',OPENCODE_MCP_CONFIG_REVIEW_REQUIRED:'기존 OpenCode 설정을 안전하게 읽지 못해 보존했습니다. 설정 파일을 확인한 뒤 다시 연결하세요.',OPENCODE_MCP_CONFIG_UNSAFE:'OpenCode 설정 파일이 일반 파일이 아니거나 너무 큽니다. 기존 파일은 변경하지 않았습니다.',CLIENT_INSTALL_PLATFORM_UNSUPPORTED:'자동 설치는 Linux·WSL에서 지원합니다. Windows 앱 연결을 선택하세요.',CLIENT_INSTALL_DOWNLOAD_REJECTED:'공식 설치 파일의 주소나 크기를 확인하지 못해 실행하지 않았습니다. 설치를 다시 누르세요.',CLIENT_INSTALL_DOWNLOAD_FAILED:'설치 파일을 내려받지 못했습니다. 인터넷 연결을 확인한 뒤 설치를 다시 누르세요.',CLIENT_INSTALL_DOWNLOAD_TIMEOUT:'설치 파일 다운로드가 지연됐습니다. 인터넷 연결을 확인한 뒤 다시 누르세요.',CLIENT_INSTALL_SCRIPT_INVALID:'올바른 설치 파일이 아니어서 실행하지 않았습니다. 설치를 다시 누르세요.',CLIENT_INSTALL_FAILED:'설치 프로그램이 실패했습니다. 아래 연결 작업 기록에서 종료 코드를 확인하고 다시 누르세요.',CLIENT_INSTALL_TIMEOUT:'설치 시간이 초과됐습니다. 다시 확인으로 설치 여부를 확인하세요.',CLIENT_INSTALL_NOT_DETECTED:'설치 후 실행 파일을 찾지 못했습니다. 다시 확인을 누르거나 설치를 다시 시도하세요.',SETTINGS_REQUEST_INVALID:'요청을 처리하지 못했습니다. 다시 확인 후 재시도하세요.'})[error.message]||error.message);}finally{busy=false;lockControls(!initialized);}}
function modeFields(){scopeFields();}
function clientFields(){const chosen=$('client').value||'codex';for(const node of document.querySelectorAll('#app-model-row [data-for-client]'))node.hidden=node.dataset.forClient!==chosen;}
function jevFields(){$('jev-fields').hidden=$('jev-mode').value!=='on';}
/** The slider shows the usual stops; an older saved value (none, minimal, max, ultra) is kept as its own stop instead of being dropped. */
function setCodexEffort(value){const field=$('codex-reasoning');if(value&&![...field.options].some(o=>o.value===value)){const extra=document.createElement('option');extra.value=extra.textContent=value;field.append(extra);}field.value=value;}
function populate(){const s=state.selection;$('client').value=['auto','mcp','opencode'].includes(s.client)?'codex':s.client;clientFields();for(const id of ['codex','claude','opencode'])fillModels(id+'-model',clientCatalogs[id]?.models||[],s.client_models?.[id]);setCodexEffort(s.codex_reasoning_effort||'');$('jev-mode').value=s.jev;$('jev-state-text').textContent=state.jev_key_present?'키 저장됨':'키를 입력하세요';$('remove-jev-btn').hidden=!state.jev_key_present;$('computer-state').textContent=state.computer.connected?'허용됨':'허용 필요';$('computer-line').hidden=state.computer.connected;$('connect-computer').hidden=state.computer.connected;$('computer-state').className='badge '+(state.computer.connected?'ok':'warn');$('work-data-row').hidden=!state.work_model_data?.editable;$('work-data').checked=Boolean(state.work_model_data?.approved);stepMarks();compactHints(document.body);$('connect-computer').disabled=state.computer.connected;modeFields();jevFields();}
async function show(index){if(!initialized)return;if(index!==step)notice('');step=index;for(let i=0;i<5;i++)$('step-'+i).hidden=i!==index;document.querySelectorAll('[data-step]').forEach(b=>b.classList.toggle('active',Number(b.dataset.step)===index));$('progress').textContent=(index+1)+' / 5';if(index===1)try{void refreshSiteLogins();await refreshBrowserSetup();}catch{notice('브라우저 안내를 불러오지 못했습니다. 다시 불러오기를 누르세요.');}if(index===0&&!mcpLoaded){await refreshMcp();mcpLoaded=true;}if(index===2&&!maintenanceLoaded)await loadMaintenance();if(index===2&&!clientsLoaded){await refreshClients();clientsLoaded=true;}if(index===4){await loadDeliverySettings();stepMarks();}}
function maintenanceTime(value){if(!value)return '';const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleString(window.officeLang==='ko'?'ko-KR':'en-GB');}
function renderMaintenance(syncChoice=true){if(!maintenanceState)return;if(syncChoice)$('cli-auto-update').checked=maintenanceState.enabled;const labels=window.officeLang==='ko'?{disabled:'꺼짐',due:'업데이트 확인 예정',idle:'대기 중',running:'업데이트 중',deferred_busy:'업무 실행 중 · 보류',cooldown:'다음 확인 대기'}:{disabled:'Off',due:'Update due',idle:'Idle',running:'Updating',deferred_busy:'Work active · deferred',cooldown:'Waiting for next check'};const parts=[maintenanceState.preference_saved===false?localized('자동 확인은 AI 설정 저장 후 적용','Automatic checks apply after saving AI settings'):labels[maintenanceState.state]||localized('상태 미확인','Status unknown')];if(maintenanceState.interval_hours===24)parts.push(localized('24시간 간격','Every 24 hours'));const due=maintenanceTime(maintenanceState.next_due_at);if(due&&maintenanceState.preference_saved!==false)parts.push(localized('다음 확인 ','Next check ')+due);const clients=[];if(clients.length)parts.push(clients.map(client=>{const name=String(client.label||client.id||'CLI'),eligibility=client.eligibility_reason||client.reason;let detail=!client.installed?localized('미설치','not installed'):client.managed_update?localized('자동 관리','managed update'):({unmanaged_install:localized('관리 밖 설치','unmanaged install'),unsupported_platform:localized('플랫폼 미지원','unsupported platform'),unsupported_update_method:localized('자동 방식 없음','no managed method')})[eligibility]||localized('수동 관리','manual');if(client.reason==='update_failed')detail+=localized(' · 최근 시도 실패',' · last attempt failed');const success=maintenanceTime(client.last_success_at);if(success)detail+=localized(' · 최근 성공 ',' · last succeeded ')+success;return name+' '+detail;}).join(' · '));$('cli-maintenance-status').textContent=parts.join(' · ');scopeFields(busy);}
async function loadMaintenance(){try{maintenanceState=await request('settings/maintenance/status');maintenanceLoaded=true;renderMaintenance();}catch{$('cli-maintenance-status').textContent=localized('업데이트 설정 상태를 확인하지 못했습니다. AI 연결은 계속 사용할 수 있습니다.','Could not read update settings. AI connection remains available.');scopeFields(busy);}}
async function saveMaintenance(enabled){if(!maintenanceState)throw Error(localized('업데이트 설정 상태를 먼저 확인해 주세요.','Check update settings first.'));maintenanceState=await request('settings/maintenance/settings',{revision:maintenanceState.revision,enabled});maintenanceLoaded=true;renderMaintenance();}
function formBody(next){
 const chosenCodex=$('client').value==='codex';
 const freshPreferred=state.selection.mode==='subscription'&&state.selection.client_models.codex===preferredCodexId;
 const preserveCodex=state.configured||codexChoiceTouched||chosenCodex||freshPreferred;
 const includeEffort=state.selection.codex_reasoning_effort!==undefined||codexChoiceTouched||!preserveCodex;
 const body={revision:state.revision,onboarding_step:next,setup_area:step===3?'jev':'ai',selection:{mode:'subscription',client:$('client').value,client_models:Object.fromEntries(['codex','claude','opencode'].map(id=>[id,id==='codex'&&!preserveCodex?null:$(id+'-model').value||null])),...(includeEffort?{codex_reasoning_effort:preserveCodex?$('codex-reasoning').value||null:null}:{}),role_model_mode:state.selection.role_model_mode||'inherit',...(state.selection.role_models?{role_models:state.selection.role_models}:{}),api_to_subscription:state.selection.mode==='api',api_provider:state.selection.api_provider,api_model:state.selection.api_model||'',api_base_url:state.selection.api_base_url||'',reasoning:state.selection.reasoning,jev:$('jev-mode').value}};
 for(const name of ['jev']){const value=$(name+'-key').value.trim();if($('remove-'+name).checked){body[name+'_action']='remove';}else if(value){body[name+'_action']='replace';body[name+'_key']=value;}}
 return body;
}
async function save(next=step){const body=formBody(next);if(!body.inherit_global&&body.selection.mode==='subscription'&&body.selection.client==='codex'&&clientCatalogs.codex?.status==='available'&&body.selection.client_models.codex&&!clientCatalogs.codex.models.some(row=>row.id===body.selection.client_models.codex))throw Error(localized('이 계정에서 쓸 수 없는 Codex 모델입니다. 목록에서 다시 선택하세요.','This Codex model is not in the current account catalog. Select a listed model.'));const maintenanceChoice=step===2?$('cli-auto-update').checked:null;const updated=await request('settings/save',body);state={...state,...updated};codexChoiceTouched=false;codexEffortTouched=false;if(maintenanceChoice!==null)await saveMaintenance(maintenanceChoice);if(state.work_model_data?.editable&&step===2&&$('work-data').checked!==Boolean(state.work_model_data.approved)){const status=await request('settings/work-data',{approved:$('work-data').checked});state={...state,work_model_data:status.work_model_data};}$('jev-key').value='';$('remove-jev').checked=false;populate();notice('저장했습니다.');}
async function refreshMcp(){
  notice('설치·로그인·MCP 상태 확인 중…');
  const checked=await request('settings/mcp/check',{});mcpState=checked.mcp;bootstrapState=checked.bootstrap;
  $('driver-state').textContent=mcpState.agent_driver.installed?'Agent Office 준비됨':'Agent Office 확인 필요';$('driver-state').className='badge '+(mcpState.agent_driver.installed?'ok':'warn');
  const list=$('mcp-clients');list.replaceChildren();
  const registrations=new Map(mcpState.clients.map(item=>[item.id,item]));
  const connections=new Map(bootstrapState.connections.map(item=>[item.id,item]));
  for(const client of bootstrapState.clients){
    const registration=registrations.get(client.id),connection=connections.get(client.id),card=document.createElement('div');card.className='client';card.dataset.client=client.id;
    const stateLabel=!client.installed?'설치 필요':['signed_out','expired'].includes(connection?.status)?'로그인 필요':registration?.registration==='registered'?'MCP 등록됨':registration?.registration==='conflict'?'설정 검토 필요':'MCP 등록 필요',tone=!client.installed?'idle':registration?.registration==='registered'&&!['signed_out','expired'].includes(connection?.status)?'ok':registration?.registration==='conflict'?'err':'warn';
    const row=clientRow(client.label,stateLabel,tone,client.id),actions=row.querySelector('.cact');card.append(row);
    const flow=document.createElement('div');flow.className='device';flow.hidden=true;flow.id='agent-flow-'+client.id;card.append(flow);
    if(!client.installed){
      if(client.managed_install){const install=document.createElement('button');install.textContent='설치';install.setAttribute('aria-label',client.label+' 설치');install.onclick=()=>installAction(client.id);actions.append(install);}
    }else{
      if(['signed_out','expired'].includes(connection?.status)){const kind=connection.supported_login_flows.includes('device')?'device':connection.supported_login_flows[0];if(kind){const login=document.createElement('button');login.textContent='로그인';login.className='login-action';login.setAttribute('aria-label',client.label+' 로그인');login.onclick=()=>loginAction(client.id,kind);actions.append(login);}}
      if(registration?.automatic&&registration.registration==='not_registered'&&!['signed_out','expired','needs_login','challenge'].includes(connection?.status)){const button=document.createElement('button');button.textContent='연결';button.setAttribute('aria-label',client.label+' MCP 연결');button.className='primary';button.onclick=()=>action(async()=>{mcpState=await request('settings/mcp/register',{client:client.id});await refreshMcp();});actions.append(button);}
      if(registration?.registration==='registered'&&connection?.status==='ready')addClientManage(actions,client.id,client.label);
    }
    list.append(card);renderFlow(connection?.connection||{client_id:client.id,state:'idle'});
  }
  const bridge=mcpState.windows_bridge;
  $('windows-bridge').hidden=!bridge;$('windows-title').hidden=!bridge;
  if(bridge)$('windows-bridge-config').textContent=JSON.stringify({command:bridge.command,args:bridge.args},null,2);
  $('mcp-next').disabled=!(mcpState.registered_count||bridge);stepMarks();compactHints(document.body);
  notice(mcpState.registered_count?'WSL 앱의 MCP 등록을 확인했습니다.':bridge?'위에서 WSL 앱을 연결하거나, 아래 Windows 연결을 펼쳐 등록하세요.':'앱 하나를 설치하고 MCP를 등록하세요.');
}
async function refreshClients(force=false){if(force===true)notice('연결 상태 확인 중…');// A forced check also drops the remembered model lists on the host, so the lists are asked for after it.
const [data,models]=force===true?[await request('settings/refresh',{force:true}),await request('settings/models')]:await Promise.all([request('settings/refresh',{}),request('settings/models')]);clientCatalogs=models;
  const codex=models.codex,listed=codex?.status==='available',prior=$('codex-model').value;
  const recommended=!state.configured&&!codexChoiceTouched&&listed&&codex.models.some(row=>row.id===preferredCodexId)?preferredCodexId:null;
  for(const id of ['codex','claude','opencode'])fillModels(id+'-model',models[id]?.models||[],id==='codex'&&recommended!==null?recommended:$(id+'-model').value);
  if(recommended&&!codexEffortTouched)$('codex-reasoning').value='low';
  const unsupported=listed&&Boolean(prior)&&!codex.models.some(row=>row.id===prior);
  $('catalog-state').textContent=localized('현재 확인: ','Checked: ')+['codex','claude'].map(id=>id+' '+(models[id]?.status==='available'?localized(models[id].models.length+'개',models[id].models.length+' models'):localized('목록 미확인','Catalog unverified'))).join(' · ')+(unsupported?state.configured?localized(' · 저장한 Codex 모델을 이 계정에서 쓸 수 없습니다. 목록에서 다시 선택하세요.',' · The saved Codex model is not in the current account catalog. Select a listed model.'):localized(' · 새 기본 Codex 모델은 현재 계정 목록에 없습니다. 지원 모델을 선택하세요.',' · The new default Codex model is not in this account catalog. Select a listed model.'):recommended?localized(' · 요청한 Codex 6.1 Sol을 현재 계정 목록에서 확인했습니다.',' · Requested Codex 6.1 Sol is listed for this account.'):!listed?localized(' · Codex 계정 지원 여부는 아직 확인되지 않았습니다.',' · Codex account availability has not been checked.'):'')+localized(' · Claude 목록은 계정 지원 확인이 아닙니다.',' · Claude choices do not prove account access.');notice('확인했습니다.');}
async function refreshModelChoices(){const models=await request('settings/models');clientCatalogs=models;for(const id of ['codex','claude','opencode'])fillModels(id+'-model',models[id]?.models||[],$(id+'-model').value);$('catalog-state').textContent=localized('CLI 업데이트 후 모델 목록을 새로 가져왔습니다. 선택은 그대로입니다. Claude 모델은 계정에 따라 쓸 수 없을 수 있습니다.','The model list was refreshed after the CLI update. Your selection is unchanged. Some Claude models may not be available to your account.');clientsLoaded=true;}
function renderFlow(flow){const url=flow.auth_url||flow.device_url,tab=authWindows.get(flow.client_id);if(url&&tab&&!tab.closed){tab.location.replace(url);authWindows.delete(flow.client_id);}if(['completed','failed','unavailable'].includes(flow.state))closeAuthWindow(flow.client_id);for(const target of [$('flow-'+flow.client_id),$('agent-flow-'+flow.client_id)].filter(Boolean)){if(flow.state==='idle'||flow.state==='unavailable'&&flow.reason==='login_contract_unavailable'){target.hidden=true;target.replaceChildren();continue;}target.hidden=false;target.replaceChildren();const text=document.createElement('span');text.textContent=({starting:'인증 화면 준비 중…',waiting:url?'공식 인증 화면에서 인증을 마쳐주세요.':'인증 화면 준비 중…',completed:'로그인 완료 · 상태를 다시 확인합니다.',failed:'로그인을 완료하지 못했습니다. 로그인 버튼으로 다시 시도하세요.',unavailable:'설치는 유지됩니다. 다시 확인 후 로그인을 다시 누르세요.'})[flow.state]||flow.state;target.append(text);if(url){const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noreferrer';link.className='action-link';link.textContent='인증 열기';target.append(link);}if(flow.user_code){const code=document.createElement('code');code.textContent=flow.user_code;target.append(code);}}}
async function pollFlows(){try{const data=await request('settings/flows');data.flows.forEach(renderFlow);if(!data.flows.some(f=>['starting','waiting'].includes(f.state))){clearInterval(flowTimer);if(step===0)await refreshMcp();else if(step===2)await refreshClients(true);}}catch{clearInterval(flowTimer);}}
function appendActivity(event){const ko=window.officeLang==='ko',time=new Date(event.at).toLocaleTimeString(ko?'ko-KR':'en-GB',{hour12:false}),status=(ko?{running:'진행',success:'완료',warning:'확인 필요',error:'실패',info:'기록'}:{running:'running',success:'done',warning:'needs attention',error:'failed',info:'log'})[event.state]||(ko?'기록':'log'),message=window.officeText(event.message);if($('setup-log').dataset.empty==='true'){$('setup-log').textContent='';$('setup-log').dataset.empty='false';}$('setup-log').textContent+=time+' ['+event.area.toUpperCase()+' · '+status+'] '+message+'\\n';$('setup-log').scrollTop=$('setup-log').scrollHeight;$('tail-last').textContent=message;}
let maintenanceCatalogRefreshTimer;const activitySource=new EventSource('settings/activity');activitySource.onopen=()=>{$('tail-state').textContent='실시간 연결됨';};activitySource.onerror=()=>{$('tail-state').textContent='재연결 중';};activitySource.onmessage=message=>{const value=JSON.parse(message.data);if(value.kind==='snapshot'){$('setup-log').textContent='';$('setup-log').dataset.empty='false';if(value.events.length)value.events.forEach(appendActivity);else{$('setup-log').textContent='아직 연결 작업 기록이 없습니다.';$('setup-log').dataset.empty='true';}}else if(value.kind==='activity'){appendActivity(value.event);if(value.event.message==='CLI 업데이트 확인을 마쳤습니다. 모델 목록을 새로고침하세요.'){clearTimeout(maintenanceCatalogRefreshTimer);maintenanceCatalogRefreshTimer=setTimeout(()=>{if(!initialized||busy||step!==2){clientsLoaded=false;return;}void action(async()=>{await loadMaintenance();await refreshModelChoices();});},900);}}};
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>action(()=>show(Number(b.dataset.step))));
// 상태는 사용자가 새로고침하지 않아도 주기적으로 다시 읽는다(화면이 보일 때만, 다른 작업 중이 아닐 때만).
const POLL_MS=60_000;let lastPoll={0:0,1:0};function pollNote(id,at){const node=$(id);if(node)node.textContent=at?localized('마지막 확인 ','Last check ')+new Date(at).toLocaleTimeString(window.officeLang==='ko'?'ko-KR':'en-GB',{hour12:false}):'';}
async function pollStep(){if(!initialized||busy||document.visibilityState!=='visible')return;if(step===0){await action(refreshMcp);lastPoll[0]=Date.now();pollNote('mcp-poll-note',lastPoll[0]);}else if(step===1){void refreshSiteLogins();await action(refreshBrowserSetup);lastPoll[1]=Date.now();pollNote('browser-poll-note',lastPoll[1]);}}
setInterval(pollStep,POLL_MS);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&Date.now()-(lastPoll[step]||0)>POLL_MS)void pollStep();});
document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>action(()=>show(Number(b.dataset.next))));
document.querySelectorAll('[data-save-next]').forEach(b=>b.onclick=()=>action(async()=>{const next=Number(b.dataset.saveNext);await save(next);await show(next);}));
$('copy-windows-bridge').onclick=()=>action(async()=>{await navigator.clipboard.writeText($('windows-bridge-config').textContent);notice('Windows 앱용 MCP 연결 정보를 복사했습니다. 앱에 등록한 뒤 MCP 목록에서 연결을 확인하세요.');});
$('client').onchange=()=>clientFields();
$('codex-model').onchange=()=>{codexChoiceTouched=true;if(!state.configured&&!codexEffortTouched)$('codex-reasoning').value=$('codex-model').value===preferredCodexId?'low':'';};
$('codex-reasoning').onchange=()=>{codexChoiceTouched=true;codexEffortTouched=true;};
$('jev-mode').onchange=jevFields;
$('refresh-mcp').onclick=()=>action(refreshMcp);
$('cli-auto-update').onchange=()=>{const enabled=$('cli-auto-update').checked;if(!state.configured){notice(localized('AI 설정을 저장하면 자동 업데이트 선택도 함께 저장됩니다.','Save AI settings to apply the automatic update preference.'));return;}void action(async()=>{try{await saveMaintenance(enabled);notice(localized('CLI 자동 업데이트 설정을 저장했습니다.','CLI automatic update preference saved.'));}catch(error){renderMaintenance();throw error;}});};
$('cli-update-now').onclick=()=>action(async()=>{if(!maintenanceState||maintenanceState.state==='running')return;const result=await request('settings/maintenance/update-now',{});await loadMaintenance();if(Array.isArray(result.updated_ids)&&result.updated_ids.length)await refreshClients(true);notice(result.state==='deferred_busy'?localized('업무 실행 중이라 업데이트를 미뤘습니다.','Update deferred while work is active.'):result.updated_ids?.length?localized('CLI 업데이트를 확인했습니다. 모델 목록을 다시 불러왔습니다.','CLI update checked; model catalogs refreshed.'):localized('CLI 업데이트 확인을 마쳤습니다. 상태를 확인하세요.','CLI update check finished. Review the status.'));});
$('connect-computer').onclick=()=>action(async()=>{state=await request('settings/computer',{mode:'non_interfering'});populate();await show(2);});
$('save-model').onclick=()=>action(()=>save(Math.max(2,state.onboarding_step)));
$('save-jev').onclick=()=>action(()=>save(Math.max(3,state.onboarding_step)));
$('remove-jev-btn').onclick=()=>action(async()=>{if(!confirm(localized('저장된 Jev 키를 삭제할까요?','Delete the saved Jev key?')))return;$('remove-jev').checked=true;await save(Math.max(3,state.onboarding_step));});
$('finish').onclick=()=>action(async()=>{await save(4);await show(4);});
async function initialize(){lockControls(true);$('retry-settings').hidden=true;notice('설정을 불러오는 중…');try{const [value,mcp,bootstrap]=await Promise.all([request('settings/status'),request('settings/mcp'),request('settings/bootstrap')]);state=value;mcpState=mcp;bootstrapState=bootstrap;initialized=true;populate();notice('');await action(async()=>{await show(location.hash==='#browsers'?1:!mcp.registered_count&&!state.computer.connected?0:!state.computer.connected?1:Math.min(4,Math.max(2,state.onboarding_step)));});}catch{initialized=false;lockControls(true);notice('설정을 불러오지 못했습니다. 다시 시도해 주세요.');$('retry-settings').hidden=false;}}
const retrySettings=document.createElement('button');retrySettings.id='retry-settings';retrySettings.textContent='설정 다시 불러오기';retrySettings.hidden=true;retrySettings.onclick=initialize;$('notice').after(retrySettings);
${browserSetupScript}
${deliverySettingsScript}
void initialize();
</script></html>`;}
