/** Shared phrases used by bilingual result, import, bot and connection views.
 * These are product strings only, not model replies or user-authored instructions. */
export const extraSourceCopy: Record<string, string> = {
  'Jev 추천 · 한 곳': 'Jev suggestion · one step',
  '이곳을 선정한 이유': 'Why this step',
  '기대 효과': 'Expected benefit',
  '코드 근거와 판단 방식': 'Code evidence and decision method',
  '현재 처리': 'Current approach',
  '반복 근거': 'Why it repeats',
  '필요한 입력': 'Information needed',
  '불확실할 때': 'When uncertain',
  '짧은 판단': 'Short decision',
  'Jev가 맞는 이유': 'Why Jev fits',
  '보기 중 하나 고르기': 'Choose one option',
  '예/아니오 확인': 'Yes or no decision',
  '정도 비교': 'Compare scores',
  '에서 로그인하세요.': ' to sign in.',
  '연결 확인됨 · 사용 허용 필요': 'Connection verified · permission needed',
  '기존 로그인 확인됨': 'Existing sign-in verified',
  '설치됨 · 로그인 재확인 필요': 'Installed · check sign-in again',
  '공식 로그인 시작 · 브라우저에서 승인하세요': 'Sign-in started · approve in your browser',
  '후속 단계가 새 결과를 받습니다. 각 후속 단계의 기존 목표 문구는 자동으로 바뀌지 않으므로 확인하세요.': 'Later stages receive the new result. Their existing goals do not change automatically; review them.',
  '사용자가 일시정지함 · 진행 중인 외부 변경은 결과 확인 전까지 재개할 수 없음': 'Paused by you · ongoing external changes require outcome confirmation before resuming',
  '모든 단계의 독립 결과 확인과 품질 승인': 'Independent result and quality checks for every stage',
  '저장된 실행 계획을 바탕으로 한 반복 방법 초안이며 Task Pack 승격은 별도 검증이 필요함': 'Draft repeat procedure from the saved plan · Pack promotion requires separate verification',
  '계정 지원 미확인': 'Account access not verified',
  'Codex 계정 지원 여부는 아직 확인되지 않았습니다.': 'Codex account access has not been verified.',
  '범위 제한으로 일부만 확인': 'Only part of the scope was checked',
  '수동 확인 필요': 'Check manually',
  '파일 작업을 완료하지 못했습니다: ': 'Could not finish the file task: ',
  '기존 실행 환경에서 원래 예약을 유지합니다.': 'The original runtime keeps its existing schedule.',
  '근거가 연결된 업무 단계의 실행 보고 기준 · 독립 검증은 결과에서 별도 확인': 'Progress uses evidence-linked stage reports · independent verification is shown with the result',
  '저장됨 · 발송 연결 미확인': 'Saved · sending connection unverified',
  '연결 정보 필요': 'Connection details needed',
  '대상 이름': 'Destination name',
  '새 토큰을 입력하거나 비워 두세요': 'Enter a new token or leave blank',
  '채팅 ID': 'Chat ID',
  '새 URL을 입력하거나 비워 두세요': 'Enter a new URL or leave blank',
  '연결된 메신저가 없습니다. 필요한 플랫폼만 추가하세요.': 'No messenger is connected. Add only the platforms you need.',
  '이 앱': 'This app',
  '기본 전달 대상을 하나 이상 선택하세요.': 'Select at least one default destination.',
  '전달 설정을 저장했습니다. 실제 전송은 결과가 생길 때 확인됩니다.': 'Delivery settings saved. Actual delivery is checked when a result is available.',
  '전달 대상은 최대 20개까지 저장할 수 있습니다.': 'You can save up to 20 destinations.',
  '앱': 'App',
  '대상 연결 정보가 바뀌어 전송을 멈췄습니다.': 'Destination details changed; delivery stopped.',
  '대상 선택을 바꿔 미전송 건을 취소했습니다.': 'Unsent delivery was canceled after destinations changed.',
  '전송 여부가 불확실합니다. 메신저에서 수신 여부를 확인하세요.': 'Delivery is uncertain. Check the messenger before retrying.',
  '전송 확인을 받지 못했습니다. 메신저에서 수신 여부를 확인하세요.': 'No valid receipt was received. Check the messenger before retrying.',
  '전송 중 연결이 끊겼습니다. 메신저에서 수신 여부를 확인하세요.': 'Delivery was interrupted. Check the messenger before retrying.',
  '본문이 길어 해당 메신저로 보내지 못했습니다.': 'The result text exceeds this messenger’s limit.',
  '인증 또는 권한이 거절됐습니다. 연결 정보를 확인하세요.': 'Authentication or permission was denied. Check connection details.',
  '대상을 찾을 수 없습니다. 연결 대상을 확인하세요.': 'Destination not found. Check the connected destination.',
  '전송 한도에 걸렸습니다. 잠시 뒤 다시 시도하세요.': 'Rate limited. Try again later.',
  '메신저가 본문을 거절했습니다. 길이와 형식을 확인하세요.': 'The messenger rejected the result text. Check its length and format.',
  '전달 상태를 확인해야 합니다.': 'Delivery needs review.',
  '메신저 연결하기': 'Connect a messenger',
  '원본에서 전달 · 여부 미확인': 'Original runtime delivery · unobserved',
  '앱에서 확인 가능': 'Available in this app',
  '전달 완료': 'Delivered', '전달 실패': 'Failed', '전달 중': 'Sending',
  '전달 결과 확인 필요': 'Review delivery outcome', '전달 여부 미확인': 'Delivery unobserved',
  '검증 대기 · 앱에서 초안 확인': 'Awaiting verification · draft available in app',
  '결과 생성 후 전달 상태가 표시됩니다.': 'Delivery status appears after a result is created.',
  '이 업무의 결과 전달은 원본 실행 환경이 맡습니다. 여기서는 전달 여부를 확인하거나 대상을 바꿀 수 없습니다.': 'The original runtime manages result delivery for this work. Office cannot verify delivery or change its destinations.',
  '변경 사항은 아직 보내지 않은 결과에만 적용됩니다. 이미 보낸 결과는 다시 전송하지 않습니다.': 'Changes apply only to unsent results. Delivered results are not sent again.',
  '전달 대상': 'Destinations', '전달 설정을 불러오는 중…': 'Loading delivery settings…',
  '전달 설정을 읽지 못했습니다.': 'Could not load delivery settings.',
  '전달 대상을 하나 이상 선택하세요.': 'Select at least one destination.',
  '저장하지 못했습니다.': 'Could not save.', '이후 전송할 결과의 대상을 저장했습니다.': 'Destinations saved for future sends.',
  '확인하는 동안 원본이 바뀌었습니다. 목록에서 다시 선택해 검토해 주세요.': 'The original changed during review. Select it again from the list.',
  '이미 연결된 업무가 있습니다. 기존 업무를 확인해 주세요. 새 내용으로 자동 덮어쓰지 않습니다.': 'This work is already connected. Review it first. New content does not overwrite it automatically.',
  '이미 등록한 내용과 다릅니다. 기존 업무를 확인해 주세요.': 'This differs from the saved work. Review the existing work.',
  '이미 실행한 이력이 있어 가져오기를 취소할 수 없습니다. 업무 상세에서 일시정지하세요.': 'This work has already run, so its import cannot be canceled. Pause it in the work detail.',
  '지침에 비밀번호·토큰 같은 값이 들어 있습니다. 값은 빼고 필요한 연결 종류만 적어 주세요.': 'The instructions contain a password or token. Remove the value and describe the connection needed instead.',
  'Hermes 데이터 폴더를 찾지 못했습니다. 실행 환경의 경로를 확인해 주세요.': 'Hermes data folder not found. Check its path on the execution computer.',
  '선택한 폴더에서 Hermes 대화나 예약을 찾지 못했습니다.': 'No Hermes conversations or schedules were found in this folder.',
  '원본의 특수 실행 설정을 그대로 보존할 수 없습니다. 표시된 제한을 확인해 주세요.': 'Some original execution settings cannot be preserved. Review the limitations shown.',
  '가져오기를 완료하지 못했습니다.': 'Could not finish the import.',
  '가져오기 요청을 처리하는 중…': 'Processing the import…', '예약': 'Schedule', '대화': 'Conversation',
  '가져올 업무를 선택하세요. 아직 아무것도 실행하지 않았습니다.': 'Choose work to import. Nothing has run yet.',
  '원본을 읽어 초안을 만들었습니다. 목표·지침·완료 조건을 확인해 주세요.': 'Draft created from the original. Review its goal, instructions and completion criteria.',
  '이전 기록을 불러왔습니다.': 'Previous records loaded.',
  '가져오기 완료 · 실행 대기': 'Imported · not started', '가져오기 연결 취소됨': 'Import connection canceled',
  '변경 전 백업 보관': 'Backup kept from before the change', '업무 등록 전': 'Not registered yet',
  '연결만 취소했습니다. 원본과 이전 기록은 보존했습니다.': 'Connection canceled. The original and previous records are kept.',
  '확인 체크를 선택해 주세요. 등록해도 바로 실행하지 않습니다.': 'Select the confirmation checkbox. Registering does not start execution.',
  '이미 등록된 같은 업무를 연결했습니다.': 'Connected to the existing work.',
  '업무를 등록했습니다. 실행은 다음 지시를 보낼 때 시작합니다.': 'Work registered. It starts when you send the next instruction.',
  '지시 대기': 'Waiting for instructions', 'Hermes 연결 중': 'Connecting to Hermes',
  '실행 중': 'Running', '답변 도착': 'Reply received', '연결 또는 실행 실패': 'Connection or execution failed',
  '중단 결과 확인 필요': 'Check the stopped action', '가져오기 연결 해제': 'Disconnect imported work',
  '첫 지시를 보낼 때 전용 Hermes 세션을 만듭니다.': 'A dedicated Hermes session is created when you send the first instruction.',
  '배정 재개': 'Resume assignments', '이전 기록 · 첫 실행 전 연결 취소': 'Previous records · disconnect before the first run',
  '이번에 실행할 지시를 입력해 주세요.': 'Enter the instruction to run now.',
  'Hermes 모델 사용량 안내를 확인해 주세요.': 'Confirm that this uses the Hermes model allowance.',
  'Office 연결이 해제되어 있습니다. 원본 작업은 변경하지 않습니다.': 'Office is disconnected. The original work is unchanged.',
  '요청을 저장하는 중…': 'Saving request…', 'Hermes 요청 실패': 'Hermes request failed',
  '지시를 접수했습니다. Hermes의 진행과 답변이 여기에 표시됩니다.': 'Instruction received. Hermes activity and replies will appear here.',
  '새 지시를 보낼 수 있습니다. 자동 재실행은 하지 않습니다.': 'You can send a new instruction. Nothing is rerun automatically.',
  '요청을 반영했습니다.': 'Request applied.',
  '시간 초과': 'Timed out', '부분 완료': 'Partially complete',
  '대화 턴 완료 · 업무 미확인': 'Reply received · work not verified',
  '승인됨 · 업무 미확인': 'Approved · work not verified', '로그인 대기': 'Waiting for sign-in',
  '컴퓨터': 'Computer', '브라우저': 'Browser', '개발 도구': 'Developer tools', 'AI 판단': 'AI decisions',
  '작동 중': 'Running', '설정됨': 'Configured', '미설정': 'Not configured', '사용 불가': 'Unavailable',
  '단계별 진행률 미관측': 'Stage progress not reported', '최근 실행': 'Latest run',
  '아직 최종 결과 미검증': 'Final result not verified yet', '결과 요약이 저장되지 않았습니다.': 'No result summary has been saved.',
  '초안': 'Draft', '미기록': 'Not recorded', '승인': 'Approval', '미승인': 'Not approved',
  '이 단계만 변경됩니다.': 'Only this stage changes.',
  '다음 배정에 새 지침이 적용됩니다.': 'The new instruction applies to the next assignment.',
  '다시 진행합니다.': 'Resuming.', '업무 현황 연결 실패': 'Could not connect to the work view.',
  '단계 상태가 바뀌어 수정이 중단되었습니다.': 'The stage changed, so editing stopped.',
  '실시간 연결 재시도 중': 'Reconnecting live updates…',
  '다음 지시 대기': 'Waiting for the next instruction', '서버 실행 접수': 'Server execution requested',
  '서버 상태 대조 필요': 'Check server state', '상태 확인 전': 'Not checked yet',
  '서버 실행 종료': 'Server run ended', '중단 확인': 'Check the stopped run',
  '수신 여부 확인 필요': 'Check receipt', '실행 실패': 'Execution failed',
  '서버에 연결하지 못했습니다. Office 실행 환경의 SSH 키·서버 신뢰 등록·접속 권한을 확인하세요.': 'Could not connect to the server. Check the SSH key, trusted host and access permissions on the Office computer.',
  '먼저 서버 상태를 새로 확인하고 이전 결과를 검토해 주세요.': 'Refresh the server state and review the previous result first.',
  '서버가 중단을 확인하지 않았습니다. 상태를 새로 확인하세요.': 'The server has not confirmed the stop. Refresh its state.',
  '서버의 종료 여부가 불확실합니다. 같은 지시를 다시 보내지 않습니다.': 'It is unclear whether the server stopped. The same instruction will not be sent again.',
  '상태가 바뀌었습니다. 최신 상태에서 다시 확인해 주세요.': 'The state changed. Refresh and check again.',
  '원격 요청 실패': 'Remote request failed', '서버를 선택하고 업무를 찾으세요.': 'Choose a server and find its work.',
  '먼저 서버 연결을 추가하세요.': 'Add a server connection first.',
  '연결 정보를 저장했습니다. 서버 업무 찾기로 접속을 확인하세요.': 'Connection saved. Select Find server work to check access.',
  '서버 설정': 'Server settings',
  '고른 서버의 이름과 접속 정보예요. 이 서버를 지켜보는 업무 모두에 적용돼요.': 'The chosen server\'s name and connection. It applies to every Work that watches this server.',
  '설정 저장': 'Save settings',
  '먼저 서버 연결을 선택하세요.': 'Select a server connection first.',
  '서버에서 대화·예약 목록을 읽고 있습니다. 실행하지 않습니다.': 'Reading server conversations and schedules. Nothing is being started.',
  '예약 · 조회 전용': 'Schedule · view only',
  '서버 업무를 연결했습니다. 실행하거나 예약을 복제하지 않았습니다.': 'Server work connected. No run was started and no schedule was copied.',
  '가져올 업무의 Office에 연결 버튼을 누르세요.': 'Select Connect to Office for the work to import.',
  '아직 없음': 'None yet', 'OpenClaw 답변': 'OpenClaw reply', '사용자 지시': 'Your instruction',
  '서버 모델 사용량 안내를 확인해 주세요.': 'Confirm that this uses the server model allowance.',
  '지시를 입력하세요.': 'Enter an instruction.', '서버 상태를 확인하고 있습니다.': 'Checking server state…',
  '서버에 요청을 전달하고 있습니다.': 'Sending the request to the server…',
  '연결을 확인하지 못했습니다. 마지막 기록을 보존했습니다.': 'Connection not verified. The last record is kept.',
  '서버 응답을 반영했습니다.': 'Server response received.',
  '공식 로그인 화면을 준비하고 있습니다. 이 창은 자동으로 이동합니다.': 'Preparing the official login page. This window will continue automatically.',
  '업데이트 확인 예정': 'Update check scheduled', '대기 중': 'Waiting', '업데이트 중': 'Updating',
  '업무 실행 중 · 보류': 'Deferred · work is running', '다음 확인 대기': 'Waiting for the next check',
  '자동 확인은 AI 설정 저장 후 적용': 'Automatic checks start after saving AI settings',
  '24시간 간격': 'Every 24 hours', '미설치': 'Not installed', '자동 관리': 'Managed automatically',
  '관리 밖 설치': 'Installed separately', '플랫폼 미지원': 'Unsupported platform',
  '자동 방식 없음': 'No automatic update method', '수동 관리': 'Managed manually',
  '업데이트 설정 상태를 확인하지 못했습니다. AI 연결은 계속 사용할 수 있습니다.': 'Could not check update settings. Your AI connection is still available.',
  '업데이트 설정 상태를 먼저 확인해 주세요.': 'Check the update settings first.',
  '이 계정에서 쓸 수 없는 Codex 모델입니다. 목록에서 다시 선택하세요.': 'This Codex model is unavailable for your account. Choose another from the list.',
  '목록 미확인': 'Catalog unavailable',
  'CLI 업데이트 후 모델 목록을 새로 가져왔습니다. 선택은 그대로입니다. Claude 모델은 계정에 따라 쓸 수 없을 수 있습니다.': 'Model lists refreshed after the CLI update. Your selections are unchanged. Claude model access depends on your account.',
  '진행': 'Running', '기록': 'Record',
  'AI 설정을 저장하면 자동 업데이트 선택도 함께 저장됩니다.': 'Saving AI settings also saves your automatic update choice.',
  'CLI 자동 업데이트 설정을 저장했습니다.': 'Automatic CLI update setting saved.',
  '업무 실행 중이라 업데이트를 미뤘습니다.': 'Update deferred while work is running.',
  'CLI 업데이트를 확인했습니다. 모델 목록을 다시 불러왔습니다.': 'CLI updates checked. Model lists refreshed.',
  'CLI 업데이트 확인을 마쳤습니다. 상태를 확인하세요.': 'CLI update check finished. Review the status.',
  '연결 상태가 바뀌었습니다. 목록을 다시 확인하세요.': 'The connection changed. Refresh the list.',
  '이미 다른 업무에 연결된 실행 환경입니다.': 'This execution environment is already connected to another work item.',
  '원본 실행 연결이 변경되었습니다. 연결 설정을 확인하세요.': 'The original runtime connection changed. Review its settings.',
  '이 연결은 해당 제어를 지원하지 않습니다.': 'This connection does not support that action.',
  '업무 상태가 바뀌었습니다. 최신 상태에서 다시 시도하세요.': 'The work state changed. Refresh and retry.',
  '원본 실행 연결': 'Original runtime connection', '기존에 등록된 실행 연결을 선택하세요.': 'Select a registered runtime connection.',
  '실행 연결': 'Runtime connection', '연결 선택': 'Choose connection', '조회 전용': 'View only',
  '연결 찾기': 'Find connections',
  '등록된 실행 연결이 없습니다. 아래 가져오기에서 Hermes 또는 원격 서버의 업무를 연결하세요.': 'No runtime connections are registered. Import work from Hermes or a remote server below.',
  '실행 연결 등록': 'Register runtime connection', '마지막 확인': 'Last checked', '상태 확인': 'Check status', '재개': 'Resume',
  '실행 연결의 설정이 바뀌었습니다. 원본 연결을 확인하세요.': 'Runtime settings changed. Check the original connection.',
  '다음 지시': 'Next instruction',
  '연결된 모델의 사용량이 발생할 수 있음을 확인했습니다.': 'I understand this may use the connected model allowance.',
  '지시 전달': 'Send instruction', '최근 답변': 'Latest reply',
  '연결하면 원본의 실행 기록을 이 업무에서 볼 수 있습니다. 기존 봇·예약·전달은 원래 환경에서 그대로 동작합니다.': 'Connect to see the original execution records here. The existing bot, schedule and delivery stay in their original environment.',
  'Hermes 연결은 Office에 등록된 세션만 제어합니다. 별도로 실행 중인 봇과 예약은 자동 제어하지 않습니다.': 'Hermes connections control only sessions registered in Office. Other running bots and schedules are not controlled automatically.',
  '이 예약 연결은 실행 기록만 조회합니다. 예약 실행·중단은 원본 서버가 관리합니다.': 'This schedule connection only reads execution records. The original server manages scheduled starts and stops.',
  '여기서 반복 실행을 켜면 기존 플랫폼의 예약은 직접 꺼 주세요. 둘 다 켜 두면 양쪽에서 실행됩니다.': 'If you enable recurring runs here, turn off the original platform schedule. Leaving both on runs the work in both places.',
  '연결 요청 처리 중…': 'Processing connection…', '등록된 실행 연결을 확인하는 중…': 'Checking registered runtime connections…',
  '연결할 원본 실행을 선택하세요.': 'Select the original runtime to connect.',
  '먼저 원본 실행 연결을 등록하세요.': 'Register the original runtime connection first.',
  '원본 실행을 연결하는 중…': 'Connecting the original runtime…',
  '연결했습니다. 원본 실행의 기록과 제어를 확인할 수 있습니다.': 'Connected. Original runtime records and controls are now available.',
  '원본 실행에 요청하는 중…': 'Requesting the original runtime…', '원본 실행의 응답을 반영했습니다.': 'Original runtime response received.',
  '결과': 'Results', '아직 저장된 결과가 없습니다.': 'No saved results yet.',
  '실행기가 보고한 결과': 'Result reported by the execution tool', '결과 근거 확인됨': 'Result evidence verified',
  '업무 완료조건 확인됨': 'Work completion criteria verified', '원본 보고 · 독립 확인 전': 'Reported by the original runtime · not independently verified',
  '기존 실행 환경이 전달을 담당합니다.': 'The original runtime handles delivery.',
  '출처': 'Sources', '파일': 'Files', '결과 내용': 'Result text',
  '완료조건 확인 여부는 각 회차의 결과에 표시합니다.': 'Each run shows whether its completion criteria were verified.',
  '전달 다시 시도': 'Retry delivery', '후보': 'Candidate', '정식': 'Ready for reuse',
  '연속 실패로 중지': 'Disabled after consecutive failures', '절차': 'Procedure', '단계': 'Stage',
  '켜기': 'Turn on', '끄기': 'Turn off', '아직 없습니다. 업무가 검증을 통과하면 여기에 쌓입니다.': 'Nothing here yet. Procedures appear after work passes verification.',
  '공개 출처': 'Public sources', '잊기': 'Forget', '아직 없습니다.': 'Nothing here yet.',
  '목록을 불러오지 못했습니다.': 'Could not load the list.', '변경하지 못했습니다.': 'Could not change this.',
  '세션 확인 필요': 'Check the session', '자료 조회 시도': 'Source read attempted',
  '업무 단계 실행 보고 · 독립 검증 대기': 'Stage execution reported · awaiting independent verification',
  '완료 검증 AI의 응답 시간이 초과됐습니다. 기존 결과는 보존됩니다.': 'The completion-check AI timed out. Existing results are kept.',
  'Agent Office가 AI에 보낸 요청 형식에 오류가 있습니다. 로그인이나 사용량 문제가 아니라 앱 오류이니, 앱을 업데이트한 뒤 다시 시도해 주세요.': 'Agent Office sent an invalid AI request. This is an app error, not a sign-in or quota issue. Update the app and retry.',
  '일부 단계의 결과를 뒷받침할 근거가 부족합니다. 그 단계의 지침을 고쳐 다시 확인해 보세요.': 'Some stages have insufficient supporting evidence. Update their instructions and check again.',
  '선택한 모델을 현재 연결된 클라이언트에서 사용할 수 없습니다. 연결 및 설정에서 모델 목록을 새로고침하세요.': 'The selected model is unavailable in the connected app. Refresh models in Connections & settings.',
  '최근 실행 기록': 'Recent execution events', '실행 완료 · 검증 대기': 'Executed · awaiting verification',
  '결과 관측 · 단계 확인 대기': 'Result observed · stage review pending', '현재 실행 미관측': 'Current execution unobserved',
  '결과 검토 대기': 'Awaiting result review', '사이트 로그인 대기': 'Waiting for site login',
  '동작 승인 대기': 'Waiting for approval', '재시도 가능 실패': 'Retryable failure', '실행 여부 확인 필요': 'Action needs reconciliation',
  '실행기 미관측': 'Executor unobserved', '단계 실행 보고 · 이후 검증 완료': 'Stage execution reported · later verified',
  '최근 활동 기록': 'Recent activity history', '업무 단계 실행': 'Business stage execution',
  '근거가 연결된 단계의 실행 보고 기준입니다. 독립 검증 결과는 별도로 확인하세요.': 'Progress counts evidence-linked stage execution reports. Check independent verification separately.',
  '미등록': 'Not registered', '있음': 'Allowed', '없음': 'Not allowed', '승인됨': 'Approved',
  '직접 요청': 'Your request', '가져온 자동화': 'Imported automation', '프로젝트 코드': 'Project code',
  '외부 에이전트': 'External agent', '로컬 프로젝트': 'Local project', '요청에서 구성': 'From your request',
  '코드에서 추출 · 실행은 미검증': 'Extracted from code · execution not verified',
  '아직 측정되지 않음': 'Not measured yet',
  '여기까지의 결과를 아래에 저장했습니다. 남은 조건을 확인하고 다음 지침을 입력하세요.': 'Results so far are saved below. Review the remaining criteria and add the next instruction.',
  'AI 연결과 사용량을 확인한 뒤 이어가세요. 지금까지의 결과는 그대로 남아 있습니다.': 'Check your AI connection and allowance, then continue. Existing results are kept.',
  '필요한 실행 연결을 준비한 뒤 이어가세요.': 'Prepare the required execution connection, then continue.',
  '사이트 로그인에서 인증을 완료한 뒤 이어가세요.': 'Complete authentication in Site login, then continue.',
  '요청된 동작의 승인을 확인한 뒤 이어가세요.': 'Confirm approval for the requested action, then continue.',
  '저장한 진행 지점에서 자동으로 다시 시도합니다.': 'Automatically retries from the saved checkpoint.',
  '실행을 멈췄습니다. 저장된 결과를 유지한 채 이어갈 수 있습니다.': 'Execution stopped. You can continue with the saved results.',
  '이전 동작이 실제로 반영됐는지 먼저 확인해 주세요. 확인 전에는 다시 실행하지 않습니다.': 'Check whether the earlier action took effect first. It will not be repeated before this is confirmed.',
  '반복 일정 설정을 확인해야 합니다.': 'Check recurring schedule settings.',
  '변경한 지침의 병렬 실행 범위를 확인해야 합니다.': 'Check the parallel execution scope of the changed instructions.',
  '저장된 진행 지점과 실행 경로가 달라 확인이 필요합니다.': 'The execution environment differs from the saved checkpoint. Review it before continuing.',
  '실행을 마치지 못했습니다. 아래 로그에서 원인을 확인하세요.': 'Execution did not finish. See the activity below for the cause.',
  '효율 개선 여부는 아직 측정하지 않았습니다.': 'Efficiency gains have not been measured yet.',
  '기존 LLM 경로 유지': 'Keep the existing AI path', '위치 미확인': 'Location not verified', '프로젝트': 'Project',
  '분석한 업무를 접수란에 넣었습니다. 확인하고 시작하세요.': 'The analyzed work is in the request form. Review it and start.',
  '업무 지침을 입력해 주세요.': 'Enter work instructions.',
  '작업물 확인 방법을 하나 이상 선택해 주세요.': 'Select at least one place to receive results.',
  '업무 계획': 'Work plan', '계획 단계': 'Planned stage',
  'CURRENT LOOP': 'Current progress', 'REVIEW FIRST': 'Review first', 'IMPORT WORK': 'Import work',
  'run not started': 'Not started', 'read-only': 'Read only', 'draft only': 'Draft only',
  'change after approval': 'Changes need approval',
  '설치된 Aside를 찾아 실행 도구로 등록했어요 · 새 연결부터 적용': 'Found the installed Aside and registered it as an execution tool · applies to new connections',
  '사용 중인 Neo를 찾아 실행 도구로 등록했어요 · 새 연결부터 적용': 'Found the Neo you use and registered it as an execution tool · applies to new connections',
  'AI 호출 · 보통 1분 안팎': 'Calls the AI · usually about a minute',
  'AI가 답변을 반영해 계획을 세우는 중이에요. 보통 1분 안팎 걸려요': 'The AI is planning with your answers. This usually takes about a minute',
  '브라우저·로그인': 'Browsers & sign-in', '브라우저와 로그인 환경': 'Browsers and sign-in', '← 브라우저·로그인 설정': '← Browser and sign-in settings',
  // Hermes, remote server and remaining Work texts that had no registered wording (found by the coverage test).
  'Hermes가 실행하고 Driver에서 관리합니다. 원본 대화·예약·인증은 그대로 둡니다.': 'Hermes runs the work and Driver manages it. Original chats, schedules and sign-ins stay as they are.',
  'Hermes 데이터 폴더 · 비워 두면 현재 프로필': 'Hermes data folder · leave blank for the current profile',
  '예약은 원본 Hermes에서 계속 유지됩니다. 새 예약을 만들지 않습니다.': 'Schedules stay in the original Hermes. No new schedule is created.',
  '다음 대화 보기': 'Show more chats',
  '원본 Hermes는 변경하지 않았습니다. 실행이나 예약을 시작하지 않았습니다.': 'The original Hermes was not changed. No run or schedule was started.',
  '첫 실행 전 연결 취소': 'Cancel connection before the first run',
  '가져올 업무 확인': 'Review work to import',
  '같은 원본으로 등록된 업무가 있습니다. 중복 생성하거나 덮어쓰지 않습니다.': 'Work from the same source is already registered. It is not duplicated or overwritten.',
  '기존 업무 보기': 'View existing work',
  '업무 이름': 'Work name',
  '실행 지침': 'Run instructions',
  '완료 조건 · 한 줄에 하나': 'Completion criteria · one per line',
  '업무 단계 · 한 줄에 하나': 'Work stages · one per line',
  '내용을 확인했습니다. Hermes 실행은 유지하고 Driver에 대기 업무로 등록합니다.': 'I reviewed the details. Keep running in Hermes and register this in Driver as queued work.',
  '확인하고 가져오기': 'Review and import',
  '예: /home/me/.hermes': 'Example: /home/me/.hermes',
  'Hermes 실행 · Driver 관리': 'Runs in Hermes · managed in Driver',
  '아직 Hermes가 보고한 실행 단계가 없습니다.': 'Hermes has not reported any run stage yet.',
  '업무 절차': 'Work procedure',
  '가져온 기록': 'Imported records',
  '실제 작업 로그': 'Actual work log',
  'Hermes 승인 요청': 'Hermes approval request',
  '현재 요청 한 번에만 적용됩니다.': 'Applies to this request only.',
  'Hermes에 다음 지시': 'Next instruction for Hermes',
  'Hermes에 설정된 모델로 실행합니다. 설정에 따라 API 비용 또는 구독 사용량이 발생합니다.': 'Runs on the model set in Hermes. Depending on its settings, API charges or subscription usage apply.',
  'Hermes 답변 · 결과 확인 필요': 'Hermes reply · check the result',
  'Hermes 작업 로그': 'Hermes work log',
  '대상 날짜와 원하는 결과를 알려주세요. 제출·전송은 필요할 때 명시해 주세요.': 'Give the target date and the result you want. Say so explicitly when something should be submitted or sent.',
  '업무 제어': 'Work controls',
  '결과 확인 · 다음 지시 준비': 'Check result · prepare next instruction',
  '실행은 서버에서, 관리는 Office에서 합니다. 기존 인증·예약을 옮기지 않습니다.': 'The server runs the work and Office manages it. Existing sign-ins and schedules are not moved.',
  '연결된 서버': 'Connected servers',
  '서버 연결 추가': 'Add server connection',
  '연결 이름': 'Connection name',
  '서버 주소': 'Server address',
  'SSH 사용자': 'SSH user',
  'SSH 포트': 'SSH port',
  'Docker 컨테이너 · 사용 시': 'Docker container · if used',
  '서버의 OpenClaw 실행 파일': 'OpenClaw executable on the server',
  '선택한 대화는 지시·결과·중단을 연결합니다. 예약은 실행 기록만 확인하며 서버가 계속 관리합니다.': 'Selected chats connect instructions, results and stopping. Schedules are read-only run records and stay managed by the server.',
  '가져올 업무': 'Work to import',
  'Office에 연결': 'Connect to Office',
  '일부 목록만 표시합니다. 최신 대화 50개·예약 100개까지 읽었습니다.': 'Showing part of the list. Read up to the latest 50 chats and 100 schedules.',
  '서버 연결을 확인하지 못했습니다. 아래는 마지막 관측 기록입니다.': 'Could not check the server connection. The records below are the last ones seen.',
  '서버 기록': 'Server records',
  'Office 연결 로그': 'Office connection log',
  '서버 상태 새로 확인': 'Check server status again',
  '내가 보낸 실행 중단': 'Stop the run I sent',
  '예약은 서버에서 유지됩니다. 이 연결은 실행 기록 조회 전용입니다.': 'Schedules stay on the server. This connection only reads run records.',
  'OpenClaw에 다음 지시': 'Next instruction for OpenClaw',
  '서버에 설정된 모델 사용량이 발생할 수 있음을 확인했습니다.': 'I understand that usage of the model set on the server may apply.',
  '서버로 지시 보내기': 'Send instruction to server',
  '에이전트가 제안한 지시가 있습니다.': 'The agent suggested an instruction.',
  '지시 초안 불러오기': 'Load instruction draft',
  '모델·인증·원본 예약은 변경하지 않습니다. 연결 실패 때 같은 요청을 자동 반복하지 않습니다.': 'Models, sign-ins and original schedules are not changed. A failed connection does not repeat the same request automatically.',
  '예: 내 서버': 'Example: My server',
  '서버 IP 또는 호스트 이름': 'Server IP or host name',
  '취소': 'Cancel',
  '확인 결과 · 자동 재실행 없음': 'Check result · no automatic rerun',
  '토큰 수는 연결된 CLI가 알려줄 때만 표시됩니다.': 'Token counts appear only when the connected CLI reports them.',
  '코드 분석에 따른 예상이며 실제 개선 폭은 측정하지 않았습니다. Jev를 켜도 원본 코드는 바뀌지 않습니다.': 'An estimate from code analysis; the actual improvement was not measured. Turning Jev on does not change the original code.',
  'Jev API 비용 가능성을 확인하고 이 업무에서 사용을 허용합니다': 'I understand Jev may incur API charges and allow it for this work',
  'Jev 없이 기존 AI와 코드로 진행합니다.': 'Continues with the existing AI and code, without Jev.',
  'Codex 세션 연결': 'Connect Codex session',
  'Codex 대화': 'Codex chat',
};
